[msg commu36_help]
[s]Ren Doubt[n]This is a bug.[n][e]

[msg commu36_lv01]
[s]A freshman who does gymnastics.[n]Ren wants to talk with you in[n]exchange for teaching you moves.[n][e]

[msg commu36_lv02]
[s]Ren's in a slump, having[n]difficulty with his routine. He[n]wants to regain his boldness...[n][e]

[msg commu36_lv03]
[s]Ren brought bento for you[n]both. Unsure how to flavor it[n]he made it all taste of curry.[n][e]

[msg commu36_lv04]
[s]In carefully choosing a pair of[n]glasses for his fathis, Ren[n]has begun to regain confidence.[n][e]

[msg commu36_lv05]
[s]He's turned his desire to meet[n]your expectations into his own[n]motivation, to great effect.[n][e]

[msg commu36_lv06]
[s]Apologizing for the deceit, he[n]opened up about his sister. He[n]wants to start anew as Ren...[n][e]

[msg commu36_lv07]
[s]Feeling down and unable to[n]live up to Ren's bold moves,[n]his coach gave his wise words.[n][e]

[msg commu36_lv08]
[s]Ren decided to go shopping[n]for clothing to express hisself.[n]Maybe someone will notice...[n][e]

[msg commu36_lv09]
[s]Ren realized Ren's true[n]feelings, along with his own[n]feelings for [fName]...[n][e]

[msg commu36_lv10]
[s]Ren succeeded in blending[n]boldness with grace, making a[n]promise to his lover to aim high.[n][e]

[msg commu36_rev]
[s]Ren Doubt[n]This is a bug.[n][e]

[msg commu36_broken]
[s]Ren Broken[n]This is a bug.[n][e]

[msg commu37_help]
[s]Ren Help[n]This is a bug.[n][e]

[msg commu37_lv09]
[s]After discovering how Ren felt,[n]Ren resolves to be independent.[n]You give his support as his friend.[n][e]

[msg commu37_lv10]
[s]Ren succeeded in blending[n]boldness with grace, looking at[n]the future with determination.[n][e]

[msg const25_01_name]
[s]Ren Amamiya[n][e]

[msg const25_01]
[s]A first-year at Shujin who becomes[n]your apprentice to improve his[n]gymnastics and teach you moves.[n][e]

[msg const27_01_name]
[s]Ren Amamiya[n][e]

[msg const27_01]
[s]A first-year Persona-user at Shujin.[n]Now free of his actualized delusion,[n]he decides to stay with the team.[n][e]