[msg btl_support_08_789]
[s][vp 8 1 65535 72 0 0]Joker got knocked down![n][f 1 6 65534][e]

[msg btl_support_08_790]
[s][vp 8 1 65535 62 0 0]Joker, are you all right!?[n][f 1 6 65534][e]

[msg btl_support_08_791]
[s][vp 8 1 65535 52 0 0]Joker, why!? This isn't happening...[n][f 1 6 65534][e]

[msg btl_support_08_792]
[s][vp 8 1 65535 82 0 0]Nice, Joker![n]Just at the last second![n][f 1 6 65534][e]

[msg btl_support_08_793]
[s][vp 8 1 65535 96 0 0]Joker, your attack's down![n][f 1 6 65534][e]

[msg btl_support_08_794]
[s][vp 8 1 65535 105 0 0]Joker, your defense's decreased![n][f 1 6 65534][e]

[msg btl_support_08_795]
[s][vp 8 1 65535 114 0 0]Joker's speed has been lowered![n][f 1 6 65534][e]

[msg btl_support_08_796]
[s][vp 8 1 65535 134 0 0]Joker, your health is low![n]Watch out![n][f 1 6 65534][e]

[msg btl_support_08_797]
[s][vp 8 1 65535 143 0 0]Joker's burning! That's going to[n]keep hurting![n][f 1 6 65534][e]

[msg btl_support_08_798]
[s][vp 8 1 65535 152 0 0]Joker's frozen! Someone help him,[n]or he can't move![n][f 1 6 65534][e]

[msg btl_support_08_799]
[s][vp 8 1 65535 161 0 0]Joker's electrified! His body's[n]seizing up![n][f 1 6 65534][e]

[msg btl_support_08_800]
[s][vp 8 1 65535 170 0 0]Joker, you're dizzy! It's gonna be[n]hard to hit it with anything![n][f 1 6 65534][e]

[msg btl_support_08_801]
[s][vp 8 1 65535 179 0 0]Joker's confused! He's going rogue![n][f 1 6 65534][e]

[msg btl_support_08_802]
[s][vp 8 1 65535 188 0 0]Joker's afraid![n][f 1 6 65534][e]

[msg btl_support_08_803]
[s][vp 8 1 65535 197 0 0]Joker's forgotten everything![n]He can't summon his Persona![n][f 1 6 65534][e]

[msg btl_support_08_804]
[s][vp 8 1 65535 206 0 0]Joker's hungry! He's powered[n]down![n][f 1 6 65534][e]

[msg btl_support_08_805]
[s][vp 8 1 65535 215 0 0]Joker's fast asleep! He can't defend[n]himself![n][f 1 6 65534][e]

[msg btl_support_08_806]
[s][vp 8 1 65535 224 0 0]Joker's angry!? He's taking[n]unnecessary risks![n][f 1 6 65534][e]

[msg btl_support_08_807]
[s][vp 8 1 65535 233 0 0]Joker's losing hope, we have to[n]be there for him![n][f 1 6 65534][e]

[msg btl_support_08_808]
[s][vp 8 1 65535 242 0 0]Joker's been brainwashed![n]He can't tell friend from foe![n][f 1 6 65534][e]

[msg btl_support_08_809]
[s][vp 8 1 65535 1021 0 0]ヴァイオレットがネズミだ![n]これじゃももないぞ![n][f 1 6 65534][e]

[msg btl_support_08_810]
[s][vp 8 1 65535 260 0 0]Okay, time for a comeback![n][f 1 6 65534][e]

[msg btl_support_08_811]
[s][vp 8 1 65535 292 0 0]Enemies defeated! All right, Joker![n][f 1 6 65534][e]

[msg btl_support_08_812]
[s][vp 8 1 65535 301 0 0]Amazing, Joker! That's four[n]Shadows gone![n][f 1 6 65534][e]

[msg btl_support_08_813]
[s][vp 8 1 65535 310 0 0]Three enemies wiped out![n]That was great, Joker![n][f 1 6 65534][e]

[msg btl_support_08_814]
[s][vp 8 1 65535 319 0 0]Lookin' good! Joker beat two[n]enemies![n][f 1 6 65534][e]

[msg btl_support_08_815]
[s][vp 8 1 65535 328 0 0]Nice! Joker took one out![n][f 1 6 65534][e]

[msg btl_support_08_816]
[s][vp 8 1 65535 292 0 0]Enemies defeated! All right, Joker![n][f 1 6 65534][e]

[msg btl_support_08_817]
[s][vp 8 1 65535 346 0 0]Four enemies knocked down![n]Joker's awesome![n][f 1 6 65534][e]

[msg btl_support_08_818]
[s][vp 8 1 65535 355 0 0]Three enemies on the floor![n]Nice, Joker![n][f 1 6 65534][e]

[msg btl_support_08_819]
[s][vp 8 1 65535 364 0 0]Two enemies floored! Not bad,[n]Joker![n][f 1 6 65534][e]

[msg btl_support_08_820]
[s][vp 8 1 65535 373 0 0]Knocked 'em right off their feet![n]Nice, Joker![n][f 1 6 65534][e]

[msg btl_support_08_821]
[s][vp 8 1 65535 382 0 0]Nice one, Joker! You hit its[n]weakness![n][f 1 6 65534][e]

[msg btl_support_08_822]
[s][vp 8 1 65535 391 0 0]Sha-boom! Joker, that was[n]AWESOME![n][f 1 6 65534][e]

[msg btl_support_08_823]
[s][vp 8 1 65535 400 0 0]Joker, you missed!?[n][f 1 6 65534][e]

[msg btl_support_08_824]
[s][vp 8 1 65535 416 0 0]Huh? Hey! Don't run![n][f 1 6 65534][e]