[msg btl_support_09_371]
[s][vp 8 1 65535 364 0 0]That's two knocked down, but you[n]can do more, can't you, Joker?[n][f 1 6 65534][e]

[msg btl_support_09_408]
[s][vp 8 1 65535 400 0 0]They dodged your attack, Joker![n][f 1 6 65534][e]

[msg btl_support_09_789]
[s][vp 8 1 65535 52 0 0]No way, they got Joker?[n][f 1 6 65534][e]

[msg btl_support_09_790]
[s][vp 8 1 65535 1121 0 0]Hey Joker, instead of dying, how[n]about we crush them together!?[n][f 1 6 65534][e]

[msg btl_support_09_791]
[s][vp 8 1 65535 134 0 0]Joker, watch it! You're at death's[n]door![n][f 1 6 65534][e]

[msg btl_support_09_792]
[s][vp 8 1 65535 82 0 0]You make that look easy, Joker.[n][f 1 6 65534][e]

[msg btl_support_09_793]
[s][vp 8 1 65535 96 0 0]Joker, your strength is reduced![n][f 1 6 65534][e]

[msg btl_support_09_794]
[s][vp 8 1 65535 105 0 0]Joker, your defense is[n]compromised![n][f 1 6 65534][e]

[msg btl_support_09_795]
[s][vp 8 1 65535 114 0 0]Joker, you've been slowed down![n][f 1 6 65534][e]

[msg btl_support_09_796]
[s][vp 8 1 65535 60 0 0]Come on, what are you doing!?[n][f 1 6 65534][e]

[msg btl_support_09_797]
[s][vp 8 1 65535 143 0 0]Joker's burning! That's gotta hurt![n][f 1 6 65534][e]

[msg btl_support_09_798]
[s][vp 8 1 65535 152 0 0]Joker's frozen! Do something[n]before it gets worse![n][f 1 6 65534][e]

[msg btl_support_09_799]
[s][vp 8 1 65535 161 0 0]Joker's paralyzed with[n]electricity![n][f 1 6 65534][e]

[msg btl_support_09_800]
[s][vp 8 1 65535 170 0 0]Joker's dizzy—he's not gonna[n]land attacks like that![n][f 1 6 65534][e]

[msg btl_support_09_801]
[s][vp 8 1 65535 179 0 0]Joker's mind is muddled![n]He might do weird stuff while[n]confused![n][f 1 6 65534][e]

[msg btl_support_09_802]
[s][vp 8 1 65535 188 0 0]Joker's scared!? What a sorry sight...[n][f 1 6 65534][e]

[msg btl_support_09_803]
[s][vp 8 1 65535 197 0 0]Joker can't remember anything![n]Least of all his Persona![n][f 1 6 65534][e]

[msg btl_support_09_804]
[s][vp 8 1 65535 206 0 0]Joker's famished and not at his best![n][f 1 6 65534][e]

[msg btl_support_09_805]
[s][vp 8 1 65535 215 0 0]Joker's asleep! Wake him up[n]before he gets killed![n][f 1 6 65534][e]

[msg btl_support_09_806]
[s][vp 8 1 65535 224 0 0]Joker's enraged? I kind of like it,[n]but it's not you! Calm down![n][f 1 6 65534][e]

[msg btl_support_09_807]
[s][vp 8 1 65535 233 0 0]Joker's in despair! Do something[n]before he gets himself killed![n][f 1 6 65534][e]

[msg btl_support_09_808]
[s][vp 8 1 65535 242 0 0]Joker's more brainwashed than a[n]cult member! He can't tell friend[n]from foe![n][f 1 6 65534][e]

[msg btl_support_09_809]
[s][vp 8 1 65535 1021 0 0]かすみがネズミ状態だ![n]何もできやしないだろう![n][f 1 6 65534][e]

[msg btl_support_09_810]
[s][vp 8 1 65535 260 0 0]Joker's back! Time to retaliate.[n][f 1 6 65534][e]

[msg btl_support_09_811]
[s][vp 8 1 65535 292 0 0]Damn, Joker! You wiped 'em out![n][f 1 6 65534][e]

[msg btl_support_09_812]
[s][vp 8 1 65535 301 0 0]Four enemies dispatched by Joker![n][f 1 6 65534][e]

[msg btl_support_09_813]
[s][vp 8 1 65535 310 0 0]Three enemies eliminated at once![n]That was rather enchanting.[n][f 1 6 65534][e]

[msg btl_support_09_814]
[s][vp 8 1 65535 319 0 0]Joker got a two-for-one deal there![n][f 1 6 65534][e]

[msg btl_support_09_815]
[s][vp 8 1 65535 328 0 0]Joker took one down! I gotta[n]keep up.[n][f 1 6 65534][e]

[msg btl_support_09_818]
[s][vp 8 1 65535 355 0 0]You knocked three down![n]Now crush them, Joker![n][f 1 6 65534][e]

[msg btl_support_09_821]
[s][vp 8 1 65535 382 0 0]Nice, Joker. You hit it where[n]it's weak.[n][f 1 6 65534][e]

[msg btl_support_09_822]
[s][vp 8 1 65535 391 0 0]Whoa, good hit, Joker![n][f 1 6 65534][e]

[msg btl_support_09_824]
[s][vp 8 1 65535 419 0 0]Hey! What are you doing?[n][f 1 6 65534][e]

