[msg btl_support_09_050]
[s][vp 8 1 65535 1003 0 0]Yoshizawa-san fell down! Come on,[n]we gotta be more careful than this![n][f 1 6 65534][e]

[msg btl_support_09_051]
[s][vp 8 1 65535 1001 0 0]Yoshizawa-san! Wasn't anyone[n]paying attention to her!?[n][f 1 6 65534][e]

[msg btl_support_09_052]
[s][vp 8 1 65535 1001 0 0]Yoshizawa-san! Wasn't anyone[n]paying attention to her!?[n][f 1 6 65534][e]

[msg btl_support_09_062]
[s][vp 8 1 65535 1002 0 0]Yoshizawa-san is cornered![n]Help her or she'll die![n][f 1 6 65534][e]

[msg btl_support_09_072]
[s][vp 8 1 65535 1003 0 0]Yoshizawa-san fell down! Come on,[n]we gotta be more careful than this![n][f 1 6 65534][e]

[msg btl_support_09_082]
[s][vp 8 1 65535 1004 0 0]Nice move, Yoshizawa-san![n][f 1 6 65534][e]

[msg btl_support_09_096]
[s][vp 8 1 65535 1005 0 0]Yoshizawa-san's attack is lowered![n][f 1 6 65534][e]

[msg btl_support_09_105]
[s][vp 8 1 65535 1006 0 0]Yoshizawa-san's defense is[n]compromised![n][f 1 6 65534][e]

[msg btl_support_09_114]
[s][vp 8 1 65535 1007 0 0]Yoshizawa-san's speed is lowered![n][f 1 6 65534][e]

[msg btl_support_09_134]
[s][vp 8 1 65535 1008 0 0]Yoshizawa-san's in danger of dying![n][f 1 6 65534][e]

[msg btl_support_09_143]
[s][vp 8 1 65535 1009 0 0]Yoshizawa-san is burning![n]Can anyone put her out!?[n][f 1 6 65534][e]

[msg btl_support_09_152]
[s][vp 8 1 65535 1010 0 0]Yoshizawa-san's frozen! Somebody[n]help her![n][f 1 6 65534][e]

[msg btl_support_09_161]
[s][vp 8 1 65535 1011 0 0]Yoshizawa-san is paralyzed by[n]electricity![n][f 1 6 65534][e]

[msg btl_support_09_170]
[s][vp 8 1 65535 1012 0 0]Yoshizawa-san is dizzy! It'll be[n]a lot harder for her to land a hit![n][f 1 6 65534][e]

[msg btl_support_09_179]
[s][vp 8 1 65535 1013 0 0]Oh, perfect, Yoshizawa-san's[n]confused![n][f 1 6 65534][e]

[msg btl_support_09_188]
[s][vp 8 1 65535 1014 0 0]Yoshizawa-san's scared to death![n]Do something before she just[n]runs away![n][f 1 6 65534][e]

[msg btl_support_09_197]
[s][vp 8 1 65535 1015 0 0]Yoshizawa-san's memory is[n]damaged! She can't remember[n]her Persona![n][f 1 6 65534][e]

[msg btl_support_09_206]
[s][vp 8 1 65535 1016 0 0]Yoshizawa-san is starving![n]She's lost a lot of strength![n][f 1 6 65534][e]

[msg btl_support_09_215]
[s][vp 8 1 65535 1017 0 0]Yoshizawa-san's asleep! Someone[n]give her a wake-up call![n][f 1 6 65534][e]

[msg btl_support_09_224]
[s][vp 8 1 65535 1018 0 0]Yoshizawa-san's enraged![n]Calm her down![n][f 1 6 65534][e]

[msg btl_support_09_233]
[s][vp 8 1 65535 1019 0 0]Yoshizawa-san is despairing![n]Do something to help her![n][f 1 6 65534][e]

[msg btl_support_09_242]
[s][vp 8 1 65535 1020 0 0]Yoshizawa-san got brainwashed![n]She's being controlled by the[n]enemy![n][f 1 6 65534][e]

[msg btl_support_09_251]
[s][vp 8 1 65535 259 0 0]You can't do anything as a mouse![n]Just run away![n][f 1 6 65534][e]

[msg btl_support_09_260]
[s][vp 8 1 65535 1022 0 0]Yoshizawa-san is back up![n]Now she can get back at 'em![n][f 1 6 65534][e]

[msg btl_support_09_292]
[s][vp 8 1 65535 1023 0 0]Whoooa, all enemies wiped out![n]Pretty damn good, Yoshizawa-san.[n][f 1 6 65534][e]

[msg btl_support_09_301]
[s][vp 8 1 65535 1024 0 0]Yoshizawa-san killed four enemies[n]at once. Quite the show![n][f 1 6 65534][e]

[msg btl_support_09_310]
[s][vp 8 1 65535 1025 0 0]Heyyy, Yoshizawa-san's pretty[n]good! She just took out three[n]enemies.[n][f 1 6 65534][e]

[msg btl_support_09_319]
[s][vp 8 1 65535 1026 0 0]Yoshizawa-san just killed two[n]enemies! Who can do better?[n][f 1 6 65534][e]

[msg btl_support_09_328]
[s][vp 8 1 65535 1027 0 0]One enemy taken out by[n]Yoshizawa-san. Nice![n][f 1 6 65534][e]

[msg btl_support_09_337]
[s][vp 8 1 65535 1028 0 0]They're all on the ground![n]Crush them![n][f 1 6 65534][e]

[msg btl_support_09_346]
[s][vp 8 1 65535 1029 0 0]Four enemies on the floor and[n]no need to hold back![n][f 1 6 65534][e]

[msg btl_support_09_355]
[s][vp 8 1 65535 1030 0 0]Three enemies downed by[n]Yoshizawa-san![n][f 1 6 65534][e]

[msg btl_support_09_364]
[s][vp 8 1 65535 1031 0 0]Two enemies knocked over![n]Not bad.[n][f 1 6 65534][e]

[msg btl_support_09_373]
[s][vp 8 1 65535 1032 0 0]Good, one got knocked down![n][f 1 6 65534][e]

[msg btl_support_09_382]
[s][vp 8 1 65535 1033 0 0]Yoshizawa-san has the right idea,[n]exploiting their weakness![n][f 1 6 65534][e]

[msg btl_support_09_391]
[s][vp 8 1 65535 408 0 0]You missed!? Open your eyes![n][f 1 6 65534][e]

[msg btl_support_09_471]
[s][vp 8 1 65535 1003 0 0]Violet! Please get up![n][f 1 6 65534][e]

[msg btl_support_09_472]
[s][vp 8 1 65535 1003 0 0]Violet! Please get up![n][f 1 6 65534][e]

[msg btl_support_09_473]
[s][vp 8 1 65535 1003 0 0]Violet! Please get up![n][f 1 6 65534][e]

[msg btl_support_09_474]
[s][vp 8 1 65535 1003 0 0]Violet! Please get up![n][f 1 6 65534][e]

[msg btl_support_09_476]
[s][vp 8 1 65535 1003 0 0]Violet! Please get up![n][f 1 6 65534][e]

[msg btl_support_09_477]
[s][vp 8 1 65535 1003 0 0]Violet! Please get up![n][f 1 6 65534][e]

[msg btl_support_09_742]
[s][vp 8 1 65535 1034 0 0]A critical hit by Yoshizawa-san.[n][f 1 6 65534][e]

[msg btl_support_09_873]
[s][vp 8 1 65535 1022 0 0]Yoshizawa-san is back up![n]Now she can get back at 'em![n][f 1 6 65534][e]

[msg btl_support_09_909]
[s][vp 8 1 65535 1002 0 0]Yoshizawa-san is cornered![n]Help her or she'll die![n][f 1 6 65534][e]

[msg btl_support_09_910]
[s][vp 8 1 65535 1172 0 0]We gotta stand up for our friend![n][f 1 6 65534][e]