[msg btl_support_08_001]
[s][vp 8 1 65535 1 0 0]You're surrounded! Three enemies![n][f 1 6 65534][e]

[msg btl_support_08_002]
[s][vp 8 1 65535 2 0 0]Watch out! Strong enemies, and[n]they've got you surrounded![n][f 1 6 65534][e]

[msg btl_support_08_003]
[s][vp 8 1 65535 3 0 0]You're surrounded by weaklings![n]What, did they sneak up on you?[n][f 1 6 65534][e]

[msg btl_support_08_004]
[s][vp 8 1 65535 4 0 0]Ugh... We don't have time for this![n][f 1 6 65534][e]

[msg btl_support_08_005]
[s][vp 8 1 65535 5 0 0]Four Shadows, and they've got[n]the drop on you![n][f 1 6 65534][e]

[msg btl_support_08_006]
[s][vp 8 1 65535 6 0 0]They ambushed us! It's four tough[n]enemies![n][f 1 6 65534][e]

[msg btl_support_08_007]
[s][vp 8 1 65535 7 0 0]Four enemies! You're surrounded,[n]but they're pretty weak![n][f 1 6 65534][e]

[msg btl_support_08_008]
[s][vp 8 1 65535 8 0 0]Just get around them! Gah, you're[n]surrounded![n][f 1 6 65534][e]

[msg btl_support_08_009]
[s][vp 8 1 65535 9 0 0]You're cornered... Just try to[n]survive, okay?[n][f 1 6 65534][e]

[msg btl_support_08_010]
[s][vp 8 1 65535 10 0 0]There are five strong ones around[n]you! We need some kinda miracle![n][f 1 6 65534][e]

[msg btl_support_08_011]
[s][vp 8 1 65535 11 0 0]Don't worry! You're surrounded,[n]but they're all kinda pathetic.[n][f 1 6 65534][e]

[msg btl_support_08_012]
[s][vp 8 1 65535 12 0 0]Awww, how'd this happen!?[n]We don't have time for a big[n]brawl![n][f 1 6 65534][e]

[msg btl_support_08_013]
[s][vp 8 1 65535 13 0 0]Now's our chance! Beat 'em up![n][f 1 6 65534][e]

[msg btl_support_08_014]
[s][vp 8 1 65535 14 0 0]We've got them surrounded—[n]now whoop 'em![n][f 1 6 65534][e]

[msg btl_support_08_015]
[s][vp 8 1 65535 15 0 0]Surprise attack: successful![n]Now just don't lose.[n][f 1 6 65534][e]

[msg btl_support_08_016]
[s][vp 8 1 65535 16 0 0]You've got them surrounded![n]Now smash 'em![n][f 1 6 65534][e]

[msg btl_support_08_017]
[s][vp 8 1 65535 17 0 0]We've got the advantage![n]Don't rush this![n][f 1 6 65534][e]

[msg btl_support_08_018]
[s][vp 8 1 65535 18 0 0]We've rounded them up![n]Now take 'em out![n][f 1 6 65534][e]

[msg btl_support_08_019]
[s][vp 8 1 65535 19 0 0]As long as we got them[n]surrounded, we might as[n]well beat them![n][f 1 6 65534][e]

[msg btl_support_08_020]
[s][vp 8 1 65535 20 0 0]You know, you could always run![n][f 1 6 65534][e]

[msg btl_support_08_021]
[s][vp 8 1 65535 21 0 0]This chump is down! Let's get 'em![n][f 1 6 65534][e]

[msg btl_support_08_022]
[s][vp 8 1 65535 22 0 0]Scatter them![n][f 1 6 65534][e]

[msg btl_support_08_023]
[s][vp 8 1 65535 23 0 0]Finish 'em off![n][f 1 6 65534][e]

[msg btl_support_08_024]
[s][vp 8 1 65535 24 0 0]Whoa, this Shadow looks strong![n][f 1 6 65534][e]

[msg btl_support_08_025]
[s][vp 8 1 65535 25 0 0]Is that a rare one!? Don't let it[n]get away![n][f 1 6 65534][e]

[msg btl_support_08_026]
[s][vp 8 1 65535 26 0 0]One enemy! Everyone do your best![n][f 1 6 65534][e]

[msg btl_support_08_027]
[s][vp 8 1 65535 27 0 0]It's strong, but there's just one![n]Don't get sloppy now![n][f 1 6 65534][e]

[msg btl_support_08_028]
[s][vp 8 1 65535 28 0 0]One enemy, and it's weak![n]This'll be a slaughter![n][f 1 6 65534][e]

[msg btl_support_08_029]
[s][vp 8 1 65535 29 0 0]Just one enemy. Beat it and[n]move on![n][f 1 6 65534][e]

[msg btl_support_08_030]
[s][vp 8 1 65535 30 0 0]Two foes. You can take this[n]nice and easy.[n][f 1 6 65534][e]

[msg btl_support_08_031]
[s][vp 8 1 65535 31 0 0]Two enemies! They're strong,[n]so watch out![n][f 1 6 65534][e]

[msg btl_support_08_032]
[s][vp 8 1 65535 32 0 0]Enemies! Don't worry, though.[n]They're no big deal.[n][f 1 6 65534][e]

[msg btl_support_08_033]
[s][vp 8 1 65535 33 0 0]Two enemies! We can't waste time[n]on these guys![n][f 1 6 65534][e]

[msg btl_support_08_034]
[s][vp 8 1 65535 34 0 0]There's three Shadows. Good luck![n][f 1 6 65534][e]

[msg btl_support_08_035]
[s][vp 8 1 65535 35 0 0]Three enemies, and they're all[n]pretty strong. Be careful![n][f 1 6 65534][e]

[msg btl_support_08_036]
[s][vp 8 1 65535 36 0 0]Three enemies. They're weak,[n]but don't let your guard down![n][f 1 6 65534][e]

[msg btl_support_08_037]
[s][vp 8 1 65535 37 0 0]We don't have time to fight three[n]whole enemies! What do we do!?[n][f 1 6 65534][e]

[msg btl_support_08_038]
[s][vp 8 1 65535 38 0 0]Four enemies! There's a lot of 'em...[n]C'mon, do something![n][f 1 6 65534][e]

[msg btl_support_08_039]
[s][vp 8 1 65535 39 0 0]Four enemies, and they're strong![n]This really sucks...[n][f 1 6 65534][e]

[msg btl_support_08_040]
[s][vp 8 1 65535 40 0 0]Four enemies! They're pretty[n]pathetic, but stay on guard![n][f 1 6 65534][e]

[msg btl_support_08_041]
[s][vp 8 1 65535 41 0 0]There's four enemies. You should[n]probably just run![n][f 1 6 65534][e]

[msg btl_support_08_042]
[s][vp 8 1 65535 42 0 0]Five enemies! You guys are[n]outnumbered. Be careful![n][f 1 6 65534][e]

[msg btl_support_08_043]
[s][vp 8 1 65535 43 0 0]Five strong Shadows... Brace[n]yourselves, guys![n][f 1 6 65534][e]

[msg btl_support_08_044]
[s][vp 8 1 65535 44 0 0]Five Shadows! They're weak,[n]but don't relax yet![n][f 1 6 65534][e]

[msg btl_support_08_045]
[s][vp 8 1 65535 45 0 0]Five of them!? We don't have time[n]for this![n][f 1 6 65534][e]

[msg btl_support_08_046]
[s][vp 8 1 65535 46 0 0]Do they have some treasure?[n][f 1 6 65534][e]

[msg btl_support_08_047]
[s][vp 8 1 65535 47 0 0]Hiding something from us?[n][f 1 6 65534][e]

[msg btl_support_08_048]
[s][vp 8 1 65535 48 0 0]Hrm! I smell treasure...[n][f 1 6 65534][e]

[msg btl_support_08_049]
[s][vp 8 1 65535 49 0 0]We've got casualties! This is bad![n][f 1 6 65534][e]

[msg btl_support_08_050]
[s][vp 8 1 65535 50 0 0]Joker!? No... Answer me![n][f 1 6 65534][e]

[msg btl_support_08_051]
[s][vp 8 1 65535 51 0 0]No! Hey, Joker! Joker... you have to[n]wake up![n][f 1 6 65534][e]

[msg btl_support_08_052]
[s][vp 8 1 65535 52 0 0]Joker, why!? This isn't happening...[n][f 1 6 65534][e]

[msg btl_support_08_053]
[s][vp 8 1 65535 53 0 0]Skull's out! Someone help him![n][f 1 6 65534][e]

[msg btl_support_08_054]
[s][vp 8 1 65535 54 0 0]Mona got knocked out! Someone[n]give him some support![n][f 1 6 65534][e]

[msg btl_support_08_055]
[s][vp 8 1 65535 55 0 0]Panther's down! She needs[n]treatment![n][f 1 6 65534][e]

[msg btl_support_08_056]
[s][vp 8 1 65535 56 0 0]Fox got taken out! Medic![n][f 1 6 65534][e]

[msg btl_support_08_057]
[s][vp 8 1 65535 57 0 0]Queen's been taken out![n]You gotta cover for her![n][f 1 6 65534][e]

[msg btl_support_08_058]
[s][vp 8 1 65535 58 0 0]Noir's been defeated! Can someone[n]heal her?[n][f 1 6 65534][e]

[msg btl_support_08_059]
[s][vp 8 1 65535 59 0 0]Crow's down! We need backup[n]here![n][f 1 6 65534][e]

[msg btl_support_08_060]
[s][vp 8 1 65535 60 0 0]No! Come on, wake up![n][f 1 6 65534][e]

[msg btl_support_08_061]
[s][vp 8 1 65535 61 0 0]Everyone, are you okay? Focus on[n]healing up![n][f 1 6 65534][e]

[msg btl_support_08_062]
[s][vp 8 1 65535 62 0 0]Joker, are you all right!?[n][f 1 6 65534][e]

[msg btl_support_08_063]
[s][vp 8 1 65535 63 0 0]Skull's in trouble![n][f 1 6 65534][e]

[msg btl_support_08_064]
[s][vp 8 1 65535 64 0 0]Mona's health is low![n][f 1 6 65534][e]

[msg btl_support_08_065]
[s][vp 8 1 65535 65 0 0]Watch Panther's health![n][f 1 6 65534][e]

[msg btl_support_08_066]
[s][vp 8 1 65535 66 0 0]Fox is swaying![n][f 1 6 65534][e]

[msg btl_support_08_067]
[s][vp 8 1 65535 67 0 0]Queen's in danger![n][f 1 6 65534][e]

[msg btl_support_08_068]
[s][vp 8 1 65535 68 0 0]Noir doesn't have much health left![n][f 1 6 65534][e]

[msg btl_support_08_069]
[s][vp 8 1 65535 69 0 0]Crow's life is in danger![n][f 1 6 65534][e]

[msg btl_support_08_070]
[s][vp 8 1 65535 70 0 0]Your health is low! Watch out![n][f 1 6 65534][e]

[msg btl_support_08_071]
[s][vp 8 1 65535 71 0 0]J-Just hold on and push through![n]We can come back from this![n][f 1 6 65534][e]

[msg btl_support_08_072]
[s][vp 8 1 65535 72 0 0]Joker got knocked down![n][f 1 6 65534][e]

[msg btl_support_08_073]
[s][vp 8 1 65535 73 0 0]Skull fell down! Hang in there![n][f 1 6 65534][e]

[msg btl_support_08_074]
[s][vp 8 1 65535 74 0 0]Mona's down! Ooooh, not good![n][f 1 6 65534][e]

[msg btl_support_08_075]
[s][vp 8 1 65535 75 0 0]Panther's on the ground![n]Are you okay?[n][f 1 6 65534][e]

[msg btl_support_08_076]
[s][vp 8 1 65535 76 0 0]Fox got knocked down! Come on,[n]stay together![n][f 1 6 65534][e]

[msg btl_support_08_077]
[s][vp 8 1 65535 77 0 0]Queen's on the ground![n]You can't fail now![n][f 1 6 65534][e]

[msg btl_support_08_078]
[s][vp 8 1 65535 78 0 0]Noir! Are you okay?[n][f 1 6 65534][e]

[msg btl_support_08_079]
[s][vp 8 1 65535 79 0 0]Crow got knocked down![n]He needs cover![n][f 1 6 65534][e]

[msg btl_support_08_080]
[s][vp 8 1 65535 80 0 0]Ah, you got knocked down![n][f 1 6 65534][e]

[msg btl_support_08_081]
[s][vp 8 1 65535 81 0 0]Whoooaaa... That was awesome![n][f 1 6 65534][e]

[msg btl_support_08_082]
[s][vp 8 1 65535 82 0 0]Nice, Joker![n]Just at the last second![n][f 1 6 65534][e]

[msg btl_support_08_083]
[s][vp 8 1 65535 83 0 0]Skull's pretty good![n][f 1 6 65534][e]

[msg btl_support_08_084]
[s][vp 8 1 65535 84 0 0]That was awesome, Mona![n][f 1 6 65534][e]

[msg btl_support_08_085]
[s][vp 8 1 65535 85 0 0]And Panther dodges with grace![n][f 1 6 65534][e]

[msg btl_support_08_086]
[s][vp 8 1 65535 86 0 0]Nice moves, Fox![n][f 1 6 65534][e]

[msg btl_support_08_087]
[s][vp 8 1 65535 87 0 0]All right, Queen![n][f 1 6 65534][e]

[msg btl_support_08_088]
[s][vp 8 1 65535 88 0 0]Noir dodged the enemy's attack![n][f 1 6 65534][e]

[msg btl_support_08_089]
[s][vp 8 1 65535 89 0 0]Crow's got some moves![n][f 1 6 65534][e]

[msg btl_support_08_090]
[s][vp 8 1 65535 90 0 0]Ooh, nice dodge![n][f 1 6 65534][e]

[msg btl_support_08_091]
[s][vp 8 1 65535 91 0 0]An enemy ran off! Four left![n][f 1 6 65534][e]

[msg btl_support_08_092]
[s][vp 8 1 65535 92 0 0]Enemy escaped! Three remaining![n][f 1 6 65534][e]

[msg btl_support_08_093]
[s][vp 8 1 65535 93 0 0]Ooh, an enemy ditched![n]That leaves two![n][f 1 6 65534][e]

[msg btl_support_08_094]
[s][vp 8 1 65535 94 0 0]One enemy ran, so that leaves[n]just one![n][f 1 6 65534][e]

[msg btl_support_08_095]
[s][vp 8 1 65535 95 0 0]They ran away... and then there[n]were none![n][f 1 6 65534][e]

[msg btl_support_08_096]
[s][vp 8 1 65535 96 0 0]Joker, your attack's down![n][f 1 6 65534][e]

[msg btl_support_08_097]
[s][vp 8 1 65535 97 0 0]Skull, your attack has dropped![n][f 1 6 65534][e]

[msg btl_support_08_098]
[s][vp 8 1 65535 98 0 0]Mona's offense has been lowered![n][f 1 6 65534][e]

[msg btl_support_08_099]
[s][vp 8 1 65535 99 0 0]Panther, your attack power's[n]lowered![n][f 1 6 65534][e]

[msg btl_support_08_100]
[s][vp 8 1 65535 100 0 0]Fox, your offense is down![n][f 1 6 65534][e]

[msg btl_support_08_101]
[s][vp 8 1 65535 101 0 0]Queen, your attack's been lowered![n][f 1 6 65534][e]

[msg btl_support_08_102]
[s][vp 8 1 65535 102 0 0]Noir, your offense's been[n]decreased![n][f 1 6 65534][e]

[msg btl_support_08_103]
[s][vp 8 1 65535 103 0 0]Crow's offense is lowered![n][f 1 6 65534][e]

[msg btl_support_08_104]
[s][vp 8 1 65535 104 0 0]Your attack's lowered![n][f 1 6 65534][e]

[msg btl_support_08_105]
[s][vp 8 1 65535 105 0 0]Joker, your defense's decreased![n][f 1 6 65534][e]

[msg btl_support_08_106]
[s][vp 8 1 65535 106 0 0]Skull's defense is down![n][f 1 6 65534][e]

[msg btl_support_08_107]
[s][vp 8 1 65535 107 0 0]Mona's defense has dropped![n][f 1 6 65534][e]

[msg btl_support_08_108]
[s][vp 8 1 65535 108 0 0]Panther, your defense has dropped![n][f 1 6 65534][e]

[msg btl_support_08_109]
[s][vp 8 1 65535 109 0 0]Fox, your defense's been lowered![n][f 1 6 65534][e]

[msg btl_support_08_110]
[s][vp 8 1 65535 110 0 0]Queen, your defense's been[n]lowered![n][f 1 6 65534][e]

[msg btl_support_08_111]
[s][vp 8 1 65535 111 0 0]Noir, you have lower defense[n]right now![n][f 1 6 65534][e]

[msg btl_support_08_112]
[s][vp 8 1 65535 112 0 0]Crow's defense is low right now![n][f 1 6 65534][e]

[msg btl_support_08_113]
[s][vp 8 1 65535 113 0 0]Your defense has dropped![n]Be careful![n][f 1 6 65534][e]

[msg btl_support_08_114]
[s][vp 8 1 65535 114 0 0]Joker's speed has been lowered![n][f 1 6 65534][e]

[msg btl_support_08_115]
[s][vp 8 1 65535 115 0 0]Uh-oh! Skull's agility is down![n][f 1 6 65534][e]

[msg btl_support_08_116]
[s][vp 8 1 65535 116 0 0]Mona, your speed is lowered![n][f 1 6 65534][e]

[msg btl_support_08_117]
[s][vp 8 1 65535 117 0 0]Your speed's decreased, Panther![n][f 1 6 65534][e]

[msg btl_support_08_118]
[s][vp 8 1 65535 118 0 0]Fox's speed has dropped![n][f 1 6 65534][e]

[msg btl_support_08_119]
[s][vp 8 1 65535 119 0 0]Queen, your agility's been lowered![n][f 1 6 65534][e]

[msg btl_support_08_120]
[s][vp 8 1 65535 120 0 0]Noir! Don't forget your speed's[n]been lowered![n][f 1 6 65534][e]

[msg btl_support_08_121]
[s][vp 8 1 65535 121 0 0]Crow's agility is currently down![n][f 1 6 65534][e]

[msg btl_support_08_122]
[s][vp 8 1 65535 122 0 0]Your speed is down, so watch it![n][f 1 6 65534][e]

[msg btl_support_08_123]
[s][vp 8 1 65535 123 0 0]Five left! Take'em down one at[n]a time![n][f 1 6 65534][e]

[msg btl_support_08_124]
[s][vp 8 1 65535 124 0 0]Five enemies! They still[n]outnumber us...[n][f 1 6 65534][e]

[msg btl_support_08_125]
[s][vp 8 1 65535 125 0 0]Four remaining! Hang in there![n][f 1 6 65534][e]

[msg btl_support_08_126]
[s][vp 8 1 65535 126 0 0]There's four enemies left![n]Stand your ground![n][f 1 6 65534][e]

[msg btl_support_08_127]
[s][vp 8 1 65535 127 0 0]Three enemies remaining![n]You can do it![n][f 1 6 65534][e]

[msg btl_support_08_128]
[s][vp 8 1 65535 128 0 0]There's still three enemies.[n]Keep it up![n][f 1 6 65534][e]

[msg btl_support_08_129]
[s][vp 8 1 65535 129 0 0]Two enemies left. But don't mess[n]this up![n][f 1 6 65534][e]

[msg btl_support_08_130]
[s][vp 8 1 65535 130 0 0]That makes two! Don't lose![n][f 1 6 65534][e]

[msg btl_support_08_131]
[s][vp 8 1 65535 131 0 0]One enemy remaining![n]Just a little more![n][f 1 6 65534][e]

[msg btl_support_08_132]
[s][vp 8 1 65535 132 0 0]Last one! Get 'em![n][f 1 6 65534][e]

[msg btl_support_08_133]
[s][vp 8 1 65535 133 0 0]Everyone's health is really low![n]Can someone heal!?[n][f 1 6 65534][e]

[msg btl_support_08_134]
[s][vp 8 1 65535 134 0 0]Joker, your health is low![n]Watch out![n][f 1 6 65534][e]

[msg btl_support_08_135]
[s][vp 8 1 65535 135 0 0]Skull, are you okay? Keep an eye[n]on your health.[n][f 1 6 65534][e]

[msg btl_support_08_136]
[s][vp 8 1 65535 136 0 0]Mona's in trouble! He's hurt bad![n][f 1 6 65534][e]

[msg btl_support_08_137]
[s][vp 8 1 65535 137 0 0]Panther's in bad shape! Watch out![n][f 1 6 65534][e]

[msg btl_support_08_138]
[s][vp 8 1 65535 138 0 0]Fox's health is really low![n]You have to be careful![n][f 1 6 65534][e]

[msg btl_support_08_139]
[s][vp 8 1 65535 139 0 0]Queen's in trouble! It looks bad![n][f 1 6 65534][e]

[msg btl_support_08_140]
[s][vp 8 1 65535 140 0 0]Ah! Noir's health! She needs help![n][f 1 6 65534][e]

[msg btl_support_08_141]
[s][vp 8 1 65535 141 0 0]Crow doesn't have much health[n]left! Someone heal him![n][f 1 6 65534][e]

[msg btl_support_08_142]
[s][vp 8 1 65535 142 0 0]Your health is dangerously low![n]Hurry up and heal![n][f 1 6 65534][e]

[msg btl_support_08_143]
[s][vp 8 1 65535 143 0 0]Joker's burning! That's going to[n]keep hurting![n][f 1 6 65534][e]

[msg btl_support_08_144]
[s][vp 8 1 65535 144 0 0]Skull's on fire! Don't move around[n]or you'll make it worse![n][f 1 6 65534][e]

[msg btl_support_08_145]
[s][vp 8 1 65535 145 0 0]Mona's burning! Put it out[n]or it'll keep hurting him![n][f 1 6 65534][e]

[msg btl_support_08_146]
[s][vp 8 1 65535 146 0 0]Panther's on fire! Hurry up and[n]put it out![n][f 1 6 65534][e]

[msg btl_support_08_147]
[s][vp 8 1 65535 147 0 0]Fox is on fire! The flames are[n]wearing him down![n][f 1 6 65534][e]

[msg btl_support_08_148]
[s][vp 8 1 65535 148 0 0]Queen's burning! W-We gotta[n]put it out![n][f 1 6 65534][e]

[msg btl_support_08_149]
[s][vp 8 1 65535 149 0 0]Noir's on fire! She can't take much[n]more of this![n][f 1 6 65534][e]

[msg btl_support_08_150]
[s][vp 8 1 65535 150 0 0]Crow's burning! He'll lose health![n][f 1 6 65534][e]

[msg btl_support_08_151]
[s][vp 8 1 65535 151 0 0]You're burning! The pain's going[n]to keep coming![n][f 1 6 65534][e]

[msg btl_support_08_152]
[s][vp 8 1 65535 152 0 0]Joker's frozen! Someone help him,[n]or he can't move![n][f 1 6 65534][e]

[msg btl_support_08_153]
[s][vp 8 1 65535 153 0 0]Skull's on ice! He can't move![n][f 1 6 65534][e]

[msg btl_support_08_154]
[s][vp 8 1 65535 154 0 0]Mona's frozen! He can't move![n][f 1 6 65534][e]

[msg btl_support_08_155]
[s][vp 8 1 65535 155 0 0]Panther's frozen! She won't be able[n]to move![n][f 1 6 65534][e]

[msg btl_support_08_156]
[s][vp 8 1 65535 156 0 0]Fox is frozen solid! He can't make[n]any moves![n][f 1 6 65534][e]

[msg btl_support_08_157]
[s][vp 8 1 65535 157 0 0]Queen's on ice! This isn't good...[n]She can't move![n][f 1 6 65534][e]

[msg btl_support_08_158]
[s][vp 8 1 65535 158 0 0]Noir's frozen! She can't move[n]like that![n][f 1 6 65534][e]

[msg btl_support_08_159]
[s][vp 8 1 65535 159 0 0]Crow's frozen. He can't move![n][f 1 6 65534][e]

[msg btl_support_08_160]
[s][vp 8 1 65535 160 0 0]You're frozen solid! You can't[n]move like this![n][f 1 6 65534][e]

[msg btl_support_08_161]
[s][vp 8 1 65535 161 0 0]Joker's electrified! His body's[n]seizing up![n][f 1 6 65534][e]

[msg btl_support_08_162]
[s][vp 8 1 65535 162 0 0]Skull's been shocked! He can't[n]move as well now![n][f 1 6 65534][e]

[msg btl_support_08_163]
[s][vp 8 1 65535 163 0 0]Mona's been shocked! He won't[n]be able to move that well![n][f 1 6 65534][e]

[msg btl_support_08_164]
[s][vp 8 1 65535 164 0 0]Panther's been shocked! She might[n]not be able to move![n][f 1 6 65534][e]

[msg btl_support_08_165]
[s][vp 8 1 65535 165 0 0]Fox's been shocked! Just tough it[n]out for now![n][f 1 6 65534][e]

[msg btl_support_08_166]
[s][vp 8 1 65535 166 0 0]Queen's been shocked! There's[n]something wrong with her[n]movement![n][f 1 6 65534][e]

[msg btl_support_08_167]
[s][vp 8 1 65535 167 0 0]She's been shocked, and she can't[n]move! Someone help Noir![n][f 1 6 65534][e]

[msg btl_support_08_168]
[s][vp 8 1 65535 168 0 0]Crow's been shocked and can't[n]move! Just hold on![n][f 1 6 65534][e]

[msg btl_support_08_169]
[s][vp 8 1 65535 169 0 0]Agh, you've been shocked![n]You might not be able to move![n][f 1 6 65534][e]

[msg btl_support_08_170]
[s][vp 8 1 65535 170 0 0]Joker, you're dizzy! It's gonna be[n]hard to hit it with anything![n][f 1 6 65534][e]

[msg btl_support_08_171]
[s][vp 8 1 65535 171 0 0]Skull's dizzy! He might not be able[n]to land a hit![n][f 1 6 65534][e]

[msg btl_support_08_172]
[s][vp 8 1 65535 172 0 0]Mona's dizzy! His accuracy is down![n][f 1 6 65534][e]

[msg btl_support_08_173]
[s][vp 8 1 65535 173 0 0]Panther's accuracy is down...[n]She's too dizzy! Watch out![n][f 1 6 65534][e]

[msg btl_support_08_174]
[s][vp 8 1 65535 174 0 0]Fox is dizzy! His attacks are going[n]to miss a lot more![n][f 1 6 65534][e]

[msg btl_support_08_175]
[s][vp 8 1 65535 175 0 0]Queen's dizzy! Her attacks won't[n]connect![n][f 1 6 65534][e]

[msg btl_support_08_176]
[s][vp 8 1 65535 176 0 0]Noir! Your accuracy's down from[n]your dizzy spell![n][f 1 6 65534][e]

[msg btl_support_08_177]
[s][vp 8 1 65535 177 0 0]Crow's completely dizzy![n]His accuracy is low![n][f 1 6 65534][e]

[msg btl_support_08_178]
[s][vp 8 1 65535 178 0 0]You're dizzy! Your attacks might[n]not connect![n][f 1 6 65534][e]

[msg btl_support_08_179]
[s][vp 8 1 65535 179 0 0]Joker's confused! He's going rogue![n][f 1 6 65534][e]

[msg btl_support_08_180]
[s][vp 8 1 65535 180 0 0]Skull's confused!? Hey, don't[n]flail around like that![n][f 1 6 65534][e]

[msg btl_support_08_181]
[s][vp 8 1 65535 181 0 0]Mona's confused! Hey, stop doing[n]your own thing![n][f 1 6 65534][e]

[msg btl_support_08_182]
[s][vp 8 1 65535 182 0 0]Panther's confused right now![n]C-Calm down![n][f 1 6 65534][e]

[msg btl_support_08_183]
[s][vp 8 1 65535 183 0 0]Fox is confused! He's not listening[n]to you![n][f 1 6 65534][e]

[msg btl_support_08_184]
[s][vp 8 1 65535 184 0 0]Queen, you're confused![n]Don't do anything drastic![n][f 1 6 65534][e]

[msg btl_support_08_185]
[s][vp 8 1 65535 185 0 0]Noir's confused! Just calm down[n]and we can talk this out![n][f 1 6 65534][e]

[msg btl_support_08_186]
[s][vp 8 1 65535 186 0 0]Crow's confused! You have to[n]think before you act![n][f 1 6 65534][e]

[msg btl_support_08_187]
[s][vp 8 1 65535 187 0 0]Calm down! You're confused![n][f 1 6 65534][e]

[msg btl_support_08_188]
[s][vp 8 1 65535 188 0 0]Joker's afraid![n][f 1 6 65534][e]

[msg btl_support_08_189]
[s][vp 8 1 65535 189 0 0]Skull's all shaken up! He might just[n]run for it![n][f 1 6 65534][e]

[msg btl_support_08_190]
[s][vp 8 1 65535 190 0 0]Mona's scared! He might make[n]a break for it![n][f 1 6 65534][e]

[msg btl_support_08_191]
[s][vp 8 1 65535 191 0 0]Panther's really scared![n]Please, don't run![n][f 1 6 65534][e]

[msg btl_support_08_192]
[s][vp 8 1 65535 192 0 0]Fox is terrified! He might run[n]any second![n][f 1 6 65534][e]

[msg btl_support_08_193]
[s][vp 8 1 65535 193 0 0]Queen's trembling! Just... don't run![n][f 1 6 65534][e]

[msg btl_support_08_194]
[s][vp 8 1 65535 194 0 0]Noir's scared! Don't run away now![n][f 1 6 65534][e]

[msg btl_support_08_195]
[s][vp 8 1 65535 195 0 0]Crow's shaking! Come on,[n]don't run away![n][f 1 6 65534][e]

[msg btl_support_08_196]
[s][vp 8 1 65535 196 0 0]Hey, don't run away! You don't[n]have to be scared![n][f 1 6 65534][e]

[msg btl_support_08_197]
[s][vp 8 1 65535 197 0 0]Joker's forgotten everything![n]He can't summon his Persona![n][f 1 6 65534][e]

[msg btl_support_08_198]
[s][vp 8 1 65535 198 0 0]Skull's memory is gone! He can't[n]call his Persona![n][f 1 6 65534][e]

[msg btl_support_08_199]
[s][vp 8 1 65535 199 0 0]Mona's lost his memory! He can't[n]summon his Persona![n][f 1 6 65534][e]

[msg btl_support_08_200]
[s][vp 8 1 65535 200 0 0]Panther can't remember anything![n]Her Persona's unusable![n][f 1 6 65534][e]

[msg btl_support_08_201]
[s][vp 8 1 65535 201 0 0]Fox's forgotten how to call[n]his Persona![n][f 1 6 65534][e]

[msg btl_support_08_202]
[s][vp 8 1 65535 202 0 0]Queen's lost her memory![n]Her Persona's been sealed![n][f 1 6 65534][e]

[msg btl_support_08_203]
[s][vp 8 1 65535 203 0 0]Noir's forgetting everything! Be[n]careful; she can't use her Persona![n][f 1 6 65534][e]

[msg btl_support_08_204]
[s][vp 8 1 65535 204 0 0]Crow's memory is gone![n]He can't summon his Persona![n][f 1 6 65534][e]

[msg btl_support_08_205]
[s][vp 8 1 65535 205 0 0]You lost your memory!? Don't you[n]remember your Persona?[n][f 1 6 65534][e]

[msg btl_support_08_206]
[s][vp 8 1 65535 206 0 0]Joker's hungry! He's powered[n]down![n][f 1 6 65534][e]

[msg btl_support_08_207]
[s][vp 8 1 65535 207 0 0]Skull's really hungry! He doesn't[n]have the energy to hit hard![n][f 1 6 65534][e]

[msg btl_support_08_208]
[s][vp 8 1 65535 208 0 0]Mona's really hungry! His attack[n]is a lot lower![n][f 1 6 65534][e]

[msg btl_support_08_209]
[s][vp 8 1 65535 209 0 0]Panther's starving! She can't use[n]her full strength![n][f 1 6 65534][e]

[msg btl_support_08_210]
[s][vp 8 1 65535 210 0 0]Fox has hit a wall! His offense is[n]way down![n][f 1 6 65534][e]

[msg btl_support_08_211]
[s][vp 8 1 65535 211 0 0]Queen needs food! Her offense is[n]really low![n][f 1 6 65534][e]

[msg btl_support_08_212]
[s][vp 8 1 65535 212 0 0]Noir's weaker than before...[n]It's 'cause she's hungry![n][f 1 6 65534][e]

[msg btl_support_08_213]
[s][vp 8 1 65535 213 0 0]Crow's really hungry! He's not at[n]full strength anymore![n][f 1 6 65534][e]

[msg btl_support_08_214]
[s][vp 8 1 65535 214 0 0]You're too hungry to fight![n]Your power's down![n][f 1 6 65534][e]

[msg btl_support_08_215]
[s][vp 8 1 65535 215 0 0]Joker's fast asleep! He can't defend[n]himself![n][f 1 6 65534][e]

[msg btl_support_08_216]
[s][vp 8 1 65535 216 0 0]Skull's sleeping! He's in danger![n][f 1 6 65534][e]

[msg btl_support_08_217]
[s][vp 8 1 65535 217 0 0]Is Mona sleeping!? Hey, you have to[n]wake up![n][f 1 6 65534][e]

[msg btl_support_08_218]
[s][vp 8 1 65535 218 0 0]Panther's asleep! If she takes a hit[n]now, it'll hurt![n][f 1 6 65534][e]

[msg btl_support_08_219]
[s][vp 8 1 65535 219 0 0]Fox has fallen asleep! Wake up;[n]you're defenseless![n][f 1 6 65534][e]

[msg btl_support_08_220]
[s][vp 8 1 65535 220 0 0]Queen's fallen asleep![n]She's defenseless! [n][f 1 6 65534][e]

[msg btl_support_08_221]
[s][vp 8 1 65535 221 0 0]Noir's asleep! If she takes[n]a hit now...[n][f 1 6 65534][e]

[msg btl_support_08_222]
[s][vp 8 1 65535 222 0 0]Crow's sleeping! He's in danger![n][f 1 6 65534][e]

[msg btl_support_08_223]
[s][vp 8 1 65535 223 0 0]Hey, no sleeping on the job![n]Wake up already![n][f 1 6 65534][e]

[msg btl_support_08_224]
[s][vp 8 1 65535 224 0 0]Joker's angry!? He's taking[n]unnecessary risks![n][f 1 6 65534][e]

[msg btl_support_08_225]
[s][vp 8 1 65535 225 0 0]Skull's really mad... Hey, listen[n]to me![n][f 1 6 65534][e]

[msg btl_support_08_226]
[s][vp 8 1 65535 226 0 0]Mona's completely lost it![n]You gotta calm down![n][f 1 6 65534][e]

[msg btl_support_08_227]
[s][vp 8 1 65535 227 0 0]Panther's upset!? She won't listen[n]to me![n][f 1 6 65534][e]

[msg btl_support_08_228]
[s][vp 8 1 65535 228 0 0]Fox is angry... Calm down! Listen! [n][f 1 6 65534][e]

[msg btl_support_08_229]
[s][vp 8 1 65535 229 0 0]Queen's mad... and really scary![n]Please, calm down![n][f 1 6 65534][e]

[msg btl_support_08_230]
[s][vp 8 1 65535 230 0 0]Noir looks really angry! She's not[n]listening to anyone![n][f 1 6 65534][e]

[msg btl_support_08_231]
[s][vp 8 1 65535 231 0 0]Crow's ticked off!? Hey, listen[n]to me![n][f 1 6 65534][e]

[msg btl_support_08_232]
[s][vp 8 1 65535 232 0 0]Don't lose your cool! Just calm[n]down![n][f 1 6 65534][e]

[msg btl_support_08_233]
[s][vp 8 1 65535 233 0 0]Joker's losing hope, we have to[n]be there for him![n][f 1 6 65534][e]

[msg btl_support_08_234]
[s][vp 8 1 65535 234 0 0]Skull's in despair! Leaving him[n]like that is asking for trouble![n][f 1 6 65534][e]

[msg btl_support_08_235]
[s][vp 8 1 65535 235 0 0]Mona's losing heart! Any damage[n]will affect his body AND mind![n][f 1 6 65534][e]

[msg btl_support_08_236]
[s][vp 8 1 65535 236 0 0]Panther's depressed! She needs to[n]get back in the fight![n][f 1 6 65534][e]

[msg btl_support_08_237]
[s][vp 8 1 65535 237 0 0]Fox's despairing! He'll be in danger[n]like that![n][f 1 6 65534][e]

[msg btl_support_08_238]
[s][vp 8 1 65535 238 0 0]Queen's in anguish! W-We have to[n]do something...[n][f 1 6 65534][e]

[msg btl_support_08_239]
[s][vp 8 1 65535 239 0 0]The despair's getting to Noir![n]We need to save her![n][f 1 6 65534][e]

[msg btl_support_08_240]
[s][vp 8 1 65535 240 0 0]Crow's desperate! It's dangerous[n]leaving him like that![n][f 1 6 65534][e]

[msg btl_support_08_241]
[s][vp 8 1 65535 241 0 0]You need to deal with the despair![n]It's bad to just ignore it![n][f 1 6 65534][e]

[msg btl_support_08_242]
[s][vp 8 1 65535 242 0 0]Joker's been brainwashed![n]He can't tell friend from foe![n][f 1 6 65534][e]

[msg btl_support_08_243]
[s][vp 8 1 65535 243 0 0]Skull's brainwashed! He thinks[n]we're the enemies![n][f 1 6 65534][e]

[msg btl_support_08_244]
[s][vp 8 1 65535 244 0 0]Mona's been brainwashed![n]We're the good guys![n][f 1 6 65534][e]

[msg btl_support_08_245]
[s][vp 8 1 65535 245 0 0]Panther's brainwashed!?[n]She doesn't know who's who![n][f 1 6 65534][e]

[msg btl_support_08_246]
[s][vp 8 1 65535 246 0 0]Fox's brainwashed! The bad guys[n]are over there![n][f 1 6 65534][e]

[msg btl_support_08_247]
[s][vp 8 1 65535 247 0 0]Queen's been brainwashed![n]Come on, we're on your side![n][f 1 6 65534][e]

[msg btl_support_08_248]
[s][vp 8 1 65535 248 0 0]Noir's brainwashed! She can't tell[n]who's her team![n][f 1 6 65534][e]

[msg btl_support_08_249]
[s][vp 8 1 65535 249 0 0]Crow's brainwashed! He's mixed up[n]who's who![n][f 1 6 65534][e]

[msg btl_support_08_250]
[s][vp 8 1 65535 250 0 0]You're brainwashed!? W-We're[n]not your enemies![n][f 1 6 65534][e]

[msg btl_support_08_251]
[s][vp 8 1 65535 251 0 0]Joker's a mouse! He's cuter, but[n]he can't do anything![n][f 1 6 65534][e]

[msg btl_support_08_252]
[s][vp 8 1 65535 252 0 0]Skull's a mouse! Just keep running![n][f 1 6 65534][e]

[msg btl_support_08_253]
[s][vp 8 1 65535 253 0 0]Whoa! You're a cat AND a mouse!?[n]Crazy![n][f 1 6 65534][e]

[msg btl_support_08_254]
[s][vp 8 1 65535 254 0 0]Panther's a mouse! You're[n]helpless... Just run![n][f 1 6 65534][e]

[msg btl_support_08_255]
[s][vp 8 1 65535 255 0 0]Fox got turned into a mouse![n]Just run![n][f 1 6 65534][e]

[msg btl_support_08_256]
[s][vp 8 1 65535 256 0 0]Queen's become a mouse![n]The only thing you can do is run![n][f 1 6 65534][e]

[msg btl_support_08_257]
[s][vp 8 1 65535 257 0 0]Noir's a mouse! She can't do[n]anything! Run![n][f 1 6 65534][e]

[msg btl_support_08_258]
[s][vp 8 1 65535 258 0 0]Crow's been mousified! All he can[n]do is run![n][f 1 6 65534][e]

[msg btl_support_08_259]
[s][vp 8 1 65535 259 0 0]You can't do anything as a mouse![n]Just run away![n][f 1 6 65534][e]

[msg btl_support_08_260]
[s][vp 8 1 65535 260 0 0]Okay, time for a comeback![n][f 1 6 65534][e]

[msg btl_support_08_261]
[s][vp 8 1 65535 261 0 0]Skull's back in action![n]Payback time![n][f 1 6 65534][e]

[msg btl_support_08_262]
[s][vp 8 1 65535 262 0 0]Mona's back up![n][f 1 6 65534][e]

[msg btl_support_08_263]
[s][vp 8 1 65535 263 0 0]Panther got back up! Start the[n]counterattack![n][f 1 6 65534][e]

[msg btl_support_08_264]
[s][vp 8 1 65535 264 0 0]Fox! It's time for revenge![n][f 1 6 65534][e]

[msg btl_support_08_265]
[s][vp 8 1 65535 265 0 0]Queen's back! Make 'em pay![n][f 1 6 65534][e]

[msg btl_support_08_266]
[s][vp 8 1 65535 266 0 0]Time to make up for that little slip![n][f 1 6 65534][e]

[msg btl_support_08_267]
[s][vp 8 1 65535 267 0 0]Crow's up again! It's payback time![n][f 1 6 65534][e]

[msg btl_support_08_268]
[s][vp 8 1 65535 268 0 0]Aw yeah! Now it's payback time![n][f 1 6 65534][e]

[msg btl_support_08_269]
[s][vp 8 1 65535 269 0 0]We've got the advantage![n]Let's win this![n][f 1 6 65534][e]

[msg btl_support_08_270]
[s][vp 8 1 65535 270 0 0]We can beat them in an instant![n][f 1 6 65534][e]

[msg btl_support_08_271]
[s][vp 8 1 65535 271 0 0]This doesn't look good! Be careful![n][f 1 6 65534][e]

[msg btl_support_08_272]
[s][vp 8 1 65535 272 0 0]They've still got the advantage...[n]Just hold out![n][f 1 6 65534][e]

[msg btl_support_08_273]
[s][vp 8 1 65535 273 0 0]A Baton Pass'll help you hit[n]the enemy's weakness![n][f 1 6 65534][e]

[msg btl_support_08_274]
[s][vp 8 1 65535 274 0 0]You'll be able to knock the enemy[n]down if you pass the baton![n][f 1 6 65534][e]

[msg btl_support_08_275]
[s][vp 8 1 65535 275 0 0]It's Baton Pass time![n][f 1 6 65534][e]

[msg btl_support_08_276]
[s][vp 8 1 65535 276 0 0]Now's your chance! Pass the baton![n][f 1 6 65534][e]

[msg btl_support_08_277]
[s][vp 8 1 65535 277 0 0]Pass that baton! Go for[n]a knockdown![n][f 1 6 65534][e]

[msg btl_support_08_278]
[s][vp 8 1 65535 278 0 0]Ooh, awesome![n][f 1 6 65534][e]

[msg btl_support_08_279]
[s][vp 8 1 65535 279 0 0]Nice![n][f 1 6 65534][e]

[msg btl_support_08_280]
[s][vp 8 1 65535 280 0 0]Huh! Not too shabby![n][f 1 6 65534][e]

[msg btl_support_08_281]
[s][vp 8 1 65535 281 0 0]Whoa... You did that with style![n][f 1 6 65534][e]

[msg btl_support_08_282]
[s][vp 8 1 65535 282 0 0]Ooh, nice attack![n][f 1 6 65534][e]

[msg btl_support_08_283]
[s][vp 8 1 65535 283 0 0]My Futaba sense is tingling![n]Let me handle this![n][f 1 6 65534][e]

[msg btl_support_08_284]
[s][vp 8 1 65535 284 0 0]They got you, huh? Guess it's[n]my turn to shine![n][f 1 6 65534][e]

[msg btl_support_08_285]
[s][vp 8 1 65535 285 0 0]Leave this to me![n][f 1 6 65534][e]

[msg btl_support_08_286]
[s][vp 8 1 65535 286 0 0]I can handle this! You guys regroup![n][f 1 6 65534][e]

[msg btl_support_08_287]
[s][vp 8 1 65535 287 0 0]All right! Persona![n][f 1 6 65534][e]

[msg btl_support_08_288]
[s][vp 8 1 65535 288 0 0]Activating emergency shift![n][f 1 6 65534][e]

[msg btl_support_08_289]
[s][vp 8 1 65535 289 0 0]Member swap complete![n][f 1 6 65534][e]

[msg btl_support_08_290]
[s][vp 8 1 65535 290 0 0]Good luck![n][f 1 6 65534][e]

[msg btl_support_08_291]
[s][vp 8 1 65535 291 0 0]And done! [n][f 1 6 65534][e]

[msg btl_support_08_292]
[s][vp 8 1 65535 292 0 0]Enemies defeated! All right, Joker![n][f 1 6 65534][e]

[msg btl_support_08_293]
[s][vp 8 1 65535 293 0 0]Shadows annihilated![n]Skull's got this![n][f 1 6 65534][e]

[msg btl_support_08_294]
[s][vp 8 1 65535 294 0 0]Nice job, Mona![n][f 1 6 65534][e]

[msg btl_support_08_295]
[s][vp 8 1 65535 295 0 0]Yeah, Panther! You got them all![n][f 1 6 65534][e]

[msg btl_support_08_296]
[s][vp 8 1 65535 296 0 0]Enemies: annihilated! You're[n]pretty good, Fox![n][f 1 6 65534][e]

[msg btl_support_08_297]
[s][vp 8 1 65535 297 0 0]Wiped out! Good work, Queen![n][f 1 6 65534][e]

[msg btl_support_08_298]
[s][vp 8 1 65535 298 0 0]That's all of them! You did great,[n]Noir![n][f 1 6 65534][e]

[msg btl_support_08_299]
[s][vp 8 1 65535 299 0 0]You obliterated them! Nice job,[n]Crow![n][f 1 6 65534][e]

[msg btl_support_08_300]
[s][vp 8 1 65535 300 0 0]No more enemy signals.[n]Good job, guys![n][f 1 6 65534][e]

[msg btl_support_08_301]
[s][vp 8 1 65535 301 0 0]Amazing, Joker! That's four[n]Shadows gone![n][f 1 6 65534][e]

[msg btl_support_08_302]
[s][vp 8 1 65535 302 0 0]Nice one, Skull! That's four less[n]to deal with![n][f 1 6 65534][e]

[msg btl_support_08_303]
[s][vp 8 1 65535 303 0 0]Nice one, Mona! You got four[n]of 'em![n][f 1 6 65534][e]

[msg btl_support_08_304]
[s][vp 8 1 65535 304 0 0]Panther beat four enemies with[n]just one skill![n][f 1 6 65534][e]

[msg btl_support_08_305]
[s][vp 8 1 65535 305 0 0]That was great, Fox! Four enemies[n]off the list![n][f 1 6 65534][e]

[msg btl_support_08_306]
[s][vp 8 1 65535 306 0 0]Queen, you're so awesome![n]Four enemies taken care of![n][f 1 6 65534][e]

[msg btl_support_08_307]
[s][vp 8 1 65535 307 0 0]Noir defeated four Shadows![n][f 1 6 65534][e]

[msg btl_support_08_308]
[s][vp 8 1 65535 308 0 0]Crow, that was incredible![n]Four enemies down![n][f 1 6 65534][e]

[msg btl_support_08_309]
[s][vp 8 1 65535 309 0 0]You took down four with one move![n]Impressive![n][f 1 6 65534][e]

[msg btl_support_08_310]
[s][vp 8 1 65535 310 0 0]Three enemies wiped out![n]That was great, Joker![n][f 1 6 65534][e]

[msg btl_support_08_311]
[s][vp 8 1 65535 311 0 0]Three more down! Keep[n]hitting them, Skull![n][f 1 6 65534][e]

[msg btl_support_08_312]
[s][vp 8 1 65535 312 0 0]Three Shadows defeated![n]Looking good, Mona![n][f 1 6 65534][e]

[msg btl_support_08_313]
[s][vp 8 1 65535 313 0 0]That's three less to worry about![n]You're on a roll, Panther![n][f 1 6 65534][e]

[msg btl_support_08_314]
[s][vp 8 1 65535 314 0 0]Three foes defeated! Nice one, Fox![n][f 1 6 65534][e]

[msg btl_support_08_315]
[s][vp 8 1 65535 315 0 0]Queen got three of them! So cool![n][f 1 6 65534][e]

[msg btl_support_08_316]
[s][vp 8 1 65535 316 0 0]That's three outta the fight![n]Keep it coming, Noir![n][f 1 6 65534][e]

[msg btl_support_08_317]
[s][vp 8 1 65535 317 0 0]Three more down! Nice going,[n]Crow![n][f 1 6 65534][e]

[msg btl_support_08_318]
[s][vp 8 1 65535 318 0 0]Okay, that's three less! Awesome![n][f 1 6 65534][e]

[msg btl_support_08_319]
[s][vp 8 1 65535 319 0 0]Lookin' good! Joker beat two[n]enemies![n][f 1 6 65534][e]

[msg btl_support_08_320]
[s][vp 8 1 65535 320 0 0]You got 'em, Skull! That's two down![n][f 1 6 65534][e]

[msg btl_support_08_321]
[s][vp 8 1 65535 321 0 0]Two foes gone for good![n]Keep the pressure up, Mona![n][f 1 6 65534][e]

[msg btl_support_08_322]
[s][vp 8 1 65535 322 0 0]Woo, Panther! Two enemies[n]defeated![n][f 1 6 65534][e]

[msg btl_support_08_323]
[s][vp 8 1 65535 323 0 0]Fox took out two of them![n]Go get 'em![n][f 1 6 65534][e]

[msg btl_support_08_324]
[s][vp 8 1 65535 324 0 0]Wow! You got two of them, Queen![n][f 1 6 65534][e]

[msg btl_support_08_325]
[s][vp 8 1 65535 325 0 0]Noir, keep that up! Two enemies[n]down![n][f 1 6 65534][e]

[msg btl_support_08_326]
[s][vp 8 1 65535 326 0 0]Great job, Crow! Two enemies[n]out of the way![n][f 1 6 65534][e]

[msg btl_support_08_327]
[s][vp 8 1 65535 327 0 0]Two enemies gone! Looking good![n][f 1 6 65534][e]

[msg btl_support_08_328]
[s][vp 8 1 65535 328 0 0]Nice! Joker took one out![n][f 1 6 65534][e]

[msg btl_support_08_329]
[s][vp 8 1 65535 329 0 0]One enemy gone! Do it again, Skull![n][f 1 6 65534][e]

[msg btl_support_08_330]
[s][vp 8 1 65535 330 0 0]Mona took out a Shadow![n]Good stuff![n][f 1 6 65534][e]

[msg btl_support_08_331]
[s][vp 8 1 65535 331 0 0]One enemy shot down![n]Panther's rockin' it![n][f 1 6 65534][e]

[msg btl_support_08_332]
[s][vp 8 1 65535 332 0 0]One enemy crushed! Keep that[n]up, Fox![n][f 1 6 65534][e]

[msg btl_support_08_333]
[s][vp 8 1 65535 333 0 0]One enemy defeated! Go get 'em,[n]Queen![n][f 1 6 65534][e]

[msg btl_support_08_334]
[s][vp 8 1 65535 334 0 0]Noir crushed it! Keep that up![n][f 1 6 65534][e]

[msg btl_support_08_335]
[s][vp 8 1 65535 335 0 0]One enemy taken out! Good one,[n]Crow![n][f 1 6 65534][e]

[msg btl_support_08_336]
[s][vp 8 1 65535 336 0 0]Okay, scratch one enemy![n][f 1 6 65534][e]

[msg btl_support_08_337]
[s][vp 8 1 65535 337 0 0]Ooh! Joker, you're looking cool![n][f 1 6 65534][e]

[msg btl_support_08_338]
[s][vp 8 1 65535 338 0 0]Skull, you sure showed me![n][f 1 6 65534][e]

[msg btl_support_08_339]
[s][vp 8 1 65535 339 0 0]Not bad, Mona![n][f 1 6 65534][e]

[msg btl_support_08_340]
[s][vp 8 1 65535 340 0 0]Amazing, Panther![n][f 1 6 65534][e]

[msg btl_support_08_341]
[s][vp 8 1 65535 341 0 0]You did it, Fox![n][f 1 6 65534][e]

[msg btl_support_08_342]
[s][vp 8 1 65535 342 0 0]That's our Queen![n][f 1 6 65534][e]

[msg btl_support_08_343]
[s][vp 8 1 65535 343 0 0]Oooh! Not bad, Noir![n][f 1 6 65534][e]

[msg btl_support_08_344]
[s][vp 8 1 65535 344 0 0]Crow! Looking good![n][f 1 6 65534][e]

[msg btl_support_08_345]
[s][vp 8 1 65535 345 0 0]Now! Surround 'em![n][f 1 6 65534][e]

[msg btl_support_08_346]
[s][vp 8 1 65535 346 0 0]Four enemies knocked down![n]Joker's awesome![n][f 1 6 65534][e]

[msg btl_support_08_347]
[s][vp 8 1 65535 347 0 0]Four enemies knocked down![n]Skull's got the right idea![n][f 1 6 65534][e]

[msg btl_support_08_348]
[s][vp 8 1 65535 348 0 0]Four enemies on the floor![n]Lookin' good, Mona![n][f 1 6 65534][e]

[msg btl_support_08_349]
[s][vp 8 1 65535 349 0 0]Four enemies knocked flat![n]Awww yesss, Panther![n][f 1 6 65534][e]

[msg btl_support_08_350]
[s][vp 8 1 65535 350 0 0]Whoaaa, Fox knocked down[n]four enemies at once![n][f 1 6 65534][e]

[msg btl_support_08_351]
[s][vp 8 1 65535 351 0 0]Queen, that was insane! That's[n]four enemies fallen flat![n][f 1 6 65534][e]

[msg btl_support_08_352]
[s][vp 8 1 65535 352 0 0]Four enemies hit the floor! Noir,[n]you're doing great![n][f 1 6 65534][e]

[msg btl_support_08_353]
[s][vp 8 1 65535 353 0 0]Four enemies knocked down![n]Excellent work, Crow![n][f 1 6 65534][e]

[msg btl_support_08_354]
[s][vp 8 1 65535 354 0 0]Four enemies knocked down![n]Pretty good.[n][f 1 6 65534][e]

[msg btl_support_08_355]
[s][vp 8 1 65535 355 0 0]Three enemies on the floor![n]Nice, Joker![n][f 1 6 65534][e]

[msg btl_support_08_356]
[s][vp 8 1 65535 356 0 0]Three enemies grounded![n]Keep it up, Skull![n][f 1 6 65534][e]

[msg btl_support_08_357]
[s][vp 8 1 65535 357 0 0]Three foes floored! Awesome,[n]Mona![n][f 1 6 65534][e]

[msg btl_support_08_358]
[s][vp 8 1 65535 358 0 0]Three Shadows knocked down![n]But Panther's not done yet, right?[n][f 1 6 65534][e]

[msg btl_support_08_359]
[s][vp 8 1 65535 359 0 0]Three enemies got knocked down![n]Nice one, Fox![n][f 1 6 65534][e]

[msg btl_support_08_360]
[s][vp 8 1 65535 360 0 0]Queen knocked down three[n]Shadows! Let 'em have it![n][f 1 6 65534][e]

[msg btl_support_08_361]
[s][vp 8 1 65535 361 0 0]That's three enemies knocked down![n]Way to go, Noir![n][f 1 6 65534][e]

[msg btl_support_08_362]
[s][vp 8 1 65535 362 0 0]Three enemies knocked down![n]That's Crow for you![n][f 1 6 65534][e]

[msg btl_support_08_363]
[s][vp 8 1 65535 363 0 0]Three enemies downed![n]You're looking good![n][f 1 6 65534][e]

[msg btl_support_08_364]
[s][vp 8 1 65535 364 0 0]Two enemies floored! Not bad,[n]Joker![n][f 1 6 65534][e]

[msg btl_support_08_365]
[s][vp 8 1 65535 365 0 0]Two Shadows downed! Skull,[n]that was on the money![n][f 1 6 65534][e]

[msg btl_support_08_366]
[s][vp 8 1 65535 366 0 0]Mona, good job! Two enemies[n]toppled![n][f 1 6 65534][e]

[msg btl_support_08_367]
[s][vp 8 1 65535 367 0 0]That's two enemies knocked[n]down! Panther, niiiiice![n][f 1 6 65534][e]

[msg btl_support_08_368]
[s][vp 8 1 65535 368 0 0]Two enemies on the ground![n]Smooth one, Fox![n][f 1 6 65534][e]

[msg btl_support_08_369]
[s][vp 8 1 65535 369 0 0]Queen floored two opponents![n]She's amazing![n][f 1 6 65534][e]

[msg btl_support_08_370]
[s][vp 8 1 65535 370 0 0]Two Shadows knocked down![n]Go for broke, Noir![n][f 1 6 65534][e]

[msg btl_support_08_371]
[s][vp 8 1 65535 371 0 0]Two enemies downed![n]Crow, keep it up![n][f 1 6 65534][e]

[msg btl_support_08_372]
[s][vp 8 1 65535 372 0 0]Two enemies floored![n]That's the ticket![n][f 1 6 65534][e]

[msg btl_support_08_373]
[s][vp 8 1 65535 373 0 0]Knocked 'em right off their feet![n]Nice, Joker![n][f 1 6 65534][e]

[msg btl_support_08_374]
[s][vp 8 1 65535 374 0 0]That's one knocked down![n]Let 'em have it, Skull![n][f 1 6 65534][e]

[msg btl_support_08_375]
[s][vp 8 1 65535 375 0 0]One enemy on the floor![n]Bona fide Monafied![n][f 1 6 65534][e]

[msg btl_support_08_376]
[s][vp 8 1 65535 376 0 0]Panther knocked one down![n]Looking good![n][f 1 6 65534][e]

[msg btl_support_08_377]
[s][vp 8 1 65535 377 0 0]You got 'em, Fox! One enemy[n]hit the ground![n][f 1 6 65534][e]

[msg btl_support_08_378]
[s][vp 8 1 65535 378 0 0]That's one downed! Go Queen, go![n][f 1 6 65534][e]

[msg btl_support_08_379]
[s][vp 8 1 65535 379 0 0]Floored 'em! Keep it coming, Noir![n][f 1 6 65534][e]

[msg btl_support_08_380]
[s][vp 8 1 65535 380 0 0]And there it goes! Good one, Crow![n][f 1 6 65534][e]

[msg btl_support_08_381]
[s][vp 8 1 65535 381 0 0]Okay! You knocked one down![n][f 1 6 65534][e]

[msg btl_support_08_382]
[s][vp 8 1 65535 382 0 0]Nice one, Joker! You hit its[n]weakness![n][f 1 6 65534][e]

[msg btl_support_08_383]
[s][vp 8 1 65535 383 0 0]Right in the weak spot! Looking[n]good, Skull![n][f 1 6 65534][e]

[msg btl_support_08_384]
[s][vp 8 1 65535 384 0 0]That was their weak point! Keep up[n]the pressure, Mona![n][f 1 6 65534][e]

[msg btl_support_08_385]
[s][vp 8 1 65535 385 0 0]You got through their defenses![n]Keep going, Panther![n][f 1 6 65534][e]

[msg btl_support_08_386]
[s][vp 8 1 65535 386 0 0]Got their weakness! You're on a roll,[n]Fox![n][f 1 6 65534][e]

[msg btl_support_08_387]
[s][vp 8 1 65535 387 0 0]Nice one, Queen! You hit their[n]weak point![n][f 1 6 65534][e]

[msg btl_support_08_388]
[s][vp 8 1 65535 388 0 0]You got 'em, Noir! Right in the[n]weak spot![n][f 1 6 65534][e]

[msg btl_support_08_389]
[s][vp 8 1 65535 389 0 0]Direct hit to their weakness![n]Nice work, Crow![n][f 1 6 65534][e]

[msg btl_support_08_390]
[s][vp 8 1 65535 390 0 0]You got their weak spot![n][f 1 6 65534][e]

[msg btl_support_08_391]
[s][vp 8 1 65535 391 0 0]Sha-boom! Joker, that was[n]AWESOME![n][f 1 6 65534][e]

[msg btl_support_08_392]
[s][vp 8 1 65535 392 0 0]Nice hit! Skull's at the top of[n]his game![n][f 1 6 65534][e]

[msg btl_support_08_393]
[s][vp 8 1 65535 393 0 0]Clean and stylish, Mona![n][f 1 6 65534][e]

[msg btl_support_08_394]
[s][vp 8 1 65535 394 0 0]There we go! Ten out of ten,[n]Panther![n][f 1 6 65534][e]

[msg btl_support_08_395]
[s][vp 8 1 65535 395 0 0]Fox, that was an awesome hit![n][f 1 6 65534][e]

[msg btl_support_08_396]
[s][vp 8 1 65535 396 0 0]A smash hit! Queen, you're so cool![n][f 1 6 65534][e]

[msg btl_support_08_397]
[s][vp 8 1 65535 397 0 0]Now that's a hit! Keep that up, Noir![n][f 1 6 65534][e]

[msg btl_support_08_398]
[s][vp 8 1 65535 398 0 0]A critical hit! Nice one, Crow![n][f 1 6 65534][e]

[msg btl_support_08_399]
[s][vp 8 1 65535 399 0 0]Nice crit![n][f 1 6 65534][e]

[msg btl_support_08_400]
[s][vp 8 1 65535 400 0 0]Joker, you missed!?[n][f 1 6 65534][e]

[msg btl_support_08_401]
[s][vp 8 1 65535 401 0 0]Skull, what're you doing!?[n][f 1 6 65534][e]

[msg btl_support_08_402]
[s][vp 8 1 65535 402 0 0]Mona! AIM![n][f 1 6 65534][e]

[msg btl_support_08_403]
[s][vp 8 1 65535 403 0 0]Eyes up, Panther![n][f 1 6 65534][e]

[msg btl_support_08_404]
[s][vp 8 1 65535 404 0 0]Fox! You gotta aim![n][f 1 6 65534][e]

[msg btl_support_08_405]
[s][vp 8 1 65535 405 0 0]C'mon, Queen![n][f 1 6 65534][e]

[msg btl_support_08_406]
[s][vp 8 1 65535 406 0 0]Noir! You gotta hit them![n][f 1 6 65534][e]

[msg btl_support_08_407]
[s][vp 8 1 65535 407 0 0]Crow, you gotta watch them![n][f 1 6 65534][e]

[msg btl_support_08_408]
[s][vp 8 1 65535 408 0 0]Ah! Your attack missed![n][f 1 6 65534][e]

[msg btl_support_08_409]
[s][vp 8 1 65535 409 0 0]Skull, where're you going!?[n][f 1 6 65534][e]

[msg btl_support_08_410]
[s][vp 8 1 65535 410 0 0]Mona ran away! Hey![n][f 1 6 65534][e]

[msg btl_support_08_411]
[s][vp 8 1 65535 411 0 0]Panther! Where are you going!?[n][f 1 6 65534][e]

[msg btl_support_08_412]
[s][vp 8 1 65535 412 0 0]Hey, Fox! Don't run![n][f 1 6 65534][e]

[msg btl_support_08_413]
[s][vp 8 1 65535 413 0 0]Queen, don't run off![n][f 1 6 65534][e]

[msg btl_support_08_414]
[s][vp 8 1 65535 414 0 0]Wait, Noir! You're not supposed[n]to run![n][f 1 6 65534][e]

[msg btl_support_08_415]
[s][vp 8 1 65535 415 0 0]Crow!? Where are you going!?[n][f 1 6 65534][e]

[msg btl_support_08_416]
[s][vp 8 1 65535 416 0 0]Huh? Hey! Don't run![n][f 1 6 65534][e]

[msg btl_support_08_417]
[s][vp 8 1 65535 417 0 0]Huh!? No, don't! Awww...[n][f 1 6 65534][e]

[msg btl_support_08_418]
[s][vp 8 1 65535 418 0 0]Wait, what about the treasure!?[n][f 1 6 65534][e]

[msg btl_support_08_419]
[s][vp 8 1 65535 419 0 0]Hey! What are you doing?[n][f 1 6 65534][e]

[msg btl_support_08_420]
[s][vp 8 1 65535 420 0 0]Got the info![n][f 1 6 65534][e]

[msg btl_support_08_421]
[s][vp 8 1 65535 421 0 0]Shadow analysis... done![n][f 1 6 65534][e]

[msg btl_support_08_422]
[s][vp 8 1 65535 422 0 0]Sending data now![n][f 1 6 65534][e]

[msg btl_support_08_423]
[s][vp 8 1 65535 423 0 0]All right, get 'em![n][f 1 6 65534][e]

[msg btl_support_08_424]
[s][vp 8 1 65535 424 0 0]Beat 'em all at once![n][f 1 6 65534][e]

[msg btl_support_08_425]
[s][vp 8 1 65535 425 0 0]Time for a beatdown![n][f 1 6 65534][e]

[msg btl_support_08_426]
[s][vp 8 1 65535 426 0 0]Go! Power up![n][f 1 6 65534][e]

[msg btl_support_08_427]
[s][vp 8 1 65535 427 0 0]This one! Defense up![n][f 1 6 65534][e]

[msg btl_support_08_428]
[s][vp 8 1 65535 428 0 0]Here I go! Speeeed up![n][f 1 6 65534][e]

[msg btl_support_08_429]
[s][vp 8 1 65535 429 0 0]Here come the buffs![n][f 1 6 65534][e]

[msg btl_support_08_430]
[s][vp 8 1 65535 430 0 0]Super move! Ultraaaa Charge![n][f 1 6 65534][e]

[msg btl_support_08_431]
[s][vp 8 1 65535 431 0 0]Support's on the way![n][f 1 6 65534][e]

[msg btl_support_08_432]
[s][vp 8 1 65535 432 0 0]I'll do something about this![n][f 1 6 65534][e]

[msg btl_support_08_433]
[s][vp 8 1 65535 433 0 0]If you're gonna run, now's your[n]chance![n][f 1 6 65534][e]

[msg btl_support_08_434]
[s][vp 8 1 65535 434 0 0]There's no openings! You can't[n]get through them![n][f 1 6 65534][e]

[msg btl_support_08_435]
[s][vp 8 1 65535 435 0 0]Just... hold on a sec! I know I can[n]find SOMEthing...[n][f 1 6 65534][e]

[msg btl_support_08_436]
[s][vp 8 1 65535 436 0 0]Now! Run![n][f 1 6 65534][e]

[msg btl_support_08_437]
[s][vp 8 1 65535 437 0 0]Okay, I'm looking for a way out![n][f 1 6 65534][e]

[msg btl_support_08_438]
[s][vp 8 1 65535 438 0 0]Don't rush me! I'm trying to[n]find you an escape route![n][f 1 6 65534][e]

[msg btl_support_08_439]
[s][vp 8 1 65535 439 0 0]It's no use... There's nowhere[n]to run...[n][f 1 6 65534][e]

[msg btl_support_08_440]
[s][vp 8 1 65535 440 0 0]Beat 'em up![n][f 1 6 65534][e]

[msg btl_support_08_441]
[s][vp 8 1 65535 441 0 0]They're done for![n][f 1 6 65534][e]

[msg btl_support_08_442]
[s][vp 8 1 65535 442 0 0]All-Out Attack![n][f 1 6 65534][e]

[msg btl_support_08_443]
[s][vp 8 1 65535 443 0 0]Ooh! You can hit their weakness![n][f 1 6 65534][e]

[msg btl_support_08_444]
[s][vp 8 1 65535 444 0 0]This is your chance! Hit 'em[n]where it hurts![n][f 1 6 65534][e]

[msg btl_support_08_445]
[s][vp 8 1 65535 445 0 0]Hey, you can go for its weak spot![n][f 1 6 65534][e]

[msg btl_support_08_446]
[s][vp 8 1 65535 446 0 0]Do you have something to hit their[n]weakness...? Welp, guess not![n][f 1 6 65534][e]

[msg btl_support_08_447]
[s][vp 8 1 65535 447 0 0]You don't have any skills that'll[n]hit its weak spot.[n][f 1 6 65534][e]

[msg btl_support_08_448]
[s][vp 8 1 65535 448 0 0]Doesn't look like you can go for[n]its weakness...[n][f 1 6 65534][e]

[msg btl_support_08_449]
[s][vp 8 1 65535 449 0 0]There's an enemy that's scared![n]Now might be the perfect time...[n][f 1 6 65534][e]

[msg btl_support_08_450]
[s][vp 8 1 65535 450 0 0]Guns! You gotta use your guns![n][f 1 6 65534][e]

[msg btl_support_08_451]
[s][vp 8 1 65535 451 0 0]Pass the baton and knock 'em down![n][f 1 6 65534][e]

[msg btl_support_08_452]
[s][vp 8 1 65535 452 0 0]This should do it![n][f 1 6 65534][e]

[msg btl_support_08_453]
[s][vp 8 1 65535 453 0 0]Gunshots are really good here![n][f 1 6 65534][e]

[msg btl_support_08_454]
[s][vp 8 1 65535 454 0 0]You can hit its weakness with[n]Physical attacks![n][f 1 6 65534][e]

[msg btl_support_08_455]
[s][vp 8 1 65535 455 0 0]Physical attacks should[n]do the trick![n][f 1 6 65534][e]

[msg btl_support_08_456]
[s][vp 8 1 65535 456 0 0]You've got good moves, but[n]maybe we should check for[n]weaknesses first![n][f 1 6 65534][e]

[msg btl_support_08_457]
[s][vp 8 1 65535 457 0 0]I dunno its weak point...[n]It's trial-and-error time![n][f 1 6 65534][e]

[msg btl_support_08_458]
[s][vp 8 1 65535 458 0 0]If I knew their affinity...! Just look[n]for their weakness![n][f 1 6 65534][e]

[msg btl_support_08_459]
[s][vp 8 1 65535 459 0 0]Hey, that one's got some treasure![n][f 1 6 65534][e]

[msg btl_support_08_460]
[s][vp 8 1 65535 460 0 0]That enemy's got some loot of its[n]own! Don't let it get away![n][f 1 6 65534][e]

[msg btl_support_08_461]
[s][vp 8 1 65535 461 0 0]Hey, a rare drop![n][f 1 6 65534][e]

[msg btl_support_08_462]
[s][vp 8 1 65535 462 0 0]Good work, everyone![n][f 1 6 65534][e]

[msg btl_support_08_463]
[s][vp 8 1 65535 463 0 0]Just like I thought![n][f 1 6 65534][e]

[msg btl_support_08_464]
[s][vp 8 1 65535 464 0 0]Okay! Let's move on![n][f 1 6 65534][e]

[msg btl_support_08_465]
[s][vp 8 1 65535 465 0 0]We got 'em, but we don't want to[n]waste too much time.[n][f 1 6 65534][e]

[msg btl_support_08_466]
[s][vp 8 1 65535 466 0 0]All enemies defeated! You're still[n]good to go, right?[n][f 1 6 65534][e]

[msg btl_support_08_467]
[s][vp 8 1 65535 467 0 0]Phew, that's a relief. Let's stay[n]out of combat![n][f 1 6 65534][e]

[msg btl_support_08_468]
[s][vp 8 1 65535 468 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_469]
[s][vp 8 1 65535 469 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_470]
[s][vp 8 1 65535 470 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_471]
[s][vp 8 1 65535 471 0 0]No... Hey, wake up! Please![n][f 1 6 65534][e]

[msg btl_support_08_472]
[s][vp 8 1 65535 472 0 0]No, get up! Joker... Jokerrrrrrr![n][f 1 6 65534][e]

[msg btl_support_08_473]
[s][vp 8 1 65535 473 0 0]Get up! It's not over yet![n]Jokerrrrr![n][f 1 6 65534][e]

[msg btl_support_08_474]
[s][vp 8 1 65535 474 0 0]No, Joker... You can't lose to[n]this guy...[n][f 1 6 65534][e]

[msg btl_support_08_475]
[s][vp 8 1 65535 475 0 0]You're joking, right? We've come[n]so far... Please... get up![n][f 1 6 65534][e]

[msg btl_support_08_476]
[s][vp 8 1 65535 476 0 0]No... You can't die... JOKEEERRRR![n][f 1 6 65534][e]

[msg btl_support_08_477]
[s][vp 8 1 65535 477 0 0]Joker, no! Don't give up![n][f 1 6 65534][e]

[msg btl_support_08_478]
[s][vp 8 1 65535 478 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_479]
[s][vp 8 1 65535 479 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_480]
[s][vp 8 1 65535 480 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_481]
[s][vp 8 1 65535 481 0 0]I'll provide backup. So... let's stop[n]his thing.[n][f 1 6 65534][e]

[msg btl_support_08_482]
[s][vp 8 1 65535 482 0 0]His employees are shielding him...[n]Let's break through and punch him[n]right in the face![n][f 1 6 65534][e]

[msg btl_support_08_483]
[s][vp 8 1 65535 483 0 0]There's a penalty for not spinning[n]the roulette. What should we do?[n][f 1 6 65534][e]

[msg btl_support_08_484]
[s][vp 8 1 65535 484 0 0]His new Persona's power is[n]unknown... Everyone, stay[n]on guard![n][f 1 6 65534][e]

[msg btl_support_08_485]
[s][vp 8 1 65535 485 0 0]Risking our lives to stop rotten[n]adults... That's why we're[n]phantom thieves![n][f 1 6 65534][e]

[msg btl_support_08_486]
[s][vp 8 1 65535 486 0 0]This guy's behind everything...[n]but we're all together! We can win![n][f 1 6 65534][e]

[msg btl_support_08_487]
[s][vp 8 1 65535 487 0 0]They're kids, but... they've got[n]the power levels of a final boss![n][f 1 6 65534][e]

[msg btl_support_08_488]
[s][vp 8 1 65535 488 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_489]
[s][vp 8 1 65535 489 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_490]
[s][vp 8 1 65535 490 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_491]
[s][vp 8 1 65535 491 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_492]
[s][vp 8 1 65535 492 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_493]
[s][vp 8 1 65535 493 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_494]
[s][vp 8 1 65535 494 0 0]She's not coming yet! You're still[n]okay![n][f 1 6 65534][e]

[msg btl_support_08_495]
[s][vp 8 1 65535 495 0 0]She's here! Approaching fast![n][f 1 6 65534][e]

[msg btl_support_08_496]
[s][vp 8 1 65535 496 0 0]He's trying to self-destruct!? Beat[n]him now or shield yourself![n][f 1 6 65534][e]

[msg btl_support_08_497]
[s][vp 8 1 65535 497 0 0]Joker! T-Time's up![n][f 1 6 65534][e]

[msg btl_support_08_498]
[s][vp 8 1 65535 498 0 0]She's way more powerful than[n]before! Don't underestimate her![n][f 1 6 65534][e]

[msg btl_support_08_499]
[s][vp 8 1 65535 499 0 0]The enemy's power is rapidly[n]increasing![n][f 1 6 65534][e]

[msg btl_support_08_500]
[s][vp 8 1 65535 500 0 0]What did Akechi do!? The enemies[n]are way stronger now![n][f 1 6 65534][e]

[msg btl_support_08_501]
[s][vp 8 1 65535 501 0 0]Something big's about to hit![n][f 1 6 65534][e]

[msg btl_support_08_502]
[s][vp 8 1 65535 502 0 0]The enemy's offense is going way[n]up! Focus on defense for now![n][f 1 6 65534][e]

[msg btl_support_08_503]
[s][vp 8 1 65535 503 0 0]Power's increasing by the second![n]It's some kind of super move![n][f 1 6 65534][e]

[msg btl_support_08_504]
[s][vp 8 1 65535 504 0 0]The enemy's charging... It's going[n]to be a big one![n][f 1 6 65534][e]

[msg btl_support_08_505]
[s][vp 8 1 65535 505 0 0]You're held down by chains![n]You can't move like that![n][f 1 6 65534][e]

[msg btl_support_08_506]
[s][vp 8 1 65535 506 0 0]And they're Persona-users too!?[n]Who ARE these girls!?[n][f 1 6 65534][e]

[msg btl_support_08_507]
[s][vp 8 1 65535 507 0 0]So powerful... It's over if your[n]weakness is hit.[n][f 1 6 65534][e]

[msg btl_support_08_508]
[s][vp 8 1 65535 508 0 0]Comparing power levels...[n]No threat. Get 'em, Joker![n][f 1 6 65534][e]

[msg btl_support_08_509]
[s][vp 8 1 65535 509 0 0]Everyone else, head to positions![n]Use Route B![n][f 1 6 65534][e]

[msg btl_support_08_510]
[s][vp 8 1 65535 510 0 0]Okay, pull out before their backup[n]gets here.[n][f 1 6 65534][e]

[msg btl_support_08_511]
[s][vp 8 1 65535 511 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_512]
[s][vp 8 1 65535 512 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_513]
[s][vp 8 1 65535 513 0 0]Guns out! Blast 'em off their feet![n][f 1 6 65534][e]

[msg btl_support_08_514]
[s][vp 8 1 65535 514 0 0]Everyone, hang in there! Focus on[n]the enemy in front of you![n][f 1 6 65534][e]

[msg btl_support_08_515]
[s][vp 8 1 65535 515 0 0]Run toward the ballista![n][f 1 6 65534][e]

[msg btl_support_08_516]
[s][vp 8 1 65535 516 0 0]Change direction! Aim the tip[n]at her![n][f 1 6 65534][e]

[msg btl_support_08_517]
[s][vp 8 1 65535 517 0 0]Adjust vertical alignment![n][f 1 6 65534][e]

[msg btl_support_08_518]
[s][vp 8 1 65535 518 0 0]All right, fire![n][f 1 6 65534][e]

[msg btl_support_08_519]
[s][vp 8 1 65535 519 0 0]I can't... lose... here![n][f 1 6 65534][e]

[msg btl_support_08_520]
[s][vp 8 1 65535 520 0 0]If we lose... the world is...[n][f 1 6 65534][e]

[msg btl_support_08_521]
[s][vp 8 1 65535 521 0 0]I need to... get back up...[n][f 1 6 65534][e]

[msg btl_support_08_522]
[s][vp 8 1 65535 522 0 0]I can't move...[n][f 1 6 65534][e]

[msg btl_support_08_523]
[s][vp 8 1 65535 523 0 0]Are we... finished?[n][f 1 6 65534][e]

[msg btl_support_08_524]
[s][vp 8 1 65535 524 0 0]Is this... the end?[n][f 1 6 65534][e]

[msg btl_support_08_525]
[s][vp 8 1 65535 525 0 0]This wasn't... supposed to...[n]happen...[n][f 1 6 65534][e]

[msg btl_support_08_526]
[s][vp 8 1 65535 526 0 0]Huh? Who're these kids?[n][f 1 6 65534][e]

[msg btl_support_08_527]
[s][vp 8 1 65535 527 0 0]Awww... Those little costumes look[n]perfect! They're so cute! Can I take[n]them home with—[n][f 1 6 65534][e]

[msg btl_support_08_528]
[s][vp 8 1 65535 528 0 0]Wait... What!?[n][f 1 6 65534][e]

[msg btl_support_08_529]
[s][vp 8 1 65535 529 0 0]Whoa... for real!? These power[n]levels...[n][f 1 6 65534][e]

[msg btl_support_08_530]
[s][vp 8 1 65535 530 0 0]Watch out! Those two are...[n]monsters![n][f 1 6 65534][e]

[msg btl_support_08_531]
[s][vp 8 1 65535 531 0 0]The countdown's starting again...[n]Take him down before it finishes![n][f 1 6 65534][e]

[msg btl_support_08_532]
[s][vp 8 1 65535 532 0 0]Ngh... The countdown is already[n]halfway finished![n][f 1 6 65534][e]

[msg btl_support_08_533]
[s][vp 8 1 65535 533 0 0]The countdown's getting low...[n]Hurry up, there's not much time[n]left![n][f 1 6 65534][e]

[msg btl_support_08_534]
[s][vp 8 1 65535 534 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_535]
[s][vp 8 1 65535 535 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_536]
[s][vp 8 1 65535 536 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_537]
[s][vp 8 1 65535 537 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_538]
[s][vp 8 1 65535 538 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_539]
[s][vp 8 1 65535 539 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_540]
[s][vp 8 1 65535 540 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_541]
[s][vp 8 1 65535 541 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_542]
[s][vp 8 1 65535 542 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_543]
[s][vp 8 1 65535 543 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_544]
[s][vp 8 1 65535 544 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_545]
[s][vp 8 1 65535 545 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_546]
[s][vp 8 1 65535 546 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_547]
[s][vp 8 1 65535 547 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_548]
[s][vp 8 1 65535 548 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_549]
[s][vp 8 1 65535 549 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_550]
[s][vp 8 1 65535 550 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_551]
[s][vp 8 1 65535 551 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_552]
[s][vp 8 1 65535 552 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_553]
[s][vp 8 1 65535 553 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_554]
[s][vp 8 1 65535 554 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_555]
[s][vp 8 1 65535 555 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_556]
[s][vp 8 1 65535 556 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_557]
[s][vp 8 1 65535 557 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_558]
[s][vp 8 1 65535 558 0 0]Nooo![n][f 1 6 65534][e]

[msg btl_support_08_559]
[s][vp 8 1 65535 559 0 0]Look out![n][f 1 6 65534][e]

[msg btl_support_08_560]
[s][vp 8 1 65535 560 0 0]Joker, you should answer it[n]this way![n][f 1 6 65534][e]

[msg btl_support_08_561]
[s][vp 8 1 65535 561 0 0]The answer it's looking for is...[n]this one![n][f 1 6 65534][e]

[msg btl_support_08_562]
[s][vp 8 1 65535 562 0 0]This is what it wants to hear![n][f 1 6 65534][e]

[msg btl_support_08_563]
[s][vp 8 1 65535 563 0 0]Necronomicon![n][f 1 6 65534][e]

[msg btl_support_08_564]
[s][vp 8 1 65535 564 0 0]Necronomicon, intercept![n][f 1 6 65534][e]

[msg btl_support_08_565]
[s][vp 8 1 65535 565 0 0]Prometheus![n][f 1 6 65534][e]

[msg btl_support_08_566]
[s][vp 8 1 65535 566 0 0]Prometheus, interfere![n][f 1 6 65534][e]

[msg btl_support_08_567]
[s][vp 8 1 65535 567 0 0]This one's strong! Be careful![n][f 1 6 65534][e]

[msg btl_support_08_568]
[s][vp 8 1 65535 568 0 0]Physical strikes will hit it hard![n]It's strong, but you can do it![n][f 1 6 65534][e]

[msg btl_support_08_569]
[s][vp 8 1 65535 569 0 0]It's powerful, but weak to gunfire![n]You can handle this![n][f 1 6 65534][e]

[msg btl_support_08_570]
[s][vp 8 1 65535 570 0 0]Fire is its weak point! It's powerful;[n]hang in there![n][f 1 6 65534][e]

[msg btl_support_08_571]
[s][vp 8 1 65535 571 0 0]This guy's weak to Ice! It's tough,[n]but not unbeatable![n][f 1 6 65534][e]

[msg btl_support_08_572]
[s][vp 8 1 65535 572 0 0]It's weak to Wind! Good luck![n][f 1 6 65534][e]

[msg btl_support_08_573]
[s][vp 8 1 65535 573 0 0]Don't worry, just use Electricity[n]attacks and you'll be fine![n][f 1 6 65534][e]

[msg btl_support_08_574]
[s][vp 8 1 65535 574 0 0]Bless attacks'll do it! The bigger[n]they are, the harder they fall![n][f 1 6 65534][e]

[msg btl_support_08_575]
[s][vp 8 1 65535 575 0 0]It's strong, but Curse attacks[n]should get through! You can[n]do it![n][f 1 6 65534][e]

[msg btl_support_08_576]
[s][vp 8 1 65535 576 0 0]Nukes are its weakness! It's strong,[n]but you can take it![n][f 1 6 65534][e]

[msg btl_support_08_577]
[s][vp 8 1 65535 577 0 0]Weak to... Psychokinesis! It's tough,[n]but it's beatable![n][f 1 6 65534][e]

[msg btl_support_08_578]
[s][vp 8 1 65535 578 0 0]This one's strong, and Physical[n]attacks don't work![n][f 1 6 65534][e]

[msg btl_support_08_579]
[s][vp 8 1 65535 579 0 0]No guns here! This one's gonna[n]be tough![n][f 1 6 65534][e]

[msg btl_support_08_580]
[s][vp 8 1 65535 580 0 0]It's a tough one! Don't use[n]Fire attacks![n][f 1 6 65534][e]

[msg btl_support_08_581]
[s][vp 8 1 65535 581 0 0]Don't use any Ice skills![n]Be careful here![n][f 1 6 65534][e]

[msg btl_support_08_582]
[s][vp 8 1 65535 582 0 0]Avoid using Wind, and don't[n]let your guard down![n][f 1 6 65534][e]

[msg btl_support_08_583]
[s][vp 8 1 65535 583 0 0]This guy's strong! Electricity won't[n]do a thing![n][f 1 6 65534][e]

[msg btl_support_08_584]
[s][vp 8 1 65535 584 0 0]This Shadow's strong! Bless skills[n]won't work at all![n][f 1 6 65534][e]

[msg btl_support_08_585]
[s][vp 8 1 65535 585 0 0]Curse moves won't work, so be[n]careful! It's a major threat![n][f 1 6 65534][e]

[msg btl_support_08_586]
[s][vp 8 1 65535 586 0 0]It's strong, and Nuclear skills won't[n]work. Keep your eyes open![n][f 1 6 65534][e]

[msg btl_support_08_587]
[s][vp 8 1 65535 587 0 0]This one's powerful... and[n]Psychokinetic stuff is useless![n][f 1 6 65534][e]

[msg btl_support_08_588]
[s][vp 8 1 65535 588 0 0]All right, you can do it! This fight[n]is ours![n][f 1 6 65534][e]

[msg btl_support_08_589]
[s][vp 8 1 65535 589 0 0]It's weak to Physical hits![n]Knock 'em out![n][f 1 6 65534][e]

[msg btl_support_08_590]
[s][vp 8 1 65535 590 0 0]Ooh, it's weak to gunfire![n]Ready... Aim...[n][f 1 6 65534][e]

[msg btl_support_08_591]
[s][vp 8 1 65535 591 0 0]Weak to Fire! You can beat this guy![n][f 1 6 65534][e]

[msg btl_support_08_592]
[s][vp 8 1 65535 592 0 0]Its weak point is Ice! Should be[n]no problem![n][f 1 6 65534][e]

[msg btl_support_08_593]
[s][vp 8 1 65535 593 0 0]Wind skills are effective![n]You can beat 'em![n][f 1 6 65534][e]

[msg btl_support_08_594]
[s][vp 8 1 65535 594 0 0]Electricity should stop it![n]Go get 'em![n][f 1 6 65534][e]

[msg btl_support_08_595]
[s][vp 8 1 65535 595 0 0]This guy's nothing special.[n]It's weak to Bless attacks![n][f 1 6 65534][e]

[msg btl_support_08_596]
[s][vp 8 1 65535 596 0 0]Curse skills oughta do it![n]Show 'em who's boss![n][f 1 6 65534][e]

[msg btl_support_08_597]
[s][vp 8 1 65535 597 0 0]This one's weak to Nuclear![n][f 1 6 65534][e]

[msg btl_support_08_598]
[s][vp 8 1 65535 598 0 0]Psychokinesis will mess this guy up![n][f 1 6 65534][e]

[msg btl_support_08_599]
[s][vp 8 1 65535 599 0 0]Physical attacks won't work![n][f 1 6 65534][e]

[msg btl_support_08_600]
[s][vp 8 1 65535 600 0 0]Gunshots will be ineffective![n][f 1 6 65534][e]

[msg btl_support_08_601]
[s][vp 8 1 65535 601 0 0]Fire attacks are a no-go, so watch it![n][f 1 6 65534][e]

[msg btl_support_08_602]
[s][vp 8 1 65535 602 0 0]FYI, it's strong against Ice![n][f 1 6 65534][e]

[msg btl_support_08_603]
[s][vp 8 1 65535 603 0 0]Wind's not gonna work![n]Try something else![n][f 1 6 65534][e]

[msg btl_support_08_604]
[s][vp 8 1 65535 604 0 0]No Electric attacks! Try something[n]else![n][f 1 6 65534][e]

[msg btl_support_08_605]
[s][vp 8 1 65535 605 0 0]Watch out! Bless skills won't work[n]here![n][f 1 6 65534][e]

[msg btl_support_08_606]
[s][vp 8 1 65535 606 0 0]Listen up! Don't use Curse moves![n][f 1 6 65534][e]

[msg btl_support_08_607]
[s][vp 8 1 65535 607 0 0]Nukes won't work on this enemy![n][f 1 6 65534][e]

[msg btl_support_08_608]
[s][vp 8 1 65535 608 0 0]Psychokinesis won't hurt this[n]Shadow![n][f 1 6 65534][e]

[msg btl_support_08_609]
[s][vp 8 1 65535 609 0 0]This guy's a joke! You could do this[n]in your sleep![n][f 1 6 65534][e]

[msg btl_support_08_610]
[s][vp 8 1 65535 610 0 0]Ooh, this one's easy. Just hit 'em[n]with Physical strikes![n][f 1 6 65534][e]

[msg btl_support_08_611]
[s][vp 8 1 65535 611 0 0]It can't take gunshots! Fill 'em with[n]lead![n][f 1 6 65534][e]

[msg btl_support_08_612]
[s][vp 8 1 65535 612 0 0]It's weak against Fire! Toasty![n][f 1 6 65534][e]

[msg btl_support_08_613]
[s][vp 8 1 65535 613 0 0]It's weak to Ice! Turn 'em into[n]a popsicle![n][f 1 6 65534][e]

[msg btl_support_08_614]
[s][vp 8 1 65535 614 0 0]Wind works here! Let's clean[n]'em up![n][f 1 6 65534][e]

[msg btl_support_08_615]
[s][vp 8 1 65535 615 0 0]Electricity's what you want.[n]Fry their circuits.[n][f 1 6 65534][e]

[msg btl_support_08_616]
[s][vp 8 1 65535 616 0 0]Bless skills should work.[n]Evil, begone![n][f 1 6 65534][e]

[msg btl_support_08_617]
[s][vp 8 1 65535 617 0 0]Curses should help! Give 'em a[n]one-way ticket to hell![n][f 1 6 65534][e]

[msg btl_support_08_618]
[s][vp 8 1 65535 618 0 0]It can't take nuclear damage![n]Let's finish this off![n][f 1 6 65534][e]

[msg btl_support_08_619]
[s][vp 8 1 65535 619 0 0]Psychokinesis works. Show 'em[n]whatcha got.[n][f 1 6 65534][e]

[msg btl_support_08_620]
[s][vp 8 1 65535 620 0 0]It's a weakling, but Physical attacks[n]won't work![n][f 1 6 65534][e]

[msg btl_support_08_621]
[s][vp 8 1 65535 621 0 0]Guns won't work—but it's a[n]total loser![n][f 1 6 65534][e]

[msg btl_support_08_622]
[s][vp 8 1 65535 622 0 0]Fire won't help here... Ugh, but it's[n]so pathetic![n][f 1 6 65534][e]

[msg btl_support_08_623]
[s][vp 8 1 65535 623 0 0]Ice won't work? Wow, but it looks[n]really weak.[n][f 1 6 65534][e]

[msg btl_support_08_624]
[s][vp 8 1 65535 624 0 0]Don't use Wind attacks! Otherwise,[n]you're good![n][f 1 6 65534][e]

[msg btl_support_08_625]
[s][vp 8 1 65535 625 0 0]This guy sucks. Oh, but don't use[n]anything Electric.[n][f 1 6 65534][e]

[msg btl_support_08_626]
[s][vp 8 1 65535 626 0 0]Bless stuff won't work.[n]Try something else![n][f 1 6 65534][e]

[msg btl_support_08_627]
[s][vp 8 1 65535 627 0 0]Don't use Curse skills...! But really,[n]it's totally weak.[n][f 1 6 65534][e]

[msg btl_support_08_628]
[s][vp 8 1 65535 628 0 0]Nuclear stuff won't work. Just use[n]something else.[n][f 1 6 65534][e]

[msg btl_support_08_629]
[s][vp 8 1 65535 629 0 0]Psychokinesis is out, but you've[n]got nothing to worry about![n][f 1 6 65534][e]

[msg btl_support_08_630]
[s][vp 8 1 65535 630 0 0]Not bad![n][f 1 6 65534][e]

[msg btl_support_08_631]
[s][vp 8 1 65535 631 0 0]You're amazing as always, Joker![n][f 1 6 65534][e]

[msg btl_support_08_632]
[s][vp 8 1 65535 632 0 0]You didn't have that one yet, Joker![n][f 1 6 65534][e]

[msg btl_support_08_633]
[s][vp 8 1 65535 633 0 0]That's another mask for you, Joker![n][f 1 6 65534][e]

[msg btl_support_08_634]
[s][vp 8 1 65535 634 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_635]
[s][vp 8 1 65535 635 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_636]
[s][vp 8 1 65535 636 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_637]
[s][vp 8 1 65535 637 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_638]
[s][vp 8 1 65535 638 0 0]A Baton Pass'll help you hit[n]the enemy's weakness![n][f 1 6 65534][e]

[msg btl_support_08_639]
[s][vp 8 1 65535 639 0 0]You'll be able to knock the enemy[n]down if you pass the baton![n][f 1 6 65534][e]

[msg btl_support_08_640]
[s][vp 8 1 65535 640 0 0]It's Baton Pass time![n][f 1 6 65534][e]

[msg btl_support_08_641]
[s][vp 8 1 65535 641 0 0]Now's your chance! Pass the baton![n][f 1 6 65534][e]

[msg btl_support_08_642]
[s][vp 8 1 65535 642 0 0]Pass that baton! Go for[n]a knockdown![n][f 1 6 65534][e]

[msg btl_support_08_643]
[s][vp 8 1 65535 643 0 0]Watch out, the enemy's coming![n][f 1 6 65534][e]

[msg btl_support_08_644]
[s][vp 8 1 65535 644 0 0]The enemy's gonna attack![n]Make sure you heal yourself![n][f 1 6 65534][e]

[msg btl_support_08_645]
[s][vp 8 1 65535 645 0 0]Watch yourself! The Shadow's[n]gonna make its move soon![n][f 1 6 65534][e]

[msg btl_support_08_646]
[s][vp 8 1 65535 646 0 0]Whoa, it's about to attack![n]Check your health![n][f 1 6 65534][e]

[msg btl_support_08_647]
[s][vp 8 1 65535 647 0 0]You need to heal before the enemy[n]attacks![n][f 1 6 65534][e]

[msg btl_support_08_648]
[s][vp 8 1 65535 648 0 0]The enemy's on fire! Stoke the[n]flames with a Wind attack![n][f 1 6 65534][e]

[msg btl_support_08_649]
[s][vp 8 1 65535 649 0 0]An enemy's frozen! Shatter it with[n]a Physical attack![n][f 1 6 65534][e]

[msg btl_support_08_650]
[s][vp 8 1 65535 650 0 0]The enemy's electrocuted! Go[n]smack 'em, but don't get shocked[n]yourself![n][f 1 6 65534][e]

[msg btl_support_08_651]
[s][vp 8 1 65535 651 0 0]It's asleep! Go, go, go![n][f 1 6 65534][e]

[msg btl_support_08_652]
[s][vp 8 1 65535 652 0 0]One of 'em is dizzy! Knock that[n]jerk down![n][f 1 6 65534][e]

[msg btl_support_08_653]
[s][vp 8 1 65535 653 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_654]
[s][vp 8 1 65535 654 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_655]
[s][vp 8 1 65535 655 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_656]
[s][vp 8 1 65535 656 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_657]
[s][vp 8 1 65535 657 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_658]
[s][vp 8 1 65535 658 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_659]
[s][vp 8 1 65535 659 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_660]
[s][vp 8 1 65535 660 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_661]
[s][vp 8 1 65535 661 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_662]
[s][vp 8 1 65535 662 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_663]
[s][vp 8 1 65535 663 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_664]
[s][vp 8 1 65535 664 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_665]
[s][vp 8 1 65535 665 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_666]
[s][vp 8 1 65535 666 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_667]
[s][vp 8 1 65535 667 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_668]
[s][vp 8 1 65535 668 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_669]
[s][vp 8 1 65535 669 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_670]
[s][vp 8 1 65535 670 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_671]
[s][vp 8 1 65535 671 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_672]
[s][vp 8 1 65535 672 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_673]
[s][vp 8 1 65535 673 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_674]
[s][vp 8 1 65535 674 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_675]
[s][vp 8 1 65535 675 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_676]
[s][vp 8 1 65535 676 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_677]
[s][vp 8 1 65535 677 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_678]
[s][vp 8 1 65535 678 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_679]
[s][vp 8 1 65535 679 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_680]
[s][vp 8 1 65535 680 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_681]
[s][vp 8 1 65535 681 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_682]
[s][vp 8 1 65535 682 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_683]
[s][vp 8 1 65535 683 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_684]
[s][vp 8 1 65535 684 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_685]
[s][vp 8 1 65535 685 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_686]
[s][vp 8 1 65535 686 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_687]
[s][vp 8 1 65535 687 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_688]
[s][vp 8 1 65535 688 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_689]
[s][vp 8 1 65535 689 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_690]
[s][vp 8 1 65535 690 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_691]
[s][vp 8 1 65535 691 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_692]
[s][vp 8 1 65535 692 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_693]
[s][vp 8 1 65535 693 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_694]
[s][vp 8 1 65535 694 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_695]
[s][vp 8 1 65535 695 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_696]
[s][vp 8 1 65535 696 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_697]
[s][vp 8 1 65535 697 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_698]
[s][vp 8 1 65535 698 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_699]
[s][vp 8 1 65535 699 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_700]
[s][vp 8 1 65535 700 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_701]
[s][vp 8 1 65535 701 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_702]
[s][vp 8 1 65535 702 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_703]
[s][vp 8 1 65535 703 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_704]
[s][vp 8 1 65535 704 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_705]
[s][vp 8 1 65535 705 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_706]
[s][vp 8 1 65535 706 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_707]
[s][vp 8 1 65535 707 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_708]
[s][vp 8 1 65535 708 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_709]
[s][vp 8 1 65535 709 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_710]
[s][vp 8 1 65535 710 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_711]
[s][vp 8 1 65535 711 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_712]
[s][vp 8 1 65535 712 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_713]
[s][vp 8 1 65535 713 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_714]
[s][vp 8 1 65535 714 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_715]
[s][vp 8 1 65535 715 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_716]
[s][vp 8 1 65535 716 0 0]There's an enemy out to get us![n]Be careful![n][f 1 6 65534][e]

[msg btl_support_08_717]
[s][vp 8 1 65535 717 0 0]The security level is higher! We've[n]got a tough enemy ahead![n][f 1 6 65534][e]

[msg btl_support_08_718]
[s][vp 8 1 65535 718 0 0]That dark enemy's powered up![n]Watch out![n][f 1 6 65534][e]

[msg btl_support_08_719]
[s][vp 8 1 65535 719 0 0]That dark one's a super-strong[n]version! Don't underestimate it![n][f 1 6 65534][e]

[msg btl_support_08_720]
[s][vp 8 1 65535 720 0 0]That one's powered up! If you're[n]gonna try to beat it, be careful![n][f 1 6 65534][e]

[msg btl_support_08_721]
[s][vp 8 1 65535 721 0 0]They're totally on to us! Things are[n]dangerous right now![n][f 1 6 65534][e]

[msg btl_support_08_722]
[s][vp 8 1 65535 722 0 0]They're on full alert! Maybe we[n]shouldn't be fighting![n][f 1 6 65534][e]

[msg btl_support_08_723]
[s][vp 8 1 65535 723 0 0]Security's on the lookout for you![n]Don't fight them head on![n][f 1 6 65534][e]

[msg btl_support_08_724]
[s][vp 8 1 65535 724 0 0]They're on total lockdown! If we[n]try and fight, this'll never end![n][f 1 6 65534][e]

[msg btl_support_08_725]
[s][vp 8 1 65535 725 0 0]This isn't good! They've got eyes[n]on us![n][f 1 6 65534][e]

[msg btl_support_08_726]
[s][vp 8 1 65535 726 0 0]There's an enemy on high alert![n]Look out for that darker one![n][f 1 6 65534][e]

[msg btl_support_08_727]
[s][vp 8 1 65535 727 0 0]That dark enemy's stronger than[n]the usual guys![n][f 1 6 65534][e]

[msg btl_support_08_728]
[s][vp 8 1 65535 728 0 0]There's a powerful enemy on the[n]field! Watch out![n][f 1 6 65534][e]

[msg btl_support_08_729]
[s][vp 8 1 65535 729 0 0]One of the enemies is really tough![n]It's out to get you guys![n][f 1 6 65534][e]

[msg btl_support_08_730]
[s][vp 8 1 65535 730 0 0]Watch out for the darker Shadow![n]It's no ordinary enemy![n][f 1 6 65534][e]

[msg btl_support_08_731]
[s][vp 8 1 65535 731 0 0]They've already gone! Switch with[n]someone else![n][f 1 6 65534][e]

[msg btl_support_08_732]
[s][vp 8 1 65535 732 0 0]If you're gonna pass it, pass it to[n]someone who hasn't had a turn![n][f 1 6 65534][e]

[msg btl_support_08_733]
[s][vp 8 1 65535 733 0 0]0[n][f 1 6 65534][e]

[msg btl_support_08_734]
[s][vp 8 1 65535 734 0 0]It's no good! You can't talk to it![n][f 1 6 65534][e]

[msg btl_support_08_735]
[s][vp 8 1 65535 735 0 0]We can't talk right now![n][f 1 6 65534][e]

[msg btl_support_08_736]
[s][vp 8 1 65535 736 0 0]The enemies recovered. Look out![n][f 1 6 65534][e]

[msg btl_support_08_737]
[s][vp 8 1 65535 737 0 0]Aww, it's better now. Don't let[n]your guard down![n][f 1 6 65534][e]

[msg btl_support_08_738]
[s][vp 8 1 65535 738 0 0]Everyone's in danger![n][f 1 6 65534][e]

[msg btl_support_08_739]
[s][vp 8 1 65535 739 0 0]I won't let you![n][f 1 6 65534][e]

[msg btl_support_08_740]
[s][vp 8 1 65535 740 0 0]Leave it to me![n][f 1 6 65534][e]

[msg btl_support_08_741]
[s][vp 8 1 65535 741 0 0]Time for my power...![n][f 1 6 65534][e]

[msg btl_support_08_742]
[s][vp 8 1 65535 742 0 0]Amazing, Joker![n][f 1 6 65534][e]

[msg btl_support_08_743]
[s][vp 8 1 65535 743 0 0]Ooooh, that was cool...[n][f 1 6 65534][e]

[msg btl_support_08_744]
[s][vp 8 1 65535 744 0 0]All right! On to the next![n][f 1 6 65534][e]

[msg btl_support_08_745]
[s][vp 8 1 65535 745 0 0]Not done yet![n][f 1 6 65534][e]

[msg btl_support_08_746]
[s][vp 8 1 65535 746 0 0]Next up! Get 'em![n][f 1 6 65534][e]

[msg btl_support_08_747]
[s][vp 8 1 65535 747 0 0]A second Baton Pass! Nice![n][f 1 6 65534][e]

[msg btl_support_08_748]
[s][vp 8 1 65535 748 0 0]Everyone's had a shot![n]Nice combos![n][f 1 6 65534][e]

[msg btl_support_08_749]
[s][vp 8 1 65535 749 0 0]Everyone passed the baton![n]That was perfect![n][f 1 6 65534][e]

[msg btl_support_08_750]
[s][vp 8 1 65535 750 0 0]The Baton Pass powered you up![n][f 1 6 65534][e]

[msg btl_support_08_751]
[s][vp 8 1 65535 751 0 0]Okay, that pass brought your[n]power even higher![n][f 1 6 65534][e]

[msg btl_support_08_752]
[s][vp 8 1 65535 752 0 0]Handed it off again![n]You're powering up![n][f 1 6 65534][e]

[msg btl_support_08_753]
[s][vp 8 1 65535 753 0 0]A two-pass combo! Your power's[n]going up![n][f 1 6 65534][e]

[msg btl_support_08_754]
[s][vp 8 1 65535 754 0 0]Everyone passed the baton![n]You're at max power; go get 'em![n][f 1 6 65534][e]

[msg btl_support_08_755]
[s][vp 8 1 65535 755 0 0]Everyone's had the baton! Your[n]power is through the roof![n][f 1 6 65534][e]

[msg btl_support_08_756]
[s][vp 8 1 65535 756 0 0]Nice![n][f 1 6 65534][e]

[msg btl_support_08_757]
[s][vp 8 1 65535 757 0 0]Ooh! Free stuff.[n][f 1 6 65534][e]

[msg btl_support_08_758]
[s][vp 8 1 65535 758 0 0]I guess you know how to keep[n]people talking![n][f 1 6 65534][e]

[msg btl_support_08_759]
[s][vp 8 1 65535 759 0 0]You got extra? You're pretty good[n]with words.[n][f 1 6 65534][e]

[msg btl_support_08_760]
[s][vp 8 1 65535 760 0 0]That guy's trying to run! Watch out![n][f 1 6 65534][e]

[msg btl_support_08_761]
[s][vp 8 1 65535 761 0 0]It'll be bad if we let it escape![n]Move quickly![n][f 1 6 65534][e]

[msg btl_support_08_762]
[s][vp 8 1 65535 762 0 0]Oh, it got away... Security's gonna[n]be tight now...[n][f 1 6 65534][e]

[msg btl_support_08_763]
[s][vp 8 1 65535 763 0 0]Not good! It's going to put[n]everyone on alert![n][f 1 6 65534][e]

[msg btl_support_08_764]
[s][vp 8 1 65535 764 0 0]It's a surge of lust! The fantasies[n]are blocking everything out![n][f 1 6 65534][e]

[msg btl_support_08_765]
[s][vp 8 1 65535 765 0 0]Oh no! The lust effect might[n]keep you from moving![n][f 1 6 65534][e]

[msg btl_support_08_766]
[s][vp 8 1 65535 766 0 0]Wrath!? No! You gotta listen to me![n][f 1 6 65534][e]

[msg btl_support_08_767]
[s][vp 8 1 65535 767 0 0]It's a surge of wrath! You hafta try[n]to calm down![n][f 1 6 65534][e]

[msg btl_support_08_768]
[s][vp 8 1 65535 768 0 0]It's a surge of envy! It's trying to[n]make you fight each other...[n][f 1 6 65534][e]

[msg btl_support_08_769]
[s][vp 8 1 65535 769 0 0]You're filled with envy!? Hey![n]Don't go against each other![n][f 1 6 65534][e]

[msg btl_support_08_770]
[s][vp 8 1 65535 770 0 0]A surge of gluttony? Persona[n]summoning might take more[n]effort...[n][f 1 6 65534][e]

[msg btl_support_08_771]
[s][vp 8 1 65535 771 0 0]Gluttony! Watch out when you use[n]your Personas![n][f 1 6 65534][e]

[msg btl_support_08_772]
[s][vp 8 1 65535 772 0 0]If you attack now, you'll be[n]countered! Be careful![n][f 1 6 65534][e]

[msg btl_support_08_773]
[s][vp 8 1 65535 773 0 0]Pride...! Don't attack, or you'll get[n]countered instantly![n][f 1 6 65534][e]

[msg btl_support_08_774]
[s][vp 8 1 65535 774 0 0]Hey! You need to focus on[n]the battle![n][f 1 6 65534][e]

[msg btl_support_08_775]
[s][vp 8 1 65535 775 0 0]Hey! Now's not the time to get[n]distracted![n][f 1 6 65534][e]

[msg btl_support_08_776]
[s][vp 8 1 65535 776 0 0]Hey! Calm down! We're on[n]your side![n][f 1 6 65534][e]

[msg btl_support_08_777]
[s][vp 8 1 65535 777 0 0]Hey! We can't afford to fight[n]amongst ourselves![n][f 1 6 65534][e]

[msg btl_support_08_778]
[s][vp 8 1 65535 778 0 0]I told you not to attack![n][f 1 6 65534][e]

[msg btl_support_08_779]
[s][vp 8 1 65535 779 0 0]Oh no... A counterattack![n][f 1 6 65534][e]

[msg btl_support_08_780]
[s][vp 8 1 65535 780 0 0]We're breaking through them![n]Follow Joker's lead![n][f 1 6 65534][e]

[msg btl_support_08_781]
[s][vp 8 1 65535 781 0 0]Oooh! An instant win. Sounds like[n]free cash![n][f 1 6 65534][e]

[msg btl_support_08_782]
[s][vp 8 1 65535 782 0 0]That punk![n][f 1 6 65534][e]

[msg btl_support_08_783]
[s][vp 8 1 65535 783 0 0]Be careful![n][f 1 6 65534][e]

[msg btl_support_08_784]
[s][vp 8 1 65535 784 0 0]This weakling...[n][f 1 6 65534][e]

[msg btl_support_08_785]
[s][vp 8 1 65535 785 0 0]It's powerful. If you're gonna[n]try to beat it, be careful![n][f 1 6 65534][e]

[msg btl_support_08_786]
[s][vp 8 1 65535 786 0 0]It's powerful—don't[n]underestimate it![n][f 1 6 65534][e]

[msg btl_support_08_787]
[s][vp 8 1 65535 787 0 0]Now's our chance to book it![n][f 1 6 65534][e]

[msg btl_support_08_788]
[s][vp 8 1 65535 788 0 0]We should retreat for now![n][f 1 6 65534][e]

[msg btl_support_08_789]
[s][vp 8 1 65535 1001 0 0]Violet's down! Someone help her![n][f 1 6 65534][e]

[msg btl_support_08_790]
[s][vp 8 1 65535 1002 0 0]Violet's about to give up the ghost![n]Somebody do something![n][f 1 6 65534][e]

[msg btl_support_08_791]
[s][vp 8 1 65535 1003 0 0]Violet! Please get up![n][f 1 6 65534][e]

[msg btl_support_08_792]
[s][vp 8 1 65535 1004 0 0]Nice, Violet! Just what I would[n]expect from an athlete![n][f 1 6 65534][e]

[msg btl_support_08_793]
[s][vp 8 1 65535 1005 0 0]Violet's attack is less powerful now![n][f 1 6 65534][e]

[msg btl_support_08_794]
[s][vp 8 1 65535 1006 0 0]Violet's defense is weakened![n][f 1 6 65534][e]

[msg btl_support_08_795]
[s][vp 8 1 65535 1007 0 0]Violet's slower now![n][f 1 6 65534][e]

[msg btl_support_08_796]
[s][vp 8 1 65535 1008 0 0]Violet's in real trouble![n]Hurry, heal her![n][f 1 6 65534][e]

[msg btl_support_08_797]
[s][vp 8 1 65535 1009 0 0]Violet is burning! She can't move[n]without hurting herself![n][f 1 6 65534][e]

[msg btl_support_08_798]
[s][vp 8 1 65535 1010 0 0]Violet's frozen! She can't move[n]at all![n][f 1 6 65534][e]

[msg btl_support_08_799]
[s][vp 8 1 65535 1011 0 0]Violet got shocked! She's paralyzed![n][f 1 6 65534][e]

[msg btl_support_08_800]
[s][vp 8 1 65535 1012 0 0]Violet's all dizzy! She can barely[n]land her attacks in that state![n][f 1 6 65534][e]

[msg btl_support_08_801]
[s][vp 8 1 65535 1013 0 0]Violet, no! You're confused![n]Don't attack your friends![n][f 1 6 65534][e]

[msg btl_support_08_802]
[s][vp 8 1 65535 1014 0 0]Listen, Violet's terrified right[n]now! She might run away![n][f 1 6 65534][e]

[msg btl_support_08_803]
[s][vp 8 1 65535 1015 0 0]Violet's too forgetful to use her[n]Persona![n][f 1 6 65534][e]

[msg btl_support_08_804]
[s][vp 8 1 65535 1016 0 0]Violet's hungry, and it's totally[n]sapped her strength![n][f 1 6 65534][e]

[msg btl_support_08_805]
[s][vp 8 1 65535 1017 0 0]Violet's asleep! What if something[n]attacks her!?[n][f 1 6 65534][e]

[msg btl_support_08_806]
[s][vp 8 1 65535 1018 0 0]Violet's enraged! Violet, try to[n]keep your cool![n][f 1 6 65534][e]

[msg btl_support_08_807]
[s][vp 8 1 65535 1019 0 0]Violet's in despair! If you leave her[n]like that, something awful could[n]happen![n][f 1 6 65534][e]

[msg btl_support_08_808]
[s][vp 8 1 65535 1020 0 0]Violet's been brainwashed![n]Watch out, she might attack you![n][f 1 6 65534][e]

[msg btl_support_08_809]
[s][vp 8 1 65535 1021 0 0]ヴァイオレットがネズミ状態だ![n]これじゃ手も足も出ないぞ![n][f 1 6 65534][e]

[msg btl_support_08_810]
[s][vp 8 1 65535 1022 0 0]Violet stood up! Forward, march![n][f 1 6 65534][e]

[msg btl_support_08_811]
[s][vp 8 1 65535 1023 0 0]That wiped them all out! A+, Violet![n][f 1 6 65534][e]

[msg btl_support_08_812]
[s][vp 8 1 65535 1024 0 0]Violet got rid of four enemies[n]at once![n][f 1 6 65534][e]

[msg btl_support_08_813]
[s][vp 8 1 65535 1025 0 0]Three enemies down! Nice, Violet![n][f 1 6 65534][e]

[msg btl_support_08_814]
[s][vp 8 1 65535 1026 0 0]Go Violet! Two birds with[n]one stone![n][f 1 6 65534][e]

[msg btl_support_08_815]
[s][vp 8 1 65535 1027 0 0]That's one enemy terminated![n]Show us what you got, Violet![n][f 1 6 65534][e]

[msg btl_support_08_816]
[s][vp 8 1 65535 1028 0 0]All enemies are down![n]Thank Violet![n][f 1 6 65534][e]

[msg btl_support_08_817]
[s][vp 8 1 65535 1029 0 0]Four enemies down! Round of[n]applause for Violet![n][f 1 6 65534][e]

[msg btl_support_08_818]
[s][vp 8 1 65535 1030 0 0]Three enemies got knocked down![n]Keep it going![n][f 1 6 65534][e]

[msg btl_support_08_819]
[s][vp 8 1 65535 1031 0 0]Two enemies knocked down![n]Don't hold back, Violet![n][f 1 6 65534][e]

[msg btl_support_08_820]
[s][vp 8 1 65535 1032 0 0]Good job, Violet![n][f 1 6 65534][e]

[msg btl_support_08_821]
[s][vp 8 1 65535 1033 0 0]Yay Violet! You went right for[n]its weakness![n][f 1 6 65534][e]

[msg btl_support_08_822]
[s][vp 8 1 65535 1034 0 0]What a performance! That was[n]awesome, Violet![n][f 1 6 65534][e]

[msg btl_support_08_823]
[s][vp 8 1 65535 1035 0 0]Aw, I gotta deduct points for that,[n]Violet![n][f 1 6 65534][e]

[msg btl_support_08_824]
[s][vp 8 1 65535 1036 0 0]Where's Violet going? Is she[n]giving up?[n][f 1 6 65534][e]

[msg btl_support_08_825]
[s][vp 8 1 65535 1037 0 0]Treasure Demon in sight![n]Let's get it![n][f 1 6 65534][e]

[msg btl_support_08_826]
[s][vp 8 1 65535 1038 0 0]Oooh, a rare one![n][f 1 6 65534][e]

[msg btl_support_08_827]
[s][vp 8 1 65535 1039 0 0]Whoa, that one's really rare![n][f 1 6 65534][e]

[msg btl_support_08_828]
[s][vp 8 1 65535 1040 0 0]Watch out, that one's dangerous![n][f 1 6 65534][e]

[msg btl_support_08_829]
[s][vp 8 1 65535 1041 0 0]I have a bad feeling about that one...[n][f 1 6 65534][e]

[msg btl_support_08_830]
[s][vp 8 1 65535 1042 0 0]That one's just weird! I don't know[n]what it's gonna do.[n][f 1 6 65534][e]

[msg btl_support_08_831]
[s][vp 8 1 65535 1043 0 0]Woohoo, money![n][f 1 6 65534][e]

[msg btl_support_08_832]
[s][vp 8 1 65535 1044 0 0]Payday! Get that money![n][f 1 6 65534][e]

[msg btl_support_08_833]
[s][vp 8 1 65535 1045 0 0]Cha-ching! We're rich![n][f 1 6 65534][e]

[msg btl_support_08_834]
[s][vp 8 1 65535 1046 0 0]This Treasure Demon's done for![n][f 1 6 65534][e]

[msg btl_support_08_835]
[s][vp 8 1 65535 1047 0 0]It had some rare loot![n][f 1 6 65534][e]

[msg btl_support_08_836]
[s][vp 8 1 65535 1048 0 0]Treasure! Woot, woot![n][f 1 6 65534][e]

[msg btl_support_08_837]
[s][vp 8 1 65535 1049 0 0]Bombs away![n][f 1 6 65534][e]

[msg btl_support_08_838]
[s][vp 8 1 65535 1050 0 0]It's like fireworks! Ooh, aah, so[n]pretty! And so much damage![n][f 1 6 65534][e]

[msg btl_support_08_839]
[s][vp 8 1 65535 1051 0 0]Sometimes you just wanna explode![n][f 1 6 65534][e]

[msg btl_support_08_840]
[s][vp 8 1 65535 1052 0 0]Oh, whaaat? They're no fun![n][f 1 6 65534][e]

[msg btl_support_08_841]
[s][vp 8 1 65535 1053 0 0]I know something that'll[n]protect you![n][f 1 6 65534][e]

[msg btl_support_08_842]
[s][vp 8 1 65535 1054 0 0]Leave all the support stuff to me![n][f 1 6 65534][e]

[msg btl_support_08_843]
[s][vp 8 1 65535 1055 0 0]Lemme help![n][f 1 6 65534][e]

[msg btl_support_08_844]
[s][vp 8 1 65535 1056 0 0]How's this!?[n][f 1 6 65534][e]

[msg btl_support_08_845]
[s][vp 8 1 65535 1057 0 0]Oh, some rare loot![n][f 1 6 65534][e]

[msg btl_support_08_846]
[s][vp 8 1 65535 1058 0 0]How very generous![n][f 1 6 65534][e]

[msg btl_support_08_847]
[s][vp 8 1 65535 1059 0 0]That's decent.[n][f 1 6 65534][e]

[msg btl_support_08_848]
[s][vp 8 1 65535 1060 0 0]Well... Could be useful.[n][f 1 6 65534][e]

[msg btl_support_08_849]
[s][vp 8 1 65535 1061 0 0]We're not gonna do much with that.[n][f 1 6 65534][e]

[msg btl_support_08_850]
[s][vp 8 1 65535 1062 0 0]This item is... um, no comment![n][f 1 6 65534][e]

[msg btl_support_08_851]
[s][vp 8 1 65535 1063 0 0]It looks saaad. Be nice and just[n]give some basic, vague answers.[n][f 1 6 65534][e]

[msg btl_support_08_852]
[s][vp 8 1 65535 1064 0 0]It looks depressed. Don't trouble it[n]with more info than it needs.[n][f 1 6 65534][e]

[msg btl_support_08_853]
[s][vp 8 1 65535 1065 0 0]It sure is glum. Hey, please[n]remember, not everyone[n]likes to be "cheered up."[n][f 1 6 65534][e]

[msg btl_support_08_854]
[s][vp 8 1 65535 1066 0 0]It's happy. If you tell a joke,[n]they might play along.[n][f 1 6 65534][e]

[msg btl_support_08_855]
[s][vp 8 1 65535 1067 0 0]Oh cute, it's happy. Have some fun[n]when you talk to that one![n][f 1 6 65534][e]

[msg btl_support_08_856]
[s][vp 8 1 65535 1068 0 0]It looks so peppy, doesn't it?[n]Don't get too serious, or you'll[n]kill the mood.[n][f 1 6 65534][e]

[msg btl_support_08_857]
[s][vp 8 1 65535 1069 0 0]This one's got a temper. Just act[n]really serious; it should appreciate[n]that.[n][f 1 6 65534][e]

[msg btl_support_08_858]
[s][vp 8 1 65535 1070 0 0]That Shadow's no happy camper.[n]Be serious and don't make light[n]of stuff.[n][f 1 6 65534][e]

[msg btl_support_08_859]
[s][vp 8 1 65535 1071 0 0]This one's so angry... I think it[n]won't have any patience for[n]niceties.[n][f 1 6 65534][e]

[msg btl_support_08_860]
[s][vp 8 1 65535 1072 0 0]It looks so shy... Please be[n]extra-nice![n][f 1 6 65534][e]

[msg btl_support_08_861]
[s][vp 8 1 65535 1073 0 0]A shy Shadow... Say something[n]kind to make it feel at ease.[n][f 1 6 65534][e]

[msg btl_support_08_862]
[s][vp 8 1 65535 1074 0 0]This one's timid... Don't beat[n]around the bush—you'll[n]scare it even more![n][f 1 6 65534][e]

[msg btl_support_08_863]
[s][vp 8 1 65535 1075 0 0]Did Mona just reveal his feelings[n]about her?[n][f 1 6 65534][e]

[msg btl_support_08_864]
[s][vp 8 1 65535 1076 0 0]You sure were hungry![n][f 1 6 65534][e]

[msg btl_support_08_865]
[s][vp 8 1 65535 1077 0 0]Very beautiful![n][f 1 6 65534][e]

[msg btl_support_08_866]
[s][vp 8 1 65535 1078 0 0]Heheheh, I love that reference![n][f 1 6 65534][e]

[msg btl_support_08_867]
[s][vp 8 1 65535 1079 0 0]So hardcore![n][f 1 6 65534][e]

[msg btl_support_08_868]
[s][vp 8 1 65535 1080 0 0]That was a fancy KO![n][f 1 6 65534][e]

[msg btl_support_08_869]
[s][vp 8 1 65535 1081 0 0]Pretty crazy technique, but it[n]worked![n][f 1 6 65534][e]

[msg btl_support_08_870]
[s][vp 8 1 65535 1082 0 0]You'd get into the Platinum League[n]for that![n][f 1 6 65534][e]

[msg btl_support_08_871]
[s][vp 8 1 65535 1083 0 0][f 1 6 65534][e]

[msg btl_support_08_872]
[s][vp 8 1 65535 1084 0 0]That was awesome, you two![n][f 1 6 65534][e]

[msg btl_support_08_873]
[s][vp 8 1 65535 1085 0 0]Nice, Joker![n][f 1 6 65534][e]

[msg btl_support_08_874]
[s][vp 8 1 65535 1086 0 0]So this is Lavenza... Don't be[n]tricked by how she looks![n]Her power is enormous.[n][f 1 6 65534][e]

[msg btl_support_08_875]
[s][vp 8 1 65535 1087 0 0]Your only chance is to give[n]her everything you've got![n][f 1 6 65534][e]

[msg btl_support_08_876]
[s][vp 8 1 65535 1088 0 0]She changed her Persona![n][f 1 6 65534][e]

[msg btl_support_08_877]
[s][vp 8 1 65535 1089 0 0]And... her affinity changed, too?[n][f 1 6 65534][e]

[msg btl_support_08_878]
[s][vp 8 1 65535 1090 0 0]Guys, Lavenza's butting in![n]Don't hold back![n][f 1 6 65534][e]

[msg btl_support_08_879]
[s][vp 8 1 65535 1091 0 0]RESERVE[n][f 1 6 65534][e]

[msg btl_support_08_880]
[s][vp 8 1 65535 1092 0 0]RESERVE[n][f 1 6 65534][e]

[msg btl_support_08_881]
[s][vp 8 1 65535 1093 0 0]RESERVE[n][f 1 6 65534][e]

[msg btl_support_08_882]
[s][vp 8 1 65535 1094 0 0]RESERVE[n][f 1 6 65534][e]

[msg btl_support_08_883]
[s][vp 8 1 65535 1095 0 0]It's not enough! We gotta do[n]a lot more damage than this![n][f 1 6 65534][e]

[msg btl_support_08_884]
[s][vp 8 1 65535 1096 0 0]Keep it up, you have to distract him![n][f 1 6 65534][e]

[msg btl_support_08_885]
[s][vp 8 1 65535 1097 0 0]Almost there! Give him one more[n]good strike![n][f 1 6 65534][e]

[msg btl_support_08_886]
[s][vp 8 1 65535 1098 0 0]Wait, maybe you can stop[n]Kamoshida's attack if you[n]get the ball![n][f 1 6 65534][e]

[msg btl_support_08_887]
[s][vp 8 1 65535 1099 0 0]You gotta go for the ball again![n][f 1 6 65534][e]

[msg btl_support_08_888]
[s][vp 8 1 65535 1100 0 0]If you find the fake one's[n]weakness, you might get[n]a chance at the real one![n][f 1 6 65534][e]

[msg btl_support_08_889]
[s][vp 8 1 65535 1101 0 0]To get to Kaneshiro, you'll have to[n]get rid of his stupid goons first![n][f 1 6 65534][e]

[msg btl_support_08_890]
[s][vp 8 1 65535 1102 0 0]Shit! Okay... we just need to wait[n]for the right moment to attack...[n][f 1 6 65534][e]

[msg btl_support_08_891]
[s][vp 8 1 65535 1103 0 0]Don't stop![n][f 1 6 65534][e]

[msg btl_support_08_892]
[s][vp 8 1 65535 1104 0 0]RESERVE[n][f 1 6 65534][e]

[msg btl_support_08_893]
[s][vp 8 1 65535 1105 0 0]RESERVE[n][f 1 6 65534][e]

[msg btl_support_08_894]
[s][vp 8 1 65535 1106 0 0]It might not have a weakness![n]Maybe try making it sleepy?[n][f 1 6 65534][e]

[msg btl_support_08_895]
[s][vp 8 1 65535 1107 0 0]It doesn't seem to have a weakness.[n]Let's try making it dizzy![n][f 1 6 65534][e]

[msg btl_support_08_896]
[s][vp 8 1 65535 1108 0 0]No weaknesses!? Well... how about[n]we make it forget its skills?[n][f 1 6 65534][e]

[msg btl_support_08_897]
[s][vp 8 1 65535 1109 0 0]It doesn't have a weakness, but...[n]I think we could make it angry![n][f 1 6 65534][e]

[msg btl_support_08_898]
[s][vp 8 1 65535 1110 0 0]Well, if it has no weakness,[n]why not try brainwashing it?[n][f 1 6 65534][e]

[msg btl_support_08_899]
[s][vp 8 1 65535 1111 0 0]It has no weakness... our best[n]chance is to make it confused![n][f 1 6 65534][e]

[msg btl_support_08_900]
[s][vp 8 1 65535 1112 0 0]It has no physical weakness, so let's[n]use an emotional weapon: fear![n][f 1 6 65534][e]

[msg btl_support_08_901]
[s][vp 8 1 65535 1113 0 0]It has no weakness, but we can try[n]overwhelming it with despair![n][f 1 6 65534][e]

[msg btl_support_08_902]
[s][vp 8 1 65535 1114 0 0]There's a forgetful enemy that[n]would be especially vulnerable[n]to Electricity.[n][f 1 6 65534][e]

[msg btl_support_08_903]
[s][vp 8 1 65535 1115 0 0]Look at how angry it is! Hit it with[n]some Psychokinesis![n][f 1 6 65534][e]

[msg btl_support_08_904]
[s][vp 8 1 65535 1116 0 0]Now the enemy is just a[n]brainwashed drone! Use[n]Psychokinesis![n][f 1 6 65534][e]

[msg btl_support_08_905]
[s][vp 8 1 65535 1117 0 0]Look, there's an enemy that's[n]confused! Give it some[n]Psychokinesis![n][f 1 6 65534][e]

[msg btl_support_08_906]
[s][vp 8 1 65535 1118 0 0]Do you see that scared one?[n]Psychokinesis would be[n]perfect now.[n][f 1 6 65534][e]

[msg btl_support_08_907]
[s][vp 8 1 65535 1119 0 0]One enemy is in despair, so[n]Psychokinesis would be a[n]good move.[n][f 1 6 65534][e]

[msg btl_support_08_908]
[s][vp 8 1 65535 1120 0 0]I recommend attacking any[n]enemy who has a status ailment![n][f 1 6 65534][e]

[msg btl_support_08_909]
[s][vp 8 1 65535 1121 0 0]Joker, you're vulnerable! Quick,[n]use your special attack![n][f 1 6 65534][e]

[msg btl_support_08_910]
[s][vp 8 1 65535 1122 0 0]Listen, Joker's on the ground![n]Can anyone do one of those[n]real intense attacks?[n][f 1 6 65534][e]

[msg btl_support_08_911]
[s][vp 8 1 65535 1123 0 0]スカル、大丈夫か![n]ショータイムでリベンジだ![n][f 1 6 65534][e]

[msg btl_support_08_912]
[s][vp 8 1 65535 1124 0 0]ぐっ、まだまだ![n]ショータイムはこれからだぜ![n][f 1 6 65534][e]

[msg btl_support_08_913]
[s][vp 8 1 65535 1125 0 0]パンサー、大丈夫か![n]ショータイムでリベンジだ![n][f 1 6 65534][e]

[msg btl_support_08_914]
[s][vp 8 1 65535 1126 0 0]フォックス、大丈夫か![n]ショータイムでリベンジだ![n][f 1 6 65534][e]

[msg btl_support_08_915]
[s][vp 8 1 65535 1127 0 0]クイーン、大丈夫か![n]ショータイムでリベンジだ![n][f 1 6 65534][e]

[msg btl_support_08_916]
[s][vp 8 1 65535 1128 0 0]ノワール、大丈夫か![n]ショータイムでリベンジだ![n][f 1 6 65534][e]

[msg btl_support_08_917]
[s][vp 8 1 65535 1129 0 0]クロウ、大丈夫か![n]ショータイムでリベンジだ![n][f 1 6 65534][e]

[msg btl_support_08_918]
[s][vp 8 1 65535 1130 0 0]ヴァイオレット、大丈夫か![n]ショータイムでリベンジだ![n][f 1 6 65534][e]

[msg btl_support_08_919]
[s][vp 8 1 65535 1131 0 0]Oh no! You'll need to attack with[n]extra oomph to get out of this one![n][f 1 6 65534][e]

[msg btl_support_08_920]
[s][vp 8 1 65535 1132 0 0]RESERVE[n][f 1 6 65534][e]

[msg btl_support_08_921]
[s][vp 8 1 65535 1133 0 0]RESERVE[n][f 1 6 65534][e]

[msg btl_support_08_922]
[s][vp 8 1 65535 1134 0 0]Joker's in trouble! Let's get 'em, Fox![n][f 1 6 65534][e]

[msg btl_support_08_923]
[s][vp 8 1 65535 1135 0 0]All right, payback time![n][f 1 6 65534][e]

[msg btl_support_08_924]
[s][vp 8 1 65535 1136 0 0]You're gonna regret that! Won't they, Fox!?[n][f 1 6 65534][e]

[msg btl_support_08_925]
[s][vp 8 1 65535 1137 0 0]Raring to go, eh Fox!?[n][f 1 6 65534][e]

[msg btl_support_08_926]
[s][vp 8 1 65535 1138 0 0]You look pumped up! Let's do this![n][f 1 6 65534][e]

[msg btl_support_08_927]
[s][vp 8 1 65535 1139 0 0]Time for the finishing move![n][f 1 6 65534][e]

[msg btl_support_08_928]
[s][vp 8 1 65535 1140 0 0]Hey, that enemy's vulnerable![n][f 1 6 65534][e]

[msg btl_support_08_929]
[s][vp 8 1 65535 1141 0 0]Ready when you are, Fox![n][f 1 6 65534][e]

[msg btl_support_08_930]
[s][vp 8 1 65535 1142 0 0]Come on, we can do better, Fox![n][f 1 6 65534][e]

[msg btl_support_08_931]
[s][vp 8 1 65535 1143 0 0]Hell yeah! You and me, let's do this![n][f 1 6 65534][e]

[msg btl_support_08_932]
[s][vp 8 1 65535 1144 0 0]Fox! We'll get 'em for you![n][f 1 6 65534][e]

[msg btl_support_08_933]
[s][vp 8 1 65535 1145 0 0]RESERVE[n][f 1 6 65534][e]

[msg btl_support_08_934]
[s][vp 8 1 65535 1146 0 0]Joker's lookin' pretty bad![n]Let's show them, Queen![n][f 1 6 65534][e]

[msg btl_support_08_935]
[s][vp 8 1 65535 1147 0 0]All right, up and at 'em![n][f 1 6 65534][e]

[msg btl_support_08_936]
[s][vp 8 1 65535 1148 0 0]We can't let them get away with[n]doing that to one of us![n][f 1 6 65534][e]

[msg btl_support_08_937]
[s][vp 8 1 65535 1149 0 0]Whoa, Queen's burning![n][f 1 6 65534][e]

[msg btl_support_08_938]
[s][vp 8 1 65535 1150 0 0]You look like you're ready to rule![n][f 1 6 65534][e]

[msg btl_support_08_939]
[s][vp 8 1 65535 1151 0 0]I'll help you finish 'em off![n][f 1 6 65534][e]

[msg btl_support_08_940]
[s][vp 8 1 65535 1152 0 0]Yeah! That's how we like our[n]enemies—weak on defense![n][f 1 6 65534][e]

[msg btl_support_08_941]
[s][vp 8 1 65535 1153 0 0]I'm ready whenever you are![n][f 1 6 65534][e]

[msg btl_support_08_942]
[s][vp 8 1 65535 1154 0 0]I'll help you exact your revenge![n][f 1 6 65534][e]

[msg btl_support_08_943]
[s][vp 8 1 65535 1155 0 0]All right, let's kick some ass![n][f 1 6 65534][e]

[msg btl_support_08_944]
[s][vp 8 1 65535 1156 0 0]Whoa! She's gonna be really pissed![n][f 1 6 65534][e]

[msg btl_support_08_945]
[s][vp 8 1 65535 1157 0 0]RESERVE[n][f 1 6 65534][e]

[msg btl_support_08_946]
[s][vp 8 1 65535 1158 0 0]We can't let Joker die![n][f 1 6 65534][e]

[msg btl_support_08_947]
[s][vp 8 1 65535 1159 0 0]Yay, you're back! Now it's[n]showtime![n][f 1 6 65534][e]

[msg btl_support_08_948]
[s][vp 8 1 65535 1160 0 0]It's times like these when we need[n]to take revenge![n][f 1 6 65534][e]

[msg btl_support_08_949]
[s][vp 8 1 65535 1161 0 0]Panther's ready to pounce![n][f 1 6 65534][e]

[msg btl_support_08_950]
[s][vp 8 1 65535 1162 0 0]Panther's fired up![n][f 1 6 65534][e]

[msg btl_support_08_951]
[s][vp 8 1 65535 1163 0 0]Do us proud![n][f 1 6 65534][e]

[msg btl_support_08_952]
[s][vp 8 1 65535 1164 0 0]The enemy's defense is down![n][f 1 6 65534][e]

[msg btl_support_08_953]
[s][vp 8 1 65535 1165 0 0]Panther, this is all for you![n][f 1 6 65534][e]

[msg btl_support_08_954]
[s][vp 8 1 65535 1166 0 0]You're okay! How about we[n]kick some butt together!?[n][f 1 6 65534][e]

[msg btl_support_08_955]
[s][vp 8 1 65535 1167 0 0]Nice! Would you also accept[n]a rose bouquet from me?[n][f 1 6 65534][e]

[msg btl_support_08_956]
[s][vp 8 1 65535 1168 0 0]Are you okay, Panther!? They won't[n]get away with this![n][f 1 6 65534][e]

[msg btl_support_08_957]
[s][vp 8 1 65535 1169 0 0]RESERVE[n][f 1 6 65534][e]

[msg btl_support_08_958]
[s][vp 8 1 65535 1170 0 0]We can't let them take out Joker![n][f 1 6 65534][e]

[msg btl_support_08_959]
[s][vp 8 1 65535 1171 0 0]Fight back, Noir![n][f 1 6 65534][e]

[msg btl_support_08_960]
[s][vp 8 1 65535 1172 0 0]We gotta stand up for our friend![n][f 1 6 65534][e]

[msg btl_support_08_961]
[s][vp 8 1 65535 1173 0 0]Let's show them who the Phantom[n]Thieves really are![n][f 1 6 65534][e]

[msg btl_support_08_962]
[s][vp 8 1 65535 1174 0 0]Noir is seriously pumped![n][f 1 6 65534][e]

[msg btl_support_08_963]
[s][vp 8 1 65535 1175 0 0]Let's take it down together![n][f 1 6 65534][e]

[msg btl_support_08_964]
[s][vp 8 1 65535 1176 0 0]The enemy's off guard![n][f 1 6 65534][e]

[msg btl_support_08_965]
[s][vp 8 1 65535 1177 0 0]Now's our chance to show what[n]chemistry we have![n][f 1 6 65534][e]

[msg btl_support_08_966]
[s][vp 8 1 65535 1178 0 0]Noir, you're back up! You wanna[n]do our thing?[n][f 1 6 65534][e]

[msg btl_support_08_967]
[s][vp 8 1 65535 1179 0 0]Nice catch! Morgana Car is in gear[n]and ready to go![n][f 1 6 65534][e]

[msg btl_support_08_968]
[s][vp 8 1 65535 1180 0 0]Noir, are you gonna make it!?[n]We'll get them for this![n][f 1 6 65534][e]

[msg btl_support_08_969]
[s][vp 8 1 65535 1181 0 0]RESERVE[n][f 1 6 65534][e]

[msg btl_support_08_970]
[s][vp 8 1 65535 1182 0 0]Joker's in danger! Let's show 'em[n]what we think of that, Mona![n][f 1 6 65534][e]

[msg btl_support_08_971]
[s][vp 8 1 65535 1183 0 0]I'll help you get back at them, Mona![n][f 1 6 65534][e]

[msg btl_support_08_972]
[s][vp 8 1 65535 1184 0 0]I'm not going to stand by while[n]my friends get hurt![n][f 1 6 65534][e]

[msg btl_support_08_973]
[s][vp 8 1 65535 1185 0 0]Time for one of your big moves![n][f 1 6 65534][e]

[msg btl_support_08_974]
[s][vp 8 1 65535 1186 0 0]Mona's fully powered![n][f 1 6 65534][e]

[msg btl_support_08_975]
[s][vp 8 1 65535 1187 0 0]TIME TO FINISH THIS![n][f 1 6 65534][e]

[msg btl_support_08_976]
[s][vp 8 1 65535 1188 0 0]The enemy's weak; now's our[n]chance![n][f 1 6 65534][e]

[msg btl_support_08_977]
[s][vp 8 1 65535 1189 0 0]Let's show them what's what![n][f 1 6 65534][e]

[msg btl_support_08_978]
[s][vp 8 1 65535 1190 0 0]You want some help serving up[n]a cold dish of revenge?[n][f 1 6 65534][e]

[msg btl_support_08_979]
[s][vp 8 1 65535 1191 0 0]Good catch! Now attack 'em[n]with some style![n][f 1 6 65534][e]

[msg btl_support_08_980]
[s][vp 8 1 65535 1192 0 0]Mona, are you okay!? We'll get them[n]for that![n][f 1 6 65534][e]

[msg btl_support_08_981]
[s][vp 8 1 65535 1193 0 0]RESERVE[n][f 1 6 65534][e]

[msg btl_support_08_982]
[s][vp 8 1 65535 1194 0 0]You'll pay for what you did[n]to Joker![n][f 1 6 65534][e]

[msg btl_support_08_983]
[s][vp 8 1 65535 1195 0 0]Revenge will be ours, Fox![n][f 1 6 65534][e]

[msg btl_support_08_984]
[s][vp 8 1 65535 1196 0 0]Nobody hurts my friends![n][f 1 6 65534][e]

[msg btl_support_08_985]
[s][vp 8 1 65535 1197 0 0]Baton pass complete! Up next:[n]our powerful attack![n][f 1 6 65534][e]

[msg btl_support_08_986]
[s][vp 8 1 65535 1198 0 0]You're really fired up![n][f 1 6 65534][e]

[msg btl_support_08_987]
[s][vp 8 1 65535 1199 0 0]IT'S TIME TO END THIS![n][f 1 6 65534][e]

[msg btl_support_08_988]
[s][vp 8 1 65535 1200 0 0]The enemy's guard is down.[n]Now's our chance![n][f 1 6 65534][e]

[msg btl_support_08_989]
[s][vp 8 1 65535 1201 0 0]Let's finish this beautifully,[n]just the way you like![n][f 1 6 65534][e]

[msg btl_support_08_990]
[s][vp 8 1 65535 1202 0 0]Let me help you get some payback![n][f 1 6 65534][e]

[msg btl_support_08_991]
[s][vp 8 1 65535 1203 0 0]Nice! Wanna go for our big attack?[n][f 1 6 65534][e]

[msg btl_support_08_992]
[s][vp 8 1 65535 1204 0 0]Fox! Let me help![n][f 1 6 65534][e]

[msg btl_support_08_993]
[s][vp 8 1 65535 1205 0 0]RESERVE[n][f 1 6 65534][e]

[msg btl_support_08_994]
[s][vp 8 1 65535 1206 0 0]We must protect Joker![n][f 1 6 65534][e]

[msg btl_support_08_995]
[s][vp 8 1 65535 1207 0 0]Allow me to assist you in your[n]vengeance, Skull.[n][f 1 6 65534][e]

[msg btl_support_08_996]
[s][vp 8 1 65535 1208 0 0]In the name of our fallen comrade![n][f 1 6 65534][e]

[msg btl_support_08_997]
[s][vp 8 1 65535 1209 0 0]Now's our chance for a glorious[n]duet![n][f 1 6 65534][e]

[msg btl_support_08_998]
[s][vp 8 1 65535 1210 0 0]Let's show them some real power![n][f 1 6 65534][e]

[msg btl_support_08_999]
[s][vp 8 1 65535 1211 0 0]Time for a lovely coup de grâce![n][f 1 6 65534][e]

[msg btl_support_08_1000]
[s][vp 8 1 65535 1212 0 0]Ah, a gap in the enemy's armor![n][f 1 6 65534][e]

[msg btl_support_08_1001]
[s][vp 8 1 65535 1213 0 0]Let's show them something truly[n]breathtaking, Skull.[n][f 1 6 65534][e]

[msg btl_support_08_1002]
[s][vp 8 1 65535 1214 0 0]Should the two of us take the stage?[n][f 1 6 65534][e]

[msg btl_support_08_1003]
[s][vp 8 1 65535 1215 0 0]Perfect catch. Now, let's put on[n]a show...[n][f 1 6 65534][e]

[msg btl_support_08_1004]
[s][vp 8 1 65535 1216 0 0]Skull, you're too talented to[n]die here![n][f 1 6 65534][e]

[msg btl_support_08_1005]
[s][vp 8 1 65535 1217 0 0]RESERVE[n][f 1 6 65534][e]

[msg btl_support_08_1006]
[s][vp 8 1 65535 1218 0 0]No, we will not abide Joker's death![n][f 1 6 65534][e]

[msg btl_support_08_1007]
[s][vp 8 1 65535 1219 0 0]Panther, I will assist in any revenge[n]you wish to visit upon them![n][f 1 6 65534][e]

[msg btl_support_08_1008]
[s][vp 8 1 65535 1220 0 0]This setback will feed our[n]determination![n][f 1 6 65534][e]

[msg btl_support_08_1009]
[s][vp 8 1 65535 1221 0 0]Let's do something to earn[n]applause![n][f 1 6 65534][e]

[msg btl_support_08_1010]
[s][vp 8 1 65535 1222 0 0]Reveal to them your power,[n]Panther![n][f 1 6 65534][e]

[msg btl_support_08_1011]
[s][vp 8 1 65535 1223 0 0]The final blow should be[n]a work of art.[n][f 1 6 65534][e]

[msg btl_support_08_1012]
[s][vp 8 1 65535 1224 0 0]An opening in the enemy's defense![n][f 1 6 65534][e]

[msg btl_support_08_1013]
[s][vp 8 1 65535 1225 0 0]Prepare to see the pinnacle[n]of beauty![n][f 1 6 65534][e]

[msg btl_support_08_1014]
[s][vp 8 1 65535 1226 0 0]Well done! Time for your encore![n][f 1 6 65534][e]

[msg btl_support_08_1015]
[s][vp 8 1 65535 1227 0 0]The game is just beginning![n][f 1 6 65534][e]

[msg btl_support_08_1016]
[s][vp 8 1 65535 1228 0 0]Panther! I'll help you fight back![n][f 1 6 65534][e]

[msg btl_support_08_1017]
[s][vp 8 1 65535 1229 0 0]RESERVE[n][f 1 6 65534][e]

[msg btl_support_08_1018]
[s][vp 8 1 65535 1230 0 0]Are we just going to let Joker die?[n][f 1 6 65534][e]

[msg btl_support_08_1019]
[s][vp 8 1 65535 1231 0 0]Skull, let's do to them what they[n]did to us! Twofold![n][f 1 6 65534][e]

[msg btl_support_08_1020]
[s][vp 8 1 65535 1232 0 0]We need retribution![n][f 1 6 65534][e]

[msg btl_support_08_1021]
[s][vp 8 1 65535 1233 0 0]You certainly look eager, Skull![n][f 1 6 65534][e]

[msg btl_support_08_1022]
[s][vp 8 1 65535 1234 0 0]Wow Skull, you're charged up![n][f 1 6 65534][e]

[msg btl_support_08_1023]
[s][vp 8 1 65535 1235 0 0]Leave the rest to me![n][f 1 6 65534][e]

[msg btl_support_08_1024]
[s][vp 8 1 65535 1236 0 0]Now's our moment![n][f 1 6 65534][e]

[msg btl_support_08_1025]
[s][vp 8 1 65535 1237 0 0]Let's show 'em what we're[n]made of![n][f 1 6 65534][e]

[msg btl_support_08_1026]
[s][vp 8 1 65535 1238 0 0]Nice recovery! I'm poised for action![n][f 1 6 65534][e]

[msg btl_support_08_1027]
[s][vp 8 1 65535 1239 0 0]Excellent! You think we should[n]try our attack together?[n][f 1 6 65534][e]

[msg btl_support_08_1028]
[s][vp 8 1 65535 1240 0 0]Hold on, Skull! We'll overcome[n]this together![n][f 1 6 65534][e]

[msg btl_support_08_1029]
[s][vp 8 1 65535 1241 0 0]RESERVE[n][f 1 6 65534][e]

[msg btl_support_08_1030]
[s][vp 8 1 65535 1242 0 0]Don't worry, Joker![n][f 1 6 65534][e]

[msg btl_support_08_1031]
[s][vp 8 1 65535 1243 0 0]Let's both teach them a lesson![n][f 1 6 65534][e]

[msg btl_support_08_1032]
[s][vp 8 1 65535 1244 0 0]When something bad happens,[n]let's remember the power inside[n]us![n][f 1 6 65534][e]

[msg btl_support_08_1033]
[s][vp 8 1 65535 1245 0 0]Everyone's counting on you![n][f 1 6 65534][e]

[msg btl_support_08_1034]
[s][vp 8 1 65535 1246 0 0]Hey, you're really strong right now![n][f 1 6 65534][e]

[msg btl_support_08_1035]
[s][vp 8 1 65535 1247 0 0]We ought to finish this![n][f 1 6 65534][e]

[msg btl_support_08_1036]
[s][vp 8 1 65535 1248 0 0]There's our opportunity, Noir![n][f 1 6 65534][e]

[msg btl_support_08_1037]
[s][vp 8 1 65535 1249 0 0]We'll make a great team![n][f 1 6 65534][e]

[msg btl_support_08_1038]
[s][vp 8 1 65535 1250 0 0]Okay, I'm ready to help![n][f 1 6 65534][e]

[msg btl_support_08_1039]
[s][vp 8 1 65535 1251 0 0]Let's corner them together![n][f 1 6 65534][e]

[msg btl_support_08_1040]
[s][vp 8 1 65535 1252 0 0]Hold on, Noir! We're going to fight[n]harder![n][f 1 6 65534][e]

[msg btl_support_08_1041]
[s][vp 8 1 65535 1253 0 0]RESERVE[n][f 1 6 65534][e]

[msg btl_support_08_1042]
[s][vp 8 1 65535 1254 0 0]Joker's pain is our pain![n][f 1 6 65534][e]

[msg btl_support_08_1043]
[s][vp 8 1 65535 1255 0 0]Let's give them hell to pay![n][f 1 6 65534][e]

[msg btl_support_08_1044]
[s][vp 8 1 65535 1256 0 0]We'll get through this together![n][f 1 6 65534][e]

[msg btl_support_08_1045]
[s][vp 8 1 65535 1257 0 0]Let's go, team![n][f 1 6 65534][e]

[msg btl_support_08_1046]
[s][vp 8 1 65535 1258 0 0]Mona's really feeling it...[n]I'm inspired![n][f 1 6 65534][e]

[msg btl_support_08_1047]
[s][vp 8 1 65535 1259 0 0]It's time for the grand finale![n][f 1 6 65534][e]

[msg btl_support_08_1048]
[s][vp 8 1 65535 1260 0 0]The enemy's vulnerable; perfect[n]timing for us![n][f 1 6 65534][e]

[msg btl_support_08_1049]
[s][vp 8 1 65535 1261 0 0]Ready to launch![n][f 1 6 65534][e]

[msg btl_support_08_1050]
[s][vp 8 1 65535 1262 0 0]We've still got a lot of fight in us![n][f 1 6 65534][e]

[msg btl_support_08_1051]
[s][vp 8 1 65535 1263 0 0]Nice catch! I'll get ready![n][f 1 6 65534][e]

[msg btl_support_08_1052]
[s][vp 8 1 65535 1264 0 0]If you insist on hurting Mona,[n]I hope you know what that[n]gets you.[n][f 1 6 65534][e]

[msg btl_support_08_1053]
[s][vp 8 1 65535 1265 0 0]RESERVE[n][f 1 6 65534][e]

[msg btl_support_08_1054]
[s][vp 8 1 65535 1266 0 0]Quick, before they get Joker![n][f 1 6 65534][e]

[msg btl_support_08_1055]
[s][vp 8 1 65535 1267 0 0]You're back in! Let's get even[n]with them![n][f 1 6 65534][e]

[msg btl_support_08_1056]
[s][vp 8 1 65535 1268 0 0]We have to turn this around![n][f 1 6 65534][e]

[msg btl_support_08_1057]
[s][vp 8 1 65535 1269 0 0]Nice! Let's go for it, the two of us![n][f 1 6 65534][e]

[msg btl_support_08_1058]
[s][vp 8 1 65535 1270 0 0]Ooh, power's coursing through[n]Queen![n][f 1 6 65534][e]

[msg btl_support_08_1059]
[s][vp 8 1 65535 1271 0 0]We can end this quickly![n][f 1 6 65534][e]

[msg btl_support_08_1060]
[s][vp 8 1 65535 1272 0 0]This is where we come in![n][f 1 6 65534][e]

[msg btl_support_08_1061]
[s][vp 8 1 65535 1273 0 0]We got this![n][f 1 6 65534][e]

[msg btl_support_08_1062]
[s][vp 8 1 65535 1274 0 0]Don't sweat it, Queen![n][f 1 6 65534][e]

[msg btl_support_08_1063]
[s][vp 8 1 65535 1275 0 0]Let's keep it up![n][f 1 6 65534][e]

[msg btl_support_08_1064]
[s][vp 8 1 65535 1276 0 0]Queen, let this fuel your desire[n]to win![n][f 1 6 65534][e]

[msg btl_support_08_1065]
[s][vp 8 1 65535 1277 0 0]RESERVE[n][f 1 6 65534][e]

[msg btl_support_08_1066]
[s][vp 8 1 65535 1278 0 0]What's going on with you!?[n][f 1 6 65534][e]

[msg btl_support_08_1067]
[s][vp 8 1 65535 1279 0 0]You'll pay for this with your life![n][f 1 6 65534][e]

[msg btl_support_08_1068]
[s][vp 8 1 65535 1280 0 0]We must repay blood with blood...[n][f 1 6 65534][e]

[msg btl_support_08_1069]
[s][vp 8 1 65535 1281 0 0]Let's do this, Joker...[n][f 1 6 65534][e]

[msg btl_support_08_1070]
[s][vp 8 1 65535 1282 0 0]I'm getting a warm, tingly feeling[n]from all this power![n][f 1 6 65534][e]

[msg btl_support_08_1071]
[s][vp 8 1 65535 1283 0 0]I'm going to make its last moments[n]on Earth its most painful...[n][f 1 6 65534][e]

[msg btl_support_08_1072]
[s][vp 8 1 65535 1284 0 0]They're wide open; let's slaughter[n]'em![n][f 1 6 65534][e]

[msg btl_support_08_1073]
[s][vp 8 1 65535 1285 0 0]Working together means extra pain[n]for them![n][f 1 6 65534][e]

[msg btl_support_08_1074]
[s][vp 8 1 65535 1286 0 0]RESERVE[n][f 1 6 65534][e]

[msg btl_support_08_1075]
[s][vp 8 1 65535 1287 0 0]RESERVE[n][f 1 6 65534][e]

[msg btl_support_08_1076]
[s][vp 8 1 65535 1288 0 0]Joker-senpai, are you all right!?[n][f 1 6 65534][e]

[msg btl_support_08_1077]
[s][vp 8 1 65535 1289 0 0]I won't give in! Let's attack[n]together, Joker-senpai![n][f 1 6 65534][e]

[msg btl_support_08_1078]
[s][vp 8 1 65535 1290 0 0]No one should die in vain...[n][f 1 6 65534][e]

[msg btl_support_08_1079]
[s][vp 8 1 65535 1291 0 0]Everyone is counting on me![n][f 1 6 65534][e]

[msg btl_support_08_1080]
[s][vp 8 1 65535 1292 0 0]Hey, we should do something[n]while I have all this power![n][f 1 6 65534][e]

[msg btl_support_08_1081]
[s][vp 8 1 65535 1293 0 0]Just a little more and we're done![n][f 1 6 65534][e]

[msg btl_support_08_1082]
[s][vp 8 1 65535 1294 0 0]Let's go now, since its defense[n]is down![n][f 1 6 65534][e]

[msg btl_support_08_1083]
[s][vp 8 1 65535 1295 0 0]Let's dance![n][f 1 6 65534][e]

[msg btl_support_08_1084]
[s][vp 8 1 65535 1296 0 0]RESERVE[n][f 1 6 65534][e]

[msg btl_support_08_1085]
[s][vp 8 1 65535 1297 0 0]RESERVE[n][f 1 6 65534][e]

[msg btl_support_08_1086]
[s][vp 8 1 65535 1298 0 0]You will face this enemy now.[n][f 1 6 65534][e]

[msg btl_support_08_1087]
[s][vp 8 1 65535 1299 0 0]Hm, how will you fare against[n]this foe?[n][f 1 6 65534][e]

[msg btl_support_08_1088]
[s][vp 8 1 65535 1300 0 0]This will be the final battle.[n][f 1 6 65534][e]

[msg btl_support_08_1089]
[s][vp 8 1 65535 1301 0 0]You rose to the challenge.[n][f 1 6 65534][e]

[msg btl_support_08_1090]
[s][vp 8 1 65535 1302 0 0]I see...[n][f 1 6 65534][e]

[msg btl_support_08_1091]
[s][vp 8 1 65535 1303 0 0]A cunning attack.[n][f 1 6 65534][e]

[msg btl_support_08_1092]
[s][vp 8 1 65535 1304 0 0]Such phenomenal teamwork.[n][f 1 6 65534][e]

[msg btl_support_08_1093]
[s][vp 8 1 65535 1305 0 0]Well-conceived and well-executed.[n][f 1 6 65534][e]

[msg btl_support_08_1094]
[s][vp 8 1 65535 1306 0 0]Now you're just showing off.[n][f 1 6 65534][e]

[msg btl_support_08_1095]
[s][vp 8 1 65535 1307 0 0]All gone in one fell swoop![n][f 1 6 65534][e]

[msg btl_support_08_1096]
[s][vp 8 1 65535 1308 0 0]Such a lovely—and destructive—[n]explosion.[n][f 1 6 65534][e]

[msg btl_support_08_1097]
[s][vp 8 1 65535 1309 0 0]This is...[n][f 1 6 65534][e]

[msg btl_support_08_1098]
[s][vp 8 1 65535 1310 0 0]A resounding victory.[n][f 1 6 65534][e]

[msg btl_support_08_1099]
[s][vp 8 1 65535 1311 0 0]Mission complete.[n][f 1 6 65534][e]

[msg btl_support_08_1100]
[s][vp 8 1 65535 1312 0 0]Hm, well at least you eked out[n]victories in every battle...[n][f 1 6 65534][e]

[msg btl_support_08_1101]
[s][vp 8 1 65535 1313 0 0]Please come back sometime.[n][f 1 6 65534][e]

[msg btl_support_08_1102]
[s][vp 8 1 65535 1314 0 0]A spectacular result for sure.[n][f 1 6 65534][e]

[msg btl_support_08_1103]
[s][vp 8 1 65535 1315 0 0]Challenge completed with a result[n]to be proud of.[n][f 1 6 65534][e]

[msg btl_support_08_1104]
[s][vp 8 1 65535 1316 0 0]You have met the minimum[n]requirements.[n][f 1 6 65534][e]

[msg btl_support_08_1105]
[s][vp 8 1 65535 1317 0 0]Can you defeat an enemy of this[n]nature?[n][f 1 6 65534][e]

[msg btl_support_08_1106]
[s][vp 8 1 65535 1318 0 0]Astounding.[n][f 1 6 65534][e]

[msg btl_support_08_1107]
[s][vp 8 1 65535 1319 0 0]RESERVE[n][f 1 6 65534][e]

[msg btl_support_08_1108]
[s][vp 8 1 65535 1320 0 0]RESERVE[n][f 1 6 65534][e]

[msg btl_support_08_1109]
[s][vp 8 1 65535 1321 0 0]Next up![n][f 1 6 65534][e]

[msg btl_support_08_1110]
[s][vp 8 1 65535 1322 0 0]Well, how do you measure up[n]against these guys!?[n][f 1 6 65534][e]

[msg btl_support_08_1111]
[s][vp 8 1 65535 1323 0 0]Last fight! You going to make it?[n][f 1 6 65534][e]

[msg btl_support_08_1112]
[s][vp 8 1 65535 1324 0 0]Hmph! Not bad.[n][f 1 6 65534][e]

[msg btl_support_08_1113]
[s][vp 8 1 65535 1325 0 0]Oho...[n][f 1 6 65534][e]

[msg btl_support_08_1114]
[s][vp 8 1 65535 1326 0 0]Perhaps I underestimated you,[n]Inmate.[n][f 1 6 65534][e]

[msg btl_support_08_1115]
[s][vp 8 1 65535 1327 0 0]I'm positively stunned.[n][f 1 6 65534][e]

[msg btl_support_08_1116]
[s][vp 8 1 65535 1328 0 0]Quite an accomplishment for[n]a lowly Inmate...[n][f 1 6 65534][e]

[msg btl_support_08_1117]
[s][vp 8 1 65535 1329 0 0]I don't believe it![n][f 1 6 65534][e]

[msg btl_support_08_1118]
[s][vp 8 1 65535 1330 0 0]Hm, you ARE good...[n][f 1 6 65534][e]

[msg btl_support_08_1119]
[s][vp 8 1 65535 1331 0 0]Finally! Some entertainment![n][f 1 6 65534][e]

[msg btl_support_08_1120]
[s][vp 8 1 65535 1332 0 0]Aah...[n][f 1 6 65534][e]

[msg btl_support_08_1121]
[s][vp 8 1 65535 1333 0 0]An excellent job, I must admit.[n][f 1 6 65534][e]

[msg btl_support_08_1122]
[s][vp 8 1 65535 1334 0 0]Not the worst thing I've seen.[n][f 1 6 65534][e]

[msg btl_support_08_1123]
[s][vp 8 1 65535 1335 0 0]You squeaked by.[n][f 1 6 65534][e]

[msg btl_support_08_1124]
[s][vp 8 1 65535 1336 0 0]Try again when you're not so scared.[n][f 1 6 65534][e]

[msg btl_support_08_1125]
[s][vp 8 1 65535 1337 0 0]I'm surprised, Inmate![n][f 1 6 65534][e]

[msg btl_support_08_1126]
[s][vp 8 1 65535 1338 0 0]Could've been better, but I'll[n]throw you a bone.[n][f 1 6 65534][e]

[msg btl_support_08_1127]
[s][vp 8 1 65535 1339 0 0]Well, I guess you pass.[n][f 1 6 65534][e]

[msg btl_support_08_1128]
[s][vp 8 1 65535 1340 0 0]Ah, but can you beat this enemy?[n][f 1 6 65534][e]

[msg btl_support_08_1129]
[s][vp 8 1 65535 1341 0 0]Okay, you're better than I thought![n][f 1 6 65534][e]

[msg btl_support_08_1130]
[s][vp 8 1 65535 1342 0 0]RESERVE[n][f 1 6 65534][e]

[msg btl_support_08_1131]
[s][vp 8 1 65535 1343 0 0]RESERVE[n][f 1 6 65534][e]

[msg btl_support_08_1132]
[s][vp 8 1 65535 1344 0 0]Let us see how you fare against[n]this enemy.[n][f 1 6 65534][e]

[msg btl_support_08_1133]
[s][vp 8 1 65535 1345 0 0]Now show me what you can[n]really do![n][f 1 6 65534][e]

[msg btl_support_08_1134]
[s][vp 8 1 65535 1346 0 0]Now for the final battle.[n][f 1 6 65534][e]

[msg btl_support_08_1135]
[s][vp 8 1 65535 1347 0 0]Impressive.[n][f 1 6 65534][e]

[msg btl_support_08_1136]
[s][vp 8 1 65535 1348 0 0]Most excellent.[n][f 1 6 65534][e]

[msg btl_support_08_1137]
[s][vp 8 1 65535 1349 0 0]Splendid![n][f 1 6 65534][e]

[msg btl_support_08_1138]
[s][vp 8 1 65535 1350 0 0]What vigor you display![n][f 1 6 65534][e]

[msg btl_support_08_1139]
[s][vp 8 1 65535 1351 0 0]Marvelous![n][f 1 6 65534][e]

[msg btl_support_08_1140]
[s][vp 8 1 65535 1352 0 0]Remarkable.[n][f 1 6 65534][e]

[msg btl_support_08_1141]
[s][vp 8 1 65535 1353 0 0]You're actually quite skilled![n][f 1 6 65534][e]

[msg btl_support_08_1142]
[s][vp 8 1 65535 1354 0 0]A total annihilation![n][f 1 6 65534][e]

[msg btl_support_08_1143]
[s][vp 8 1 65535 1355 0 0]My, oh my![n][f 1 6 65534][e]

[msg btl_support_08_1144]
[s][vp 8 1 65535 1356 0 0]Congratulations![n][f 1 6 65534][e]

[msg btl_support_08_1145]
[s][vp 8 1 65535 1357 0 0]Not the best, but certainly not[n]the worst.[n][f 1 6 65534][e]

[msg btl_support_08_1146]
[s][vp 8 1 65535 1358 0 0]I see...[n][f 1 6 65534][e]

[msg btl_support_08_1147]
[s][vp 8 1 65535 1359 0 0]Please try again sometime.[n][f 1 6 65534][e]

[msg btl_support_08_1148]
[s][vp 8 1 65535 1360 0 0]That's my Trickster![n][f 1 6 65534][e]

[msg btl_support_08_1149]
[s][vp 8 1 65535 1361 0 0]I was right to expect great things[n]of you.[n][f 1 6 65534][e]

[msg btl_support_08_1150]
[s][vp 8 1 65535 1362 0 0]An impressive result, indeed.[n][f 1 6 65534][e]

[msg btl_support_08_1151]
[s][vp 8 1 65535 1363 0 0]Will you be able to overcome[n]this foe?[n][f 1 6 65534][e]

[msg btl_support_08_1152]
[s][vp 8 1 65535 1364 0 0]I knew you could do it, my Trickster![n][f 1 6 65534][e]

[msg btl_support_08_1153]
[s][vp 8 1 65535 1365 0 0]RESERVE[n][f 1 6 65534][e]

[msg btl_support_08_1154]
[s][vp 8 1 65535 1366 0 0]RESERVE[n][f 1 6 65534][e]

[msg btl_support_08_1155]
[s][vp 8 1 65535 1367 0 0]Get them! Don't let them blow up![n][f 1 6 65534][e]

[msg btl_support_08_1156]
[s][vp 8 1 65535 1368 0 0]It's not the real one, just hurry[n]and smash it![n][f 1 6 65534][e]

[msg btl_support_08_1157]
[s][vp 8 1 65535 1369 0 0]So many, and they just keep[n]coming... gotta destroy 'em all![n][f 1 6 65534][e]

[msg btl_support_08_1158]
[s][vp 8 1 65535 1370 0 0]They're honing in on just one[n]person! Be careful![n][f 1 6 65534][e]

[msg btl_support_08_1159]
[s][vp 8 1 65535 1371 0 0]She's going to attack with Fire![n]Watch out![n][f 1 6 65534][e]

[msg btl_support_08_1160]
[s][vp 8 1 65535 1372 0 0]She's gearing up for an Ice attack...[n]Be careful![n][f 1 6 65534][e]

[msg btl_support_08_1161]
[s][vp 8 1 65535 1373 0 0]She's going to come at us with[n]Wind... Stand firm![n][f 1 6 65534][e]

[msg btl_support_08_1162]
[s][vp 8 1 65535 1374 0 0]Agh! I think she's about to strike us[n]with Electricity![n][f 1 6 65534][e]

[msg btl_support_08_1163]
[s][vp 8 1 65535 1375 0 0]She's gonna go Nuclear on us![n]Get ready![n][f 1 6 65534][e]

[msg btl_support_08_1164]
[s][vp 8 1 65535 1376 0 0]She might be about to use[n]Psychokinesis...[n][f 1 6 65534][e]

[msg btl_support_08_1165]
[s][vp 8 1 65535 1377 0 0]I think she's got something new up[n]her sleeve... Stay alert![n][f 1 6 65534][e]

[msg btl_support_08_1166]
[s][vp 8 1 65535 1378 0 0]I think she's going to use a Curse![n][f 1 6 65534][e]

[msg btl_support_08_1167]
[s][vp 8 1 65535 1379 0 0]Now's your chance! Attack like[n]there's no tomorrow![n][f 1 6 65534][e]

[msg btl_support_08_1168]
[s][vp 8 1 65535 1380 0 0]This benefits us, too![n]Keep attacking![n][f 1 6 65534][e]

[msg btl_support_08_1169]
[s][vp 8 1 65535 1381 0 0]Wh-What happened!?[n][f 1 6 65534][e]

[msg btl_support_08_1170]
[s][vp 8 1 65535 1382 0 0]Are you all right, Joker!?[n][f 1 6 65534][e]

[msg btl_support_08_1171]
[s][vp 8 1 65535 1383 0 0]This is bad... Come on, guys![n][f 1 6 65534][e]

[msg btl_support_08_1172]
[s][vp 8 1 65535 1384 0 0]We've come so far...[n]We have to do something![n][f 1 6 65534][e]

[msg btl_support_08_1173]
[s][vp 8 1 65535 1385 0 0]Joker... Please, don't lose![n][f 1 6 65534][e]

[msg btl_support_08_1174]
[s][vp 8 1 65535 1386 0 0]Can we still attack him somehow?[n][f 1 6 65534][e]

[msg btl_support_08_1175]
[s][vp 8 1 65535 1387 0 0]Dammit! ...Well, let's just do[n]what we can![n][f 1 6 65534][e]

[msg btl_support_08_1176]
[s][vp 8 1 65535 1388 0 0]Okay, nobody freak out, but...[n]it just grew more legs.[n][f 1 6 65534][e]

[msg btl_support_08_1177]
[s][vp 8 1 65535 1389 0 0]Oh no, it's getting stronger![n]Defense, defense![n][f 1 6 65534][e]

[msg btl_support_08_1178]
[s][vp 8 1 65535 1390 0 0]Watch out, one of you's being[n]targeted![n][f 1 6 65534][e]

[msg btl_support_08_1179]
[s][vp 8 1 65535 1391 0 0]Everyone, please don't give up![n]This is NOT where you die![n][f 1 6 65534][e]

[msg btl_support_08_1180]
[s][vp 8 1 65535 1392 0 0]It's getting weaker! Keep going![n][f 1 6 65534][e]

[msg btl_support_08_1181]
[s][vp 8 1 65535 1393 0 0]Finish him, Joker![n][f 1 6 65534][e]

[msg btl_support_08_1182]
[s][vp 8 1 65535 1394 0 0]He's about to get way stronger...[n]but you've nearly won, so keep[n]going![n][f 1 6 65534][e]

[msg btl_support_08_1183]
[s][vp 8 1 65535 1395 0 0]Now's our chance! Go, go, go![n][f 1 6 65534][e]

[msg btl_support_08_1184]
[s][vp 8 1 65535 1396 0 0]You can't lose here, not when[n]we've come so far![n][f 1 6 65534][e]

[msg btl_support_08_1185]
[s][vp 8 1 65535 1397 0 0]RESERVE[n][f 1 6 65534][e]

[msg btl_support_08_1186]
[s][vp 8 1 65535 1398 0 0]Who the heck is this guy!?[n][f 1 6 65534][e]

[msg btl_support_08_1187]
[s][vp 8 1 65535 1399 0 0]He's kind of like Joker, I think...?[n][f 1 6 65534][e]

[msg btl_support_08_1188]
[s][vp 8 1 65535 1400 0 0]Never mind, just don't lose! I'll do[n]everything I can to help![n][f 1 6 65534][e]

[msg btl_support_06_638]
[s][vp 8 1 65535 638 0 0]If you pass the baton, you can hit[n]the foes' weaknesses![n][f 1 6 65534][e]

[msg btl_support_06_639]
[s][vp 8 1 65535 639 0 0]We know their weak points now![n]Pass the baton![n][f 1 6 65534][e]

[msg btl_support_06_640]
[s][vp 8 1 65535 640 0 0]We can hit their weaknesses![n]Pass the baton, now![n][f 1 6 65534][e]

[msg btl_support_06_641]
[s][vp 8 1 65535 641 0 0]This is our chance! Pass the baton![n][f 1 6 65534][e]

[msg btl_support_06_642]
[s][vp 8 1 65535 642 0 0]We've almost won! Pass the baton[n]and switch attackers![n][f 1 6 65534][e]

[msg btl_support_06_643]
[s][vp 8 1 65535 643 0 0]Be careful! They're about to attack![n][f 1 6 65534][e]

[msg btl_support_06_644]
[s][vp 8 1 65535 644 0 0]The opponent is going to attack![n]Recover your health![n][f 1 6 65534][e]

[msg btl_support_06_645]
[s][vp 8 1 65535 645 0 0]Heal yourself quickly![n]They're about to retaliate![n][f 1 6 65534][e]

[msg btl_support_06_646]
[s][vp 8 1 65535 646 0 0]They're about to make their move![n]You need to heal![n][f 1 6 65534][e]

[msg btl_support_06_647]
[s][vp 8 1 65535 647 0 0]Watch your health! They're coming![n][f 1 6 65534][e]

[msg btl_support_06_648]
[s][vp 8 1 65535 648 0 0]An enemy's burning! Follow up[n]with Wind to deal major damage![n][f 1 6 65534][e]

[msg btl_support_06_649]
[s][vp 8 1 65535 649 0 0]An enemy's frozen! Let's shatter it[n]in one strike![n][f 1 6 65534][e]

[msg btl_support_06_650]
[s][vp 8 1 65535 650 0 0]The enemy is electrified! Melee[n]may work, but you might get[n]shocked![n][f 1 6 65534][e]

[msg btl_support_06_651]
[s][vp 8 1 65535 651 0 0]An enemy has fallen asleep![n]Now's our chance to strike![n][f 1 6 65534][e]

[msg btl_support_06_652]
[s][vp 8 1 65535 652 0 0]The enemy's dizzy! Strike now,[n]and knock it down![n][f 1 6 65534][e]

[msg btl_support_06_653]
[s][vp 8 1 65535 653 0 0]The opponent is strong! Don't do[n]anything reckless![n][f 1 6 65534][e]

[msg btl_support_06_654]
[s][vp 8 1 65535 654 0 0]It's strong, but weak to Physical[n]blows. We just need to use that.[n][f 1 6 65534][e]

[msg btl_support_06_655]
[s][vp 8 1 65535 655 0 0]It's powerful, but guns should shut[n]it down. Just watch your ammo![n][f 1 6 65534][e]

[msg btl_support_06_656]
[s][vp 8 1 65535 656 0 0]It looks vicious... We should go[n]directly for its weakness: Fire.[n][f 1 6 65534][e]

[msg btl_support_06_657]
[s][vp 8 1 65535 657 0 0]It's powerful! You'll want[n]fierce Ice attacks![n][f 1 6 65534][e]

[msg btl_support_06_658]
[s][vp 8 1 65535 658 0 0]The enemy is strong! Let's aim for[n]its Wind weakness![n][f 1 6 65534][e]

[msg btl_support_06_659]
[s][vp 8 1 65535 659 0 0]Its weakness is Electricity. If we can[n]use that, it'll go down fast![n][f 1 6 65534][e]

[msg btl_support_06_660]
[s][vp 8 1 65535 660 0 0]The enemy is strong! Defeat it[n]quickly with Bless attacks![n][f 1 6 65534][e]

[msg btl_support_06_661]
[s][vp 8 1 65535 661 0 0]It's a powerful enemy! Finish it[n]quickly with Curse attacks![n][f 1 6 65534][e]

[msg btl_support_06_662]
[s][vp 8 1 65535 662 0 0]They're tough, but weak to[n]Nuclear. You know what to do,[n]right?[n][f 1 6 65534][e]

[msg btl_support_06_663]
[s][vp 8 1 65535 663 0 0]A vicious foe! Attack with[n]Psychokinetic skills![n][f 1 6 65534][e]

[msg btl_support_06_664]
[s][vp 8 1 65535 664 0 0]It's strong AND immune to Physical[n]strikes!? Brute force won't work![n][f 1 6 65534][e]

[msg btl_support_06_665]
[s][vp 8 1 65535 665 0 0]It's strong, and guns won't help![n]Be careful![n][f 1 6 65534][e]

[msg btl_support_06_666]
[s][vp 8 1 65535 666 0 0]It's strong... Use anything but[n]Fire skills![n][f 1 6 65534][e]

[msg btl_support_06_667]
[s][vp 8 1 65535 667 0 0]It's strong, and has a significant[n]resistance to Ice![n][f 1 6 65534][e]

[msg btl_support_06_668]
[s][vp 8 1 65535 668 0 0]No Wind skills! It's powerful,[n]so stay on guard![n][f 1 6 65534][e]

[msg btl_support_06_669]
[s][vp 8 1 65535 669 0 0]This enemy is tough and Electric[n]attacks won't work on it![n][f 1 6 65534][e]

[msg btl_support_06_670]
[s][vp 8 1 65535 670 0 0]This could be tough. Bless skills[n]will be nullified, so be careful.[n][f 1 6 65534][e]

[msg btl_support_06_671]
[s][vp 8 1 65535 671 0 0]Hm, it's immune to Curse... I had[n]hoped we could end this quickly...[n][f 1 6 65534][e]

[msg btl_support_06_672]
[s][vp 8 1 65535 672 0 0]Strong and impervious to Nuclear[n]attacks! A bad match for me...[n][f 1 6 65534][e]

[msg btl_support_06_673]
[s][vp 8 1 65535 673 0 0]It's strong, and Psychokinesis[n]won't hurt it![n][f 1 6 65534][e]

[msg btl_support_06_674]
[s][vp 8 1 65535 674 0 0]We're evenly matched here.[n]Just don't let your guard down.[n][f 1 6 65534][e]

[msg btl_support_06_675]
[s][vp 8 1 65535 675 0 0]Its weak point is Physical strikes![n]This should be no problem![n][f 1 6 65534][e]

[msg btl_support_06_676]
[s][vp 8 1 65535 676 0 0]Gunfire gets through its defenses![n]Watch your remaining ammo![n][f 1 6 65534][e]

[msg btl_support_06_677]
[s][vp 8 1 65535 677 0 0]It's weak to fire. We're about[n]evenly matched, though.[n][f 1 6 65534][e]

[msg btl_support_06_678]
[s][vp 8 1 65535 678 0 0]The enemy's weak to Ice. Let's take[n]advantage of that.[n][f 1 6 65534][e]

[msg btl_support_06_679]
[s][vp 8 1 65535 679 0 0]Wind is effective! Keep calm,[n]and this will go smoothly![n][f 1 6 65534][e]

[msg btl_support_06_680]
[s][vp 8 1 65535 680 0 0]The playing field is even! It's weak[n]to Electricity![n][f 1 6 65534][e]

[msg btl_support_06_681]
[s][vp 8 1 65535 681 0 0]It's weak to Bless skills.[n]Do we have any ready?[n][f 1 6 65534][e]

[msg btl_support_06_682]
[s][vp 8 1 65535 682 0 0]A Curse skill might do it. If we can[n]manage an instant kill here...[n][f 1 6 65534][e]

[msg btl_support_06_683]
[s][vp 8 1 65535 683 0 0]Weak against Nuclear attacks?[n]Sounds like it's my turn.[n][f 1 6 65534][e]

[msg btl_support_06_684]
[s][vp 8 1 65535 684 0 0]This one's weak to Psychokinesis.[n][f 1 6 65534][e]

[msg btl_support_06_685]
[s][vp 8 1 65535 685 0 0]Physical attacks will be nullified.[n]Don't attack recklessly![n][f 1 6 65534][e]

[msg btl_support_06_686]
[s][vp 8 1 65535 686 0 0]Guns won't help here. Let's try[n]another tack.[n][f 1 6 65534][e]

[msg btl_support_06_687]
[s][vp 8 1 65535 687 0 0]Fire won't work![n][f 1 6 65534][e]

[msg btl_support_06_688]
[s][vp 8 1 65535 688 0 0]Ice is ineffective on this enemy.[n]Watch out.[n][f 1 6 65534][e]

[msg btl_support_06_689]
[s][vp 8 1 65535 689 0 0]Wind attacks shouldn't be used.[n]Look for something else![n][f 1 6 65534][e]

[msg btl_support_06_690]
[s][vp 8 1 65535 690 0 0]Electric skills are ineffective.[n]Watch your attacks![n][f 1 6 65534][e]

[msg btl_support_06_691]
[s][vp 8 1 65535 691 0 0]Bless skills won't do anything.[n]Let's switch our methods![n][f 1 6 65534][e]

[msg btl_support_06_692]
[s][vp 8 1 65535 692 0 0]Stay alert! Curse attacks won't work![n][f 1 6 65534][e]

[msg btl_support_06_693]
[s][vp 8 1 65535 693 0 0]So it's immune to Nuclear...[n]I suppose I'm useless here...[n][f 1 6 65534][e]

[msg btl_support_06_694]
[s][vp 8 1 65535 694 0 0]Psychokinesis is no good.[n]That's a bit annoying...[n][f 1 6 65534][e]

[msg btl_support_06_695]
[s][vp 8 1 65535 695 0 0]This enemy is beneath us. It should[n]be easy if we stay focused.[n][f 1 6 65534][e]

[msg btl_support_06_696]
[s][vp 8 1 65535 696 0 0]It is weak and vulnerable to[n]Physical strikes. Let's go![n][f 1 6 65534][e]

[msg btl_support_06_697]
[s][vp 8 1 65535 697 0 0]Gunfire is our best shot![n]Let's mop them up![n][f 1 6 65534][e]

[msg btl_support_06_698]
[s][vp 8 1 65535 698 0 0]We are the better fighters! Use Fire[n]attacks to hit its weak point![n][f 1 6 65534][e]

[msg btl_support_06_699]
[s][vp 8 1 65535 699 0 0]The enemy is weak against Ice.[n]Don't worry, we're stronger![n][f 1 6 65534][e]

[msg btl_support_06_700]
[s][vp 8 1 65535 700 0 0]It's clearly inferior! Win with[n]Wind attacks![n][f 1 6 65534][e]

[msg btl_support_06_701]
[s][vp 8 1 65535 701 0 0]Electricity is its weak point! This[n]should be no problem for you![n][f 1 6 65534][e]

[msg btl_support_06_702]
[s][vp 8 1 65535 702 0 0]Bless skills will work here.[n]The enemy is weak, but[n]don't relax yet![n][f 1 6 65534][e]

[msg btl_support_06_703]
[s][vp 8 1 65535 703 0 0]Curse skills will work![n][f 1 6 65534][e]

[msg btl_support_06_704]
[s][vp 8 1 65535 704 0 0]It's weak to Nuclear moves.[n]Let's end this quickly![n][f 1 6 65534][e]

[msg btl_support_06_705]
[s][vp 8 1 65535 705 0 0]Psychokinetic moves should help[n]here. It won't be a problem.[n][f 1 6 65534][e]

[msg btl_support_06_706]
[s][vp 8 1 65535 706 0 0]They're weak, but Physical attacks[n]won't help here.[n][f 1 6 65534][e]

[msg btl_support_06_707]
[s][vp 8 1 65535 707 0 0]The opponent's weak. Gunshots[n]won't work, so try something else![n][f 1 6 65534][e]

[msg btl_support_06_708]
[s][vp 8 1 65535 708 0 0]Fire's not going to work...[n]Aggravating for such a weak one.[n][f 1 6 65534][e]

[msg btl_support_06_709]
[s][vp 8 1 65535 709 0 0]Ice attacks are out. They're weak,[n]but don't let your guard down.[n][f 1 6 65534][e]

[msg btl_support_06_710]
[s][vp 8 1 65535 710 0 0]The enemy is weak, but Wind[n]won't do much to it.[n][f 1 6 65534][e]

[msg btl_support_06_711]
[s][vp 8 1 65535 711 0 0]It isn't a major threat, but don't[n]use Electric attacks.[n][f 1 6 65534][e]

[msg btl_support_06_712]
[s][vp 8 1 65535 712 0 0]Don't use Bless attacks![n]Try something else![n][f 1 6 65534][e]

[msg btl_support_06_713]
[s][vp 8 1 65535 713 0 0]Curse skills are ineffective![n]Stay focused![n][f 1 6 65534][e]

[msg btl_support_06_714]
[s][vp 8 1 65535 714 0 0]Nuclear attacks won't work?[n]Strange... It seems weak otherwise.[n][f 1 6 65534][e]

[msg btl_support_06_715]
[s][vp 8 1 65535 715 0 0]No Psychokinesis! Attack with[n]something else![n][f 1 6 65534][e]

[msg btl_support_06_894]
[s][vp 8 1 65535 1106 0 0]It might not have a weakness![n]Maybe try making it sleepy?[n][f 1 6 65534][e]

[msg btl_support_06_895]
[s][vp 8 1 65535 1107 0 0]It doesn't seem to have a weakness.[n]Let's try making it dizzy![n][f 1 6 65534][e]

[msg btl_support_06_896]
[s][vp 8 1 65535 1108 0 0]No weaknesses!? Well... how about[n]we make it forget its skills?[n][f 1 6 65534][e]

[msg btl_support_06_897]
[s][vp 8 1 65535 1109 0 0]It doesn't have a weakness, but...[n]I think we could make it angry![n][f 1 6 65534][e]

[msg btl_support_06_898]
[s][vp 8 1 65535 1110 0 0]Well, if it has no weakness,[n]why not try brainwashing it?[n][f 1 6 65534][e]

[msg btl_support_06_899]
[s][vp 8 1 65535 1111 0 0]It has no weakness... our best[n]chance is to make it confused![n][f 1 6 65534][e]

[msg btl_support_06_900]
[s][vp 8 1 65535 1112 0 0]It has no physical weakness, so let's[n]use an emotional weapon: fear![n][f 1 6 65534][e]

[msg btl_support_06_901]
[s][vp 8 1 65535 1113 0 0]It has no weakness, but we can try[n]overwhelming it with despair![n][f 1 6 65534][e]

[msg btl_support_06_902]
[s][vp 8 1 65535 1114 0 0]There's a forgetful enemy that[n]would be especially vulnerable[n]to Electricity.[n][f 1 6 65534][e]

[msg btl_support_06_903]
[s][vp 8 1 65535 1115 0 0]Look at how angry it is! Hit it with[n]some Psychokinesis![n][f 1 6 65534][e]

[msg btl_support_06_904]
[s][vp 8 1 65535 1116 0 0]Now the enemy is just a[n]brainwashed drone! Use[n]Psychokinesis![n][f 1 6 65534][e]

[msg btl_support_06_905]
[s][vp 8 1 65535 1117 0 0]Look, there's an enemy that's[n]confused! Give it some[n]Psychokinesis![n][f 1 6 65534][e]

[msg btl_support_06_906]
[s][vp 8 1 65535 1118 0 0]Do you see that scared one?[n]Psychokinesis would be[n]perfect now.[n][f 1 6 65534][e]

[msg btl_support_06_907]
[s][vp 8 1 65535 1119 0 0]One enemy is in despair, so[n]Psychokinesis would be a[n]good move.[n][f 1 6 65534][e]

[msg btl_support_06_908]
[s][vp 8 1 65535 1120 0 0]I recommend attacking any[n]enemy who has a status ailment![n][f 1 6 65534][e]

